### ISSUE TITLE
[BUG] Unicode `REPLACEMENT CHARACTER`(efbfbd) in Buffers

### ISSUE THREAD

**Issue by icefed** [ibhagwan/fzf-lua#672] opened 2023-03-02 06:35 UTC
### Info

- Operating System: MacOS
- Shell: zsh
- Terminal: Iterm2
- `nvim --version`: v0.8.2
- `fzf --version`: 0.37.0 (brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    winopts = {
      height = 0.85, -- window height
      width = 0.85, -- window width
      preview = {
        horizontal = "right:50%",
        scrollbar = false,
      },
    },
    files = {
      prompt = "Files> ",
      rg_opts = "--color=never --files --follow -g '!.git'",
      fd_opts = "--color=never --type f --follow --exclude .git",
    },
    grep = {
      prompt = "Rg> ",
      input_prompt = "Grep For> ",
    },

})
```
</details>

### Description 

Sometimes it comes, sometimes it doesn't.

![](https://user-images.githubusercontent.com/3964419/222348835-1041d857-5d17-48c5-9360-d0a1e69ce45e.png)

**Comment by ibhagwan** [comment] 2023-03-02 07:01
I noticed that too with buffers, there’s a good chance this is an upstream bug.

**Comment by ibhagwan** [comment] 2023-05-25 18:06
@icefed, I haven’t encountered this issue in months, I have a feeling this was upstream (this character isn’t anywhere in fzf-lua’s code), although I can’t pin point the exact issue it does seem fixed on my end.

If you find a semi consistent way of reproducing this issue please reopen and I’ll take another look.

**Comment by nyngwang** [comment] 2023-05-26 04:15
I also encountered this one many times. I think it has something to do with the transparent/blend of the floating window:

1. When the character(s) behind the line containing `efbfbd` matches a certain pattern, this just happened.
2. I used to think that this might be related to the input method being used, but since you also encountered it I think it's not related.

**Comment by ibhagwan** [comment] 2023-05-26 09:10
> When the line under the current floating window that contains efbfbd matches a certain pattern, this just happened.

If that’s the case that would be an upstream bug, fzf-lua doesn’t use this character at all in the code, where would it appear from?

Can you reproduce this consistently and let me know the steps?

**Comment by liangxianzhe** [comment] 2023-06-20 22:25
Hi @ibhagwan 

I might have a consistent repro. I guess the issue is related to how brackets are parsed, but didn't get a chance to dig deep.

To repro, copy the below config to somewhere like `~/.config/bug-report/init.lua`, then `NVIM_APPNAME="bug-report" nvim`, then press `fk` and you will see the issue.

Env: `NVIM v0.10.0-dev-1884+ga05bbc60e-Homebrew`, latest fzf-lua, macos, alacritty.

```lua
local map = vim.keymap.set

-- Install Lazy when first opening nvim. Use ':Lazy' to install/update plugins.
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "--single-branch",
    "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  { "nvim-tree/nvim-web-devicons", config = true, }, -- File type icons
  {
    "ibhagwan/fzf-lua",                              -- Fuzzy search everything
    config = function()
      require('fzf-lua').setup({})
      require("fzf-lua").register_ui_select() -- Use fzf for vim.ui.select, such as code actions, etc
      local f = "f"
      local F = "F"

      map("n", f .. "<space>", require('fzf-lua').builtin, { desc = "[f] All fzf commands" })
      map("n", f .. "a", require("fzf-lua").tabs, { desc = "[f] Tabs" })
      map("n", f .. "b", require("fzf-lua").buffers, { desc = "[f] Buffesr" })
      map("n", f .. "c", require("fzf-lua").git_bcommits, { desc = "[f] Commits for current file" })
      map("n", F .. "C", require("fzf-lua").git_commits, { desc = "[f] Commits for repo" })
      map("n", f .. "d", require("fzf-lua").diagnostics_document, { desc = "[f] Diagnostics in buffer" })
      map("n", F .. "D", require("fzf-lua").diagnostics_workspace, { desc = "[f] Diagnostics in workplace" })
      map("n", f .. "e", require('fzf-lua').changes, { desc = "[f] Edits (change list)" })
      map("n", f .. "f", require('fzf-lua').files, { desc = "[f] Files in cwd" })
      map("n", F .. "F", require('fzf-lua').git_files, { desc = "[f] Files in repo" })
      map("n", f .. "g", require('fzf-lua').live_grep_glob, { desc = "[f] Grep" })
      map("n", F .. "G", require('fzf-lua').grep_project, { desc = "[f] Fuzzy search project" })
      map("n", f .. "h", require("fzf-lua").git_status, { desc = "[f] Hunks (git status)" })
      map("n", f .. "j", require('fzf-lua').jumps, { desc = "[f] Jumps" })
      map("n", f .. "k", function() require('fzf-lua').keymaps({ query = "[]" }) end, { desc = "[f] Keybindings" })
      map("n", f .. "l", require('fzf-lua').loclist, { desc = "[f] Loclist" })
      map("n", F .. "L", require('fzf-lua').loclist_stack, { desc = "[f] Loclist history" })
      map("n", f .. "o", function() require("fzf-lua").lsp_document_symbols({ symbol_fmt = false, symbol_style = 2 }) end,
        { desc = "[f] Symbols in buffer" })
      map("n", F .. "O", require("fzf-lua").lsp_workspace_symbols, { desc = "[f] Symbols in repo" })
      map("n", f .. "q", require('fzf-lua').quickfix, { desc = "[f] Quickfix" })
      map("n", F .. "Q", require('fzf-lua').quickfix_stack, { desc = "[f] Quickfix history" })
      map("n", f .. "r", function() require("fzf-lua").oldfiles({ cwd_only = true }) end,
        { desc = "[f] Recent files in cwd" })
      map("n", F .. "R", require("fzf-lua").oldfiles, { desc = "[f] Recent files" })
      map("n", f .. "t", require("fzf-lua").btags, { desc = "[f] Tags in buffer" })
      map("n", F .. "T", require("fzf-lua").tags, { desc = "[f] Tags in repo" })
      map("n", f .. "w", require('fzf-lua').grep_cword, { desc = "[f] Grep cursor word" })
      map("n", F .. "W", require('fzf-lua').grep_cWORD, { desc = "[f] Grep cursor WORD" })

      map("n", f .. ".", require("fzf-lua").resume, { desc = "[f] Continue last fzf session" })
      map("n", f .. ";", require('fzf-lua').commands, { desc = "[f] Commands" })
      map("n", F .. ":", require('fzf-lua').command_history, { desc = "[f] Command history" })
      map("n", f .. "'", require('fzf-lua').marks, { desc = "[f] Marks" })
      map("n", F .. "\"", require('fzf-lua').registers, { desc = "[f] Registers" })
      map("n", f .. "/", require('fzf-lua').search_history, { desc = "[f] Search history" })
      map("n", f .. "1", require('fzf-lua').help_tags, { desc = "[f] Help tags" })

      map("n", "z=", require("fzf-lua").spell_suggest, { desc = "[f] Spell suggestion" }) -- Override the default ":h z="
    end
  },
}

require("lazy").setup(plugins)
```

**Comment by ibhagwan** [comment] 2023-06-21 02:55
@liangxianzhe, just tried with latest nightly and the provided `init.lua` and no success in repro:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/dc7f0e4b-8568-4e86-94c2-13de84b7fe52)

**Comment by ibhagwan** [comment] 2023-06-21 02:55
@liangxianzhe, what version of fzf are you using btw?

**Comment by liangxianzhe** [comment] 2023-06-21 05:32
0.42.0, which is latest. I noticed that it repros consistently on alacritty, but not on wezterm (though my full config, which has more key bindings, repros on wezterm too). If it doesn't repro for you, I will try debug on my side when I got some time.

**Comment by liangxianzhe** [comment] 2023-06-21 05:34
New finding, it only repros for certain terminal window's size. Try zoom in and out a few times.

**Comment by liangxianzhe** [comment] 2023-06-21 05:35
![image](https://github.com/ibhagwan/fzf-lua/assets/1334962/4a74435e-aae9-4166-9dbd-f8ee7b695325)

**Comment by nyngwang** [comment] 2023-06-21 11:28
@liangxianzhe Hi, really thank you for creating the repo of the issue!

**Comment by ibhagwan** [comment] 2023-06-21 20:15
> New finding, it only repros for certain terminal window's size. Try zoom in and out a few times.

Ty @liangxianzhe, reopened the issue but unfortunnately I still cannot reproduce this using both alacritty and fzf `0.42`.

Also, given that fzf-lua doesn't draw anything when zooming in/out I stand by my initial analysis that **this is an upstream issue**.

My suggestions is we try to reproduce it in the shell and once we have decent repro steps open an issue upstream.

**Comment by ibhagwan** [comment] 2023-06-22 14:52
Following the discussion in #791, @liangxianzhe identified this issue as https://github.com/neovim/neovim/issues/16245, it seems there is not much we can do from fzf-lua’s side without the upstream being fixed.

**Comment by ibhagwan** [comment] 2024-03-19 15:51
FYI, the issue was resolved upstream in https://github.com/neovim/neovim/pull/27922.

Can anyone who had this easily reproduced  try this out once the next nightly is released?

**Comment by icefed** [comment] 2024-03-20 08:43
I've been using it for a few minutes, it looks like the problem is gone.

Open same session(nightly left):
<img width="1903" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/3964419/3d26b05d-73e3-44bd-87d3-a811c54b1720">

**Comment by ibhagwan** [comment] 2024-03-20 14:47
Ty for the update @icefed, I also feel confident this issue can be closed, ty everyone for your efforts troubleshooting  this!

**Closed by ibhagwan** 2024-03-20 14:47 UTC
Labels: upstream
