### ISSUE TITLE
`cursorline` gets reset when opening files

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#254] opened 2021-12-13 22:00 UTC
I have `cursorline` set in my `init.vim`. However, when I open a new file using **fzf-lua**, its uses `nocursorline`.

## Reproduction

1. First, here's the `init.vim` I used for this test:
    ```vim
    let g:vimDir = stdpath('config')

    call plug#begin(g:vimDir . '/bundle')
    Plug 'ibhagwan/fzf-lua'
    call plug#end()

    set cursorline
    ```
2. Create test files:
    ```sh
    echo hello > b
    echo world > a
    ```

3. Open `b`: `nvim b`

    Make sure `cursorline` is set and visible.

4. Run `:FzfLua files`
5. Highlight `a` (this should be the default) and open a new split by hitting **CTRL+v**
6. Note that the window containing the file `a` does not have a cursor line. Confirm by querying `cursorline`:
    ```
    :set cursorline?
    nocursorline
    ```

## Environment
* Neovim v0.6.0
* Ubuntu 20.04.3 LTS
* Windows 10 WSL2

**Comment by ibhagwan** [comment] 2021-12-13 22:22
Few things to try so we can narrow this down:

1. Can you try also calling the `setup` function from `init.vim` by adding the below?
```lua
lua << EOF
require('fzf-lua').setup{}
EOF
```

2. I suspect this might be related to the builting previewer not restoring options properly (althought weird since it also uses `cursorline`), can you try with the `bat` (or `cat` if you don't have `bat` installed)?
```lua
lua << EOF
require('fzf-lua').setup{
  winopts = {
    preview = { default = 'bat' }
  }
}
EOF
```

3. We can also try with the default previewer with `cursorline` removed from `winopts`:
```lua
lua << EOF
require('fzf-lua').setup{
  winopts = {
    preview = {
      winopts = {
        number            = true,
        relativenumber    = false,
        -- cursorline        = true,
        -- cursorlineopt     = 'both',
        cursorcolumn      = false,
        signcolumn        = 'no',
        list              = false,
        foldenable        = false,
        foldmethod        = 'manual',
      },
    }
  }
}
EOF
```

**Comment by shyun3** [comment] 2021-12-13 22:31
I tried all 3 and they didn't make a difference ☹

**Comment by ibhagwan** [comment] 2021-12-13 22:34
> I tried all 3 and they didn't make a difference frowning_face

Don't worry I promise you we'll get to the bottom of this :-)

I'm going to try to reproduce this myself (I have no such issue ATM, also using `cursorline`) with this [minimal `init.lua`](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua), if you can try as well it would be great, all you have to do is save this file as `init.lua` and delete `init.vim` (they conflict) and it would the rest for you, download `packer.nvim` lua plugin manager and install `fzf-lua`.

**Comment by shyun3** [comment] 2021-12-13 22:59
I used your `minimal_init.lua` with this extra line at the end to enable `cursorline`: `vim.opt.cursorline = true`

I repeated my steps and the `a` window did have `cursorline` set. However, I closed the window and kept repeating the procedure until about the 5th or 6th attempt, `a` opened to using `nocursorline`.

To be more explicit, the additional steps are:
7. If `cursorline` is set, close the window using `:q`
8. Repeat steps 4-7 until `nocursorline` is observed in the `a` window. This may take around 6 tries.

Sometimes it only takes 2-3 tries. Strange that it's non-deterministic like this.

**Comment by ibhagwan** [comment] 2021-12-13 23:08
> I used your `minimal_init.lua` with this extra line at the end to enable `cursorline`: `vim.opt.cursorline = true`
> 
> I repeated my steps and the `a` window did have `cursorline` set. However, I closed the window and kept repeating the procedure until about the 5th or 6th attempt, `a` opened to using `nocursorline`.
> 
> To be more explicit, the additional steps are: 7. If `cursorline` is set, close the window using `:q` 8. Repeat steps 4-7 until `nocursorline` is observed in the `a` window. This may take around 6 tries.
> 
> Sometimes it only takes 2-3 tries. Strange that it's non-deterministic like this.

I see, that's very strange indeed and I also don't understand why the difference between `init.vim` and `init.lua` both do pretty much nothing but install `fzf-lua` and that's it (albit with a different plugin manager which is also a plugin by itself).

What's more confusing is that there's never any line of code that sets `nocursorline`, what the builtin preview does is copy the `cursorline` option from the source window and the set the preview buffer with these options before closing as there's a behavior in neovim where the source window would "inherit" these options from an existing window before closure.

Now all of the above applies to the builtin previewer but you also told me you tried with `bat` and it still didn't work, the entire "backup/restore" window options code doesn't even apply with `bat` as it's all handled internally in the terminal.

**Comment by ibhagwan** [comment] 2021-12-14 00:30
hi @shyun3, I was able to reproduce this but it seems this only happens when opening files in new windows (splits or tabs) - can you confirm this is only for new wins (i.e. if you open a new buffer in the current window with `<CR>` it doesn't happen.

I'll have a fix for this issue shortly.

**Comment by shyun3** [comment] 2021-12-14 00:41
Yeah, it seems like it only happens for new windows.

**Comment by ibhagwan** [comment] 2021-12-14 01:55
This issue is driving me nuts, can't seem to figure out why this is happening, I even printed `vim.wo.cursorline` in the code after opening the window which returns `true` yet `set cursorline?` on the affected buffer returns `nocursorline`.

To add to the mess, the issue isn't very consistent...

**Comment by ibhagwan** [comment] 2021-12-14 04:31
After furhter investigation this seems to an issue related to opening a new windows after having the terminal open.

The neovim runtime script `/usr/share/nvim/runtime/plugin/fzf.vim` defines a command `:FZF` which also exhibits the same behavior when opening files in a split (`<C-s>` or `<C-v>`).

I personally never noticed this behavior as I have an autocmd that enables `cursorline` only for the active buffer (makes it easiler to find your active window).

**Comment by shyun3** [comment] 2021-12-14 05:15
Oh so, this is a Neovim issue?

Could you also post your autocommand?

**Comment by ibhagwan** [comment] 2021-12-14 11:05
> Oh so, this is a Neovim issue?

Not sure if it's an issue per-se or "intended" behavior, I'm still researching this,I feel this might be related to the fact I set the terminal fieltype to `fzf` which perhaps uses special filetype settings inside neovim?

> Could you also post your autocommand?

```lua
au.group('ActiveWinCursorLine', {
  -- Highlight current line only on focused window
  {'WinEnter,BufEnter,InsertLeave', '*', 'if ! &cursorline && ! &pvw | setlocal cursorline | endif'};
  {'WinLeave,BufLeave,InsertEnter', '*', 'if &cursorline && ! &pvw | setlocal nocursorline | endif'};
})
```
You can find it [in my neovim config](https://github.com/ibhagwan/nvim-lua/blob/f1a9fb3a9872982b4ee20d4dc1e7a8a3c8f5b865/lua/autocmd.lua#L39-L43) which uses [au.lua](https://github.com/ibhagwan/nvim-lua/blob/main/lua/au.lua) to setup these commands.

**Comment by ibhagwan** [comment] 2021-12-14 11:57
I may have found the issue, still not sure why this setting causes neovim to bug out and reset `cursorline` to new windows but this is definitely what's setting the `fzf` window to `nocursorline`, it's the `nvim_open_win_api` with `minimal` specified (from `:help nvim_open_win`):
```help
                              • style: Configure the appearance of the window.
                                Currently only takes one non-empty value:
                                • "minimal" Nvim will display the window with
                                  many UI options disabled. This is useful
                                  when displaying a temporary float where the
                                  text should not be edited. Disables
                                  'number', 'relativenumber', 'cursorline',
                                  'cursorcolumn', 'foldcolumn', 'spell' and
                                  'list' options. 'signcolumn' is changed to
                                  `auto` and 'colorcolumn' is cleared. The
                                  end-of-buffer region is hidden by setting
                                  `eob` flag of 'fillchars' to a space char,
                                  and clearing the |EndOfBuffer| region in
                                  'winhighlight'.
```

**Closed** 2021-12-14 12:15 UTC
Labels: bug, invalid

**Comment by ibhagwan** [comment] 2021-12-14 12:19
https://github.com/ibhagwan/fzf-lua/commit/d07c5c85225e4681f2be788fa1fccb2d9fe8108a wohoo! managed to work around this by restoring `cursorline` in the fzf popup (only if the user had it turned on prior), this seems to solve the problem (which is most likely a neovim bug) and doesn't affect anything else, the cursorline setting doesn't change behavior or visuals since we're already always in terminal insert mode when using fzf.
