### ISSUE TITLE
fzf-project

### ISSUE THREAD

**Issue by archaict** [ibhagwan/fzf-lua#26] opened 2021-07-30 12:40 UTC
Hello, this is a little implementation that maybe can be used for project management, I think it can also be improved with keybindings to help adding and remove it directly, it is a simple solution :) Thank you for this project!

``` lua
function fzf_projectionist()
  local project_dirs = {
    "~/.config",
    "~/.config/nvim",
  }
  coroutine.wrap(function()
    local choice = require "fzf".fzf(project_dirs)
    if choice then
      require('fzf-lua').files({ cwd = choice[1] })
    end
  end)()
end
```

**Comment by vijaymarupudi** [comment] 2021-07-30 14:30
This snippet makes me really happy, it's a perfect example of the extensibility of `nvim-fzf` and the customizability of `fzf-lua` while being minimalist. Thanks for sharing, I'll be using it :)

**Comment by ibhagwan** [comment] 2021-07-30 15:13
Great idea and implementation, this will def go in the Wiki examples :)

**Comment by archaict** [comment] 2021-08-02 08:13
hello, adding more for wallpaper (through feh):
``` lua
function fzf_wallpaper()
  coroutine.wrap(function()
    local fzf = require("fzf")
    local result = fzf.fzf("fd . ~/Pictures -e png -e jpg")
    if result then
      vim.cmd('!feh --bg-fill ' .. result[1])
    end
  end)()
end
```
is it possible to see preview images through fzf-lua, either using ueberzug or w3m? I know it's not its core feature, but it is nice if its possible 😊

**Comment by ibhagwan** [comment] 2021-08-04 06:22
> is it possible to see preview images through fzf-lua, either using ueberzug or w3m? I know it's not its core feature, but it is nice if its possible

Interesting idea, In the last couple of days I refactored the previewer code to make it more extensible and I believe it should possible now, perhaps with `sxiv`? or basically any command line utility that can display images in the terminal, basically if you can make it work from the shell we can make it work inside `nvim`.

>also adding this [fzf-lua-extensions](https://github.com/archaict/fzf-lua-extensions)!

Very cool! I'll def add a link to this.

The only issue is I have higher priority work to add to `fzf-lua` I can't seem to find time to continue writing [the Wiki](https://github.com/ibhagwan/fzf-lua/wiki)

**Comment by ibhagwan** [comment] 2021-08-04 06:28
Some clues on how to make `fzf` preview images [fzf issue #738](https://github.com/junegunn/fzf/issues/738), [fzf issue #2551](https://github.com/junegunn/fzf/issues/2551), perhaps possible with [termpix](https://github.com/hopey-dishwasher/termpix)?

Let me know if you can make it work in the terminal and I'll instruct you how to use the new previewers code to use whatever program you find that works.

**Comment by archaict** [comment] 2021-08-04 11:35
hello, yes, it is possible using `termpix`, I've just tried it now 😆 
I think I just need to change it to vertical rather than horizontally now!
This is the code I use, I think it can be improved further, but for now, this is what I've tried (termpix required, using   [this](https://github.com/mmacedoeu/termpix) fork of termpix ( since masters seems to have bug on install )
```lua
local fzf = require("fzf").fzf
local action = require "fzf.actions".action
coroutine.wrap(function()
  fzf('fd . ~/Pictures -e png -e jpg', [[--preview "((termpix --width 70 --true-colour {} > /tmp/termpixdump && cat /tmp/termpixdump) || bat {})"]])
end)()
```

**Comment by archaict** [comment] 2021-08-04 11:44
and this one for setting the wallpaper with preview, I also see that there's a possibility of using ueberzug, telescope seems to have [this extensions](https://github.com/nvim-telescope/telescope-media-files.nvim) but I think this will suffice for now, since everything is running from terminal and can be used with or without gpu help ( alacritty or xterm should prolly work )

```lua
local fzf = require("fzf").fzf
local action = require "fzf.actions".action
coroutine.wrap(function()
  local choice = fzf('fd . ~/Pictures -e png -e jpg', [[--preview "((termpix --width 70 --true-colour {} > /tmp/termpixdump && cat /tmp/termpixdump) || bat {})"]])
  if choice then
    vim.cmd('silent !feh --bg-fill ' .. choice[1])
  end
end)()
```

**Comment by ibhagwan** [comment] 2021-08-04 13:17
> EDIT: is there a way to use fzf-lua devicons to be used with this?

Should be possible using `core.fzf_files`, look at the [files provider code](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/files.lua), you can just replicate that and send any command or `fzf_fn` you wish:

```lua
M.files = function(opts)

  opts = config.normalize_opts(opts, config.globals.files)

  local command = get_files_cmd(opts)

  opts.fzf_fn = fzf_helpers.cmd_line_transformer(command,
    function(x)
      return core.make_entry_file(opts, x)
    end)

  return core.fzf_files(opts)
end

```


> EDIT2: add autowallpaper, sorry for spamming edits here, tell me if it is problematic 😢

Absolutely no problem.

**Comment by ibhagwan** [comment] 2021-08-04 22:45
FYI, I just added a new custom previewer might help you achieve the image previewer in an easier way (with icons if you wish):

First you'd need to configure the previewer cmd (see the README where this fits):
```lua
...
    previewers = {
      cmd = {
        -- custom previewer, will execute:
        -- `<cmd> <args> <filename>`
        cmd             = "termpix",
        args            = "--width 70 --true-colour",
      },
...
```

Then you can just run
```lua
:lua require('fzf-lua').files({ cwd = "~/Pictures", previewer = "cmd" })
```

This is just a sample, you're not limited to the `cmd` previewer, you can define as many as you want like below (must have `_new` defined):
```lua
    termpix = {
      cmd             = "termpix",
      args            = "",
      _new            = function() return require 'fzf-lua.previewer'.cmd_async end,
    },
```

**Comment by archaict** [comment] 2021-08-05 04:06
It works as intended 😄 
```lua
function fzf_pictures()
  local action = require "fzf.actions".action
  local choice = require('fzf-lua').files({
    cwd       = "~/Pictures",
    prompt    = 'Wallpaper » ',
    previewer = "termpix",
    actions = {
      ["default"]  = function(selected) vim.cmd('silent !feh --bg-fill ' .. selected[2]) end
    }
  })
end
```
I think this previewer will help with many creative ideas people may have in the future!

**Comment by ibhagwan** [comment] 2021-08-05 05:04
> It works as intended 😄
> 
> ```lua
> function fzf_pictures()
>   require('fzf-lua').files({
>     cwd       = "~/Pictures",
>     prompt    = 'Wallpaper » ',
>     previewer = "termpix",
>     actions = {
>       ["default"]  = function(selected) vim.cmd('silent !feh --bg-fill ' .. selected[2]) end
>     }
>   })
> end
> ```
> 
> I think this previewer will help with many creative ideas people may have in the future!

Fantastic! :)

**Comment by ibhagwan** [comment] 2021-08-05 16:43
Closing this for now, when I work on the Wiki, this will all be added as well as a link to [fzf-lua-extensions](https://github.com/archaict/fzf-lua-extensions).

**Closed by ibhagwan** 2021-08-05 16:43 UTC
Labels: documentation

**Comment by ibhagwan** [comment] 2021-09-09 22:33
FYI, I updated the previewer interface code to make it easier to write future extensions, you can now send the previewer directly to the function or to adjust to what you wrote  above (notice `_ctor` instead of `_new`).

```lua
termpix = {
      cmd             = "termpix",
      args            = "",
      _ctor            = require'fzf-lua.previewer'.fzf.cmd_async,
    },
```

Or you can send it directly to the function like this:

```lua
require('fzf-lua').files({ previewer = {
      cmd             = "termpix",
      args            = "",
      _ctor            = require'fzf-lua.previewer'.fzf.cmd_async,
   }
})
```

**Comment by ibhagwan** [comment] 2022-03-13 13:05
It's been a long time @archaict but I'm still posting it here for documentation purposes in the chance you might find this useful.

From [Can fzf-lua preview media files?](https://github.com/ibhagwan/fzf-lua/wiki#media-preview):

![MediaDemo](https://raw.githubusercontent.com/wiki/ibhagwan/fzf-lua/demo-media.gif)

**Comment by jaekyeom** [comment] 2022-03-13 14:07
@ibhagwan Hi, thanks for the great news!
It looks amazing. I've got some questions.

1. Do both `previewer` and `previewers` work in the config, or is [it](https://github.com/ibhagwan/fzf-lua/wiki#media-preview) a typo?
2. I'm using iTerm, and the environment variables are `TERM=xterm-256color`, `COLORTERM=truecolor`, and `TERM_PROGRAM=iTerm.app`.
  I tried `viu` and it works well as a separate command e.g., `viu image_file.png`.
  However, with fzf-lua, it seems that the previewer just terminates (`[Process exited 0]`), and it only works when the environment variable `TERM_PROGRAM` is not set, which produces blurry previews.
  Do you have any idea why this issue is happening?
3. What do you think about making the `extensions` option case-insensitive?

**Comment by ibhagwan** [comment] 2022-03-13 18:20
> 1. Do both previewer and previewers work in the config, or is a typo?

A typo in the wiki, the cost of programming at 6am :)

> 2. I tried viu and it works well as a separate command e.g., viu image_file.png.
> However, with fzf-lua, it seems that the previewer just terminates ([Process exited 0]) with empty outputs

I noticed the same on the Mac, this is an issue with the neovim terminal, if you open a new terminal inside neovim with `:new | term` and run `viu <image>` you’ll see no output, **however, if you do the same inside `tmux`, it works.**

I’m still unsure why this happens, I’m working on a list of external programs to add to the wiki with notes on which work on Linux/Mac and how to use them.

Technically, for Mac, the best would be to use [`iTerm`’s own `imgcat`](https://iterm2.com/3.2/documentation-utilities.html) which renders beautiful images but the issue again is that it doesn’t work inside tmux or the neovim terminal (same goes for kitty’s imgcat).

Btw, have you tried `termpix` instead of `viu` - I recall you used that before.

> 3. What do you think about making the extensions option case-insensitive?

Makes sense, I’ll add it in the next commit.

**Comment by jaekyeom** [comment] 2022-03-13 20:18
Thanks for the detailed comment!

> I noticed the same on the Mac, this is an issue with the neovim terminal, if you open a new terminal inside neovim with `:new | term` and run `viu <image>` you’ll see no output, **however, if you do the same inside `tmux`, it works.**
> 
> I’m still unsure why this happens, I’m working on a list of external programs to add to the wiki with notes on which work on Linux/Mac and how to use them.
> 
> Technically, for Mac, the best would be to use [`iTerm`’s own `imgcat`](https://iterm2.com/3.2/documentation-utilities.html) which renders beautiful images but the issue again is that it doesn’t work inside tmux or the neovim terminal (same goes for kitty’s imgcat).

Oh, I wasn't aware of that. 
It looks that https://github.com/neovim/neovim/issues/4349 is the long-standing issue that prevents using `imgcat` (and maybe `viu` as well) inside Neovim's terminal buffers.

> Btw, have you tried `termpix` instead of `viu` - I recall you used that before.

Actually, my last comment was my first comment on this issue. I was just a subscriber 😅 

> > 3. What do you think about making the extensions option case-insensitive?
> 
> Makes sense, I’ll add it in the next commit.

Sounds great, thank you!

**Comment by ibhagwan** [comment] 2022-03-13 20:27
>Actually, my last comment was my first comment on this issue. I was just a subscriber

I just realized that, I never imagined anyone other than the OP responding to such an old issue lol

>It looks that https://github.com/neovim/neovim/issues/4349 is the long-standing issue that prevents using imgcat (and maybe viu as well) inside Neovim's terminal buffers.

Ty for find that! I'll take a look.

https://github.com/ibhagwan/fzf-lua/commit/c8973d5a17af6e3e85fa5dccb74a9c360acb0c5b - this commit already takes care of the lowercase extensions so it should work regardless of the capitalization of either the file extension or your choice of capitalization in the config.

**Comment by ibhagwan** [comment] 2022-03-13 22:15
@jaekyeom, few updates:

- [The wiki](https://github.com/ibhagwan/fzf-lua/wiki#media-preview) was updated (although I have a few more utilities to add for icons, epub, fonts, PDFs, etc)

- A solution for the below:

>I tried viu and it works well as a separate command e.g., viu image_file.png.
However, with fzf-lua, it seems that the previewer just terminates ([Process exited 0]) with empty outputs, and it only works when the environment variable TERM_PROGRAM is not set, which produces blurry previews.
Do you have any idea why this is happening?

When `iTerm` (or `kitty`) without `tmux`,  `viu` attempts to draw a high resolution image using something similar to [the kitty graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) which isn't supported inside a neovim terminal (as you've found out in https://github.com/neovim/neovim/issues/4349), the solution is to always use `viu -b` to output in `block mode`, unfortuntaely that means blurry previews but it's better than nothing.

```lua
require("fzf-lua").setup({
  previewers = {
    builtin = {
      extensions = {
        -- neovim terminal only supports `viu` block output
        ["png"] = { "viu", "-b" },
        ["jpg"] = { "viu", "-b" },
      }
  },
})
```

**Comment by jaekyeom** [comment] 2022-03-14 08:26
> [c8973d5](https://github.com/ibhagwan/fzf-lua/commit/c8973d5a17af6e3e85fa5dccb74a9c360acb0c5b) - this commit already takes care of the lowercase extensions so it should work regardless of the capitalization of either the file extension or your choice of capitalization in the config.

Thanks, I'll check it out!

> When `iTerm` (or `kitty`) without `tmux`, `viu` attempts to draw a high resolution image using something similar to [the kitty graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) which isn't supported inside a neovim terminal (as you've found out in [neovim/neovim#4349](https://github.com/neovim/neovim/issues/4349)), the solution is to always use `viu -b` to output in `block mode`, unfortuntaely that means blurry previews but it's better than nothing.

It seems to me as well that it's the most reasonable workaround until the issue is resolved. I appreciate the kind, detailed guides (including the wiki updates).
