### ISSUE TITLE
Question. Why there is no support for file icons in live_grep, live_grep native?

### ISSUE THREAD

**Issue by LoydAndrew** [ibhagwan/fzf-lua#168] opened 2021-10-05 20:23 UTC
There is no file icons in live_grep, live_grep_native providers. Is this a deliberate choice or some sort of a bug?

**Comment by ibhagwan** [comment] 2021-10-05 20:34
This is not a bug, the issue is that when using the `change:reload` event fzf populates the entries on it’s own so fzf-lua wasn’t able to parse the lines and add the icons.

But now that you mention it, since then things have changed and the `live_grep_resume` version works differently and feeds the reloaded lines into fzf so I can probably solve that now, will keep this thread updated.

**Comment by ibhagwan** [comment] 2021-10-06 05:19
https://github.com/ibhagwan/fzf-lua/commit/a499bd78a4bf7426bedfbed0b1a5cc57a3ac2aa1

Worked hard on adding this properly, tried to improve performance as much as I could but there's still a non-negligible difference when running with or without this feature, this is due to the fact that I can no longer simply passthrough the data from `rg` directly to `fzf` but rather have to parse the data (find the extension, add the icon, etc, check against git change map, etc) which adds a significant load.

It's not very noticeable in small projects but when running on my home directory with millions of files you can clearly feel the difference so I decided to disable it by default.

To enable it, you have to either enable `experimental` under `grep` options during `setup`:
```lua
require'fzf-lua'.setup {
  grep = {
    experimental      = true,
  }
}
```

Or direcltly with each call:
```lua
:lua require'fzf-lua'.live_grep({ experimental = true })
```

I've enabled it for myself by default and unless I'm running nvim at `$HOME` it works great and the performance difference is barely noticeable but YMMV.

Let me know if this works well for you?

**Comment by LoydAndrew** [comment] 2021-10-06 06:42
Wow. That was really quick. I tried it on a project with 50 thousand files and it just hangs after first input. On a small project with one  thousand files it works just good enough.

**Comment by ibhagwan** [comment] 2021-10-06 06:44
> Wow. That was really quick. I tried it on a project with 50 thousand files and it just hangs after first input. On a small project with one thousand files it works just good enough.

Yes, it was hanging for me too but then after a couple of seconds it “releases” somehow, I still haven’t given up on this but for now it does seem to work fine on small-medium projects which are the majority I would assume.

**Comment by LoydAndrew** [comment] 2021-10-06 07:09
Sorry for annoyance. But I notice now that custom script ( I modified this script https://github.com/fanliver/vimrg for my needs) for rg command stops working. The last commit where it works is 510aca8658a954e152bd5e97cdad4fd6b09b7ea7 
I am using it like live_grep({cmd=vimrg}) or by using setup function .setup {grep = { cmd = "vimrg"} }

**Comment by ibhagwan** [comment] 2021-10-06 07:15
> Sorry for annoyance. But I notice now that custom script ( I modified this script https://github.com/fanliver/vimrg for my needs) for rg command stops working. The last commit where it works is [510aca8](https://github.com/ibhagwan/fzf-lua/commit/510aca8658a954e152bd5e97cdad4fd6b09b7ea7) I am using it like live_grep({cmd=vimrg}) or by using setup function .setup {grep = { cmd = "vimrg"} } I doesn't use vimrg as a custom command just default rg.

Probably because I restored the original `live_grep` function (after the icon and performance enhancements), try running `live_grep_native({cmd=vimrg})`, this should work as before as `live_grep` was mapped to the native version.

Now if you can post your modified script here I'll make sure it works in both `live_grep` and `live_grep_native`.

**Comment by LoydAndrew** [comment] 2021-10-06 07:38
Yes, it works with a live_grep_native. I just customize go script from https://github.com/fanliver/vimrg . You can do  `go build` and paste it to your HOME dir.

**Comment by ibhagwan** [comment] 2021-10-06 08:03
I just tried and both versions work, see below with and without filtering, you can see I'm running the non-native version as I have icons in my result set.

Without filtering:
![screenshot-1633507214](https://user-images.githubusercontent.com/59988195/136163466-6837b050-03d9-4431-a1b6-79aa2952e3bc.png)

Excluding all files with `*key*` - you can see all results from `which_key.lua` are excluded:
![screenshot-1633507195](https://user-images.githubusercontent.com/59988195/136163490-24ed4174-f14c-463f-ab14-079356cfe4f8.png)

**Comment by LoydAndrew** [comment] 2021-10-06 08:09
Yes, I can confirm that too now. It doesn't work only if  setup function has this line `{grep = { cmd = "vimrg"} }` and then you invoke `FzfLua live_grep `. But maybe this is how it should be.

**Comment by ibhagwan** [comment] 2021-10-06 08:31
> Yes, I can confirm that too now. It doesn't work only if setup function has this line `{grep = { cmd = "vimrg"} }` and then you invoke `FzfLua live_grep `. But maybe this is how it should be.

Just tried with `cmd = "vimrg"` in the setup and it works with both native and non-native, there should be no difference where you define you `cmd`, the one sent to the command at runtime takes precedence but there should be no reason why the one in setup wouldn't work.

**Comment by ibhagwan** [comment] 2021-10-06 08:40
In any event I just looked at the code of `vimrg` it's very simple, so while I cannot add that functionality to `live_grep_native` (as the query arguments are handled directly by fzf) I can easily add this to `live_grep` - just need to make sure it has enough customization so it doesn't conflict with other operations users might want to do (such as searching for the separator).

**Comment by ibhagwan** [comment] 2021-10-06 09:31
Closing this issue, will update in #167 as it makes more sense there.

**Closed by ibhagwan** 2021-10-06 09:31 UTC
Labels: enhancement, question
