### ISSUE TITLE
bat: permission denied error message

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#409] opened 2022-05-12 03:27 UTC
![Screen Shot 2022-05-11 at 20 19 55](https://user-images.githubusercontent.com/16427330/167985484-63d1a194-a25e-45b1-8a66-08e4e0709902.png)

triggering `lsp` functionality like `fzf.lsp_references` gets the results to show up in FZF, but preview says this ^. The file is is giving error is located at `/var/v4/...`. the owner of that folder v4 is my user, so I dont see why this should be a problem. Have only noticed this recently past the 0.7 release.

Also, the permission denied thing also comes on when using `files` or `lines` (anything using `bat` as previewer).  But interestingly, when using these other commands, the preview does work, just with the permission denied message at the top as overlay.

**Comment by ibhagwan** [comment] 2022-05-12 03:32
>Also, the permission denied thing also comes on when using files or lines (anything using bat as previewer). But interestingly, when using these other commands, the preview does work, just with the permission denied message at the top as overlay.

That is strange indeed, I'm yet to conclude if this is an issue with parsing the filename or your setup.

What happens if you run `bat <filename>` from the `lsp_references` output? does it work properly on the terminal? can you figure out if this fails for paths in the project's cwd or only for external referenes?

What happens if you try the `builtin` previewer?

Once we can hone in on the exact issue I'm sure the solution will be quick.

**Comment by ViRu-ThE-ViRuS** [comment] 2022-05-13 21:39
Great suggestions! Ill check those out and get back in a bit, finals week.

**Comment by ibhagwan** [comment] 2022-05-14 00:45
> Great suggestions! Ill check those out and get back in a bit, finals week.

Good luck in your finals! 🤞

**Comment by ViRu-ThE-ViRuS** [comment] 2022-05-14 00:52
the file is of type `socket` (using the `file` command). using bat on it from terminal gives me: ```[bat error]: '/var/folders/v4/.../T/.../1': Operation not supported on socket (os error 102)```

**Comment by ibhagwan** [comment] 2022-05-14 00:55
> the file is of type `socket` (using the `file` command). using bat on it from terminal gives me: `[bat error]: '/var/folders/v4/.../T/.../1': Operation not supported on socket (os error 102)`

I'm not sure what I can do in the case `bat` itself can't read the file, I would assume the builtin previewer would have similar issues reading the content of the file.

How do I get `lsp_references` to return results from `socket` files?

**Comment by ViRu-ThE-ViRuS** [comment] 2022-05-14 00:57
do you know what is creating these files? 
the full path is `/var/folders/v4/2cp1ct4d3f15n5y64_lln1z80000gn/T/nvim3zWj5M/1` and there are a bunch of these nvim folders in there inside `T`.

**Comment by ibhagwan** [comment] 2022-05-14 01:03
> do you know what is creating these files? the full path is `/var/folders/v4/2cp1ct4d3f15n5y64_lln1z80000gn/T/nvim3zWj5M/1` and there are a bunch of these nvim folders in there inside `T`.
> 
> Weird part is it works, output shows in the preview window, its just overlaid with the error.

These files seem to be generated by neovim's `vim.fn.tempname()` which returns an available name within the neovim temp directory (try it with `:lua print(vim.fn.tempname())`), unfortunately understanding what is generating these can be tricky as the function is called by myriad of plugins when a temp name is needed, `fzf-lua` uses these too for input/output pipes but calls `vim.fn.delete` when fzf exits.

Since these somehow contain LSP references I would assume it's a language/LSP related plugin generating these.

**Comment by monkoose** [comment] 2022-05-17 07:36
Have the same issue with bat previewer.

**Comment by monkoose** [comment] 2022-05-17 09:23
Placing 
```lua
  if filepath == '' and entry.uri then
    filepath = entry.uri:gsub("file://", "")
  end
```
below 
https://github.com/ibhagwan/fzf-lua/blob/d4c050e1017ddccd372cce1dec4146558dbb7c1e/lua/fzf-lua/previewer/fzf.lua#L170
fixed it for me.

**Comment by ibhagwan** [comment] 2022-05-17 14:08
Tysm @monkoose, this is really helpful, the use of URIs for LSP locations is by design so that references/definitions/etc jumps are registered in the tag stack which you can then use `<C- t>` to jump between locations similarly to how `vim.lsp…` calls behave, see #336.

I’ll take a deeper look why URIs cause this behavior, you can always disable that using:
```lua
:lua require'fzf-lua'.lsp_references({ force_uri = false })
```

Can you check of the above also solves your issue?

Btw, are you on Mac/Linux? What version of neovim are you using?

**Comment by monkoose** [comment] 2022-05-17 15:19
> `:lua require'fzf-lua'.lsp_references({ force_uri = false })`

Yes it works, but it looses mentioned by you `<C-t>` (personally i don't use it that often, but for someone it can be more convenient than `<C-o>`). With my code above `<C-t>` still works, because it only change previewer behavior.

I'm on Arch Linux and stable neovim 0.7.

**Comment by ibhagwan** [comment] 2022-05-17 15:20
@monkoose, this seems to be a bug I intrudoced in #408 while adding `path_shorten` support, bat previewer entry parsing should never return a URI style entry, fixed with https://github.com/ibhagwan/fzf-lua/commit/74831cf13841ebe6da49e3ff9d98095f124514be.

I'll leave this issue open until we can confirm this also solves the issue for @ViRu-ThE-ViRuS as I'm not 100% sure this is the same issue.

**Comment by monkoose** [comment] 2022-05-17 15:22
Can confirm, last commit fixed it for me.

**Comment by ibhagwan** [comment] 2022-05-17 15:23
Ty @monkoose! will away further feedback from @ViRu-ThE-ViRuS.

**Comment by ibhagwan** [comment] 2022-05-17 15:29
> And with that commit it actually fixed title of the built in previewer (previously it was full path uri) and now it just filename relative to cwd.

Yes, that's also part of the bug I introduced, I passed extra options to the entry parsing function as part of the `path_shorten` changes and that was passing `force_uri` to parsing of all LSP entries even when a URI wasn't needed (it's only needed in `actions` to facilitate the tag stack).

Ty for your diligence :-)

**Comment by ViRu-ThE-ViRuS** [comment] 2022-05-17 18:40
<img width="736" alt="Screen Shot 2022-05-17 at 11 37 16" src="https://user-images.githubusercontent.com/16427330/168886081-2d703d62-d1f5-4a4e-a5cc-f3de1e7aed1f.png">

regardless of the single line change (`lsp_references` with `force_uri` option set), the behavior is see is the same:

- the first few previews show the popup of permission denied as overlay, while showing correct results / working on <cr> etc
- going up the results from the same file, after the first few (usually 1-3 results), the error goes up on entries higher up. 


file changes depending on which file the preview is from, and as mentioned, is only there for first few results when going upwards (default layout, going up via `<c-p>`)

**Comment by ibhagwan** [comment] 2022-05-17 19:18
@ViRu-ThE-ViRuS it would help if you can further isolate the issue:

- Are you using `bat` or `bat_native`? What happens if you use the other?
- Does it also happen with `cat` or `head` previewer?
- Does this also happen with the `builtin` previewer?
- Is the temp file always the same or does the number change as you keep scrolling between results?
- What is the output if `:lua print(vim.g.fzf_lua_server)`?

**Comment by ibhagwan** [comment] 2022-05-17 19:23
@ViRu-ThE-ViRuS Also can you try with a different shell that isn't `fish` so we can rule it if this is yet another fish shell issue?

**Comment by ibhagwan** [comment] 2022-05-17 19:50
@ViRu-ThE-ViRuS Can you try the latest commit https://github.com/ibhagwan/fzf-lua/commit/f7ca80ab4eee105df3aa3f7a9eefdfc62307fda9?

I suspect this might be yet another similar issue to #340  (fish shell escaping).

**Comment by Shivix** [comment] 2022-05-17 19:54
I am getting the same issue, still happens to me after latest commit, also tried with bash and the issue persisted.

**Comment by ibhagwan** [comment] 2022-05-17 20:06
@Shivix can you try to answer some of the questions I posted above so we can further isolate the issue?

**Comment by Shivix** [comment] 2022-05-17 20:06
* Seems to happen with both `bat`, `bat_native`, `cat` and `head` but not `builtin`.
* The temp file changes every time I restart nvim, is the same when switching files and reopening the fzf window. (Not using global_resume)
* The output of `:lua print(vim.g.fzf_lua_server)` matches the temp file.

**Comment by Shivix** [comment] 2022-05-17 20:15
NVIM v0.8.0-dev+169-ge50b1fe60 on Linux

**Comment by ibhagwan** [comment] 2022-05-17 21:01
> NVIM v0.8.0-dev+169-ge50b1fe60 on Linux

Ty @Shivix, I was able to reproduce this with the nightly, this doesn't happen with `0.7`, I removed the last commit (https://github.com/ibhagwan/fzf-lua/commit/f7ca80ab4eee105df3aa3f7a9eefdfc62307fda9) as it seems to not have been required and might have unintended consequences.

I'll update this thread once I find out the reason.

**Comment by ibhagwan** [comment] 2022-05-18 03:17
https://github.com/ibhagwan/fzf-lua/commit/6cd1224581494077f6155ed81b22ceed0474c9ce - should work now.

Lmk if this works for you @ViRu-ThE-ViRuS, @Shivix?

**Closed** 2022-05-18 03:17 UTC
Labels: bug

**Comment by Shivix** [comment] 2022-05-18 07:35
Yep, all good for me now. Nice one!
