### ISSUE TITLE
Running startinsert on TermOpen in windows kills the fzf window

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#1088] opened 2024-03-16 14:00 UTC
This is a bit weird, i have and use the same config on both win, mac and linux, however on windows, having the following. (with nvim 0.9.4)

```lua
vim.api.nvim_create_autocmd({ "TermOpen" }, {
    pattern = "term://*",
    callback = vim.cmd.startinsert
})
```

causes the fzf window to just popup and then instantly close down, while on the other platforms it would simply work just fine. It could be a nvim issue after all. Problem above is i can not really mitigate it with `vim.bo.filetype` since TermOpen triggers earlier than FileType is set.

**Comment by ibhagwan** [comment] 2024-03-16 17:39
@asmodeus812, couldn't reproduce on my Windows with nightly, still might be a neovim issue that was fixed in recent versions?

In any event I suspect https://github.com/ibhagwan/fzf-lua/commit/e8b2093821553a9a338f5a6c570a687934dffe70 will solve it for you - try it out and lmk?

**Comment by asmodeus812** [comment] 2024-03-16 20:05
@ibhagwan seems like it did fix the issue on Windows, and no regressions on unix. 

Another question on the side, related to fzf's split cmd, that might be nvim itself, but when you press <esc> to close fzf, it "looks" like two windows are being closed. Hard to explain. When first pressing <esc> the fzf "win is closed / cleared", but for a split second, the actual split still stays there, as what seems / looks like a window showing an "empty" buffer, and maybe after a 100-200ms delay, it get's removed from the window layout and closed. That seems quite strange.

**Comment by ibhagwan** [comment] 2024-03-16 20:33
> @ibhagwan seems like it did fix the issue on Windows, and no regressions on unix.

That’s great.

> Another question on the side, related to fzf's split cmd, that might be nvim itself, but when you press to close fzf, it "looks" like two windows are being closed. Hard to explain. When first pressing the fzf "win is closed / cleared", but for a split second, the actual split still stays there, as what seems / looks like a window showing an "empty" buffer, and maybe after a 100-200ms delay, it get's removed from the window layout and closed. That seems quite strange.

I can’t say I understand what you mean, more so, I don’t really use splits, if you can take screencast of the issue I’ll be able to compare how this behaves on my end, this also might be related to the view restoration commands, you can try commenting out this section of the code and lmk if it makes any difference?

Maybe @TheBlob42 has some insights on this - have you experienced the described behavior?

https://github.com/ibhagwan/fzf-lua/blob/e8b2093821553a9a338f5a6c570a687934dffe70/lua/fzf-lua/win.lua#L952-L968

**Comment by ibhagwan** [comment] 2024-03-16 20:41
> when you press to close fzf, it "looks" like two windows are being closed

Perhaps I understand, if you're using the "builtin" previewer (not native) there are actually two windows, the fzf terminal window and the preview window which is **layered on top of it in the same dimensions the native previewer should be**,  that was the best way I came up with the reuse the previewer without having yet another split window.

Try the `bat` previewer, it has only one window, the fzf terminal window which renders the preview natively in the terminal, if you don't experience the behavior there that's probably it.

**Comment by ibhagwan** [comment] 2024-03-17 04:48
Closing the issue as the discussion is no longer relevant to the OP.

**Closed by ibhagwan** 2024-03-17 04:48 UTC
Labels: Windows
