### ISSUE TITLE
Deadlock and neovim hangs forever when fzf command fails

### ISSUE THREAD

**Issue by wookayin** [ibhagwan/fzf-lua#886] opened 2023-09-25 02:40 UTC
We often experience a deadlock, neovim **hanging forever** when something goes wrong. This is mostly when the raw `fzf` shell command fails immediately.

## How to reproduce

```lua
require("fzf-lua").fzf_exec({ }, { fzf_raw_args = "--wrong-arg" })
```

I know this is a tricky problem --- I now think this is actually a bug of neovim when coroutine and jobstart are used at the same time. But I open this thread to share what I have found so far and figure out solutions together.

## Where does a deadlock happen?

`fzf` does not recognize the invalid raw args, so [`jobstart()`](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/fzf.lua#L203) immediately fails and here's the cause of the deadlock. I'm still trying to figure out what's the root cause.

So here's what happens:

- `core.fzf()`:
  - Create a floating window (it was not drawn yet)
  - Call `fzf.raw_fzf()`:
	- `jobstart()` or `termopen()` fails due to the falsy shell command
	- `::wait_for_fzf::` runs `coroutine.yield()`
	- Now the thread does some other jobs (unknown), and blocks
  - `selected, exit_code <- fzf.raw_fzf() return value`

Stacktrace when neovim hangs:

<img width="683" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/1009873/fc68b01e-1a17-4f8d-a639-24b886f16d36">

## Additional Remarks

<details>
<summary>Some comments by @ibhagwan from fzf-lua/fzf.lua</summary>

```
I'm not sure why this happens (probably a neovim bug) but when pressing
<C-c> in quick successsion immediately after opening the window neovim
hangs the CPU at 100% at the last `coroutine.yield` before returning from
this function. At this point it seems that the fzf subprocess was started
and killed but `on_exit` is never called. In order to avoid calling `yield`
I tried checking the job/coroutine status in different ways:
  * coroutine.status(co): always returns 'running'
  * vim.fn.job_pid: always returns the corrent pid (even if it doesn't
    exist anymore)
  * vim.fn.jobwait({job_pid}, 0): always returns '-1' (even when looping
    with 'vim.defer_fn(fn, 100)')
  * uv.os_priority(job_pid): always returns '0'
`sudo strace -s 99 -ffp <pid> when neovim is stuck:
  [pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
  [pid 27432] <... write resumed>)        = 8
  [pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
  [pid 27432] epoll_wait(9,  <unfinished ...>
  [pid 27433] epoll_wait(15,  <unfinished ...>
  [pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] write(32, "\3", 1)          = 1
  [pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
  [pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
  [pid 27432] <... write resumed>)        = 8
  [pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
  [pid 27432] epoll_wait(9,  <unfinished ...>
  [pid 27433] epoll_wait(15,  <unfinished ...>
  [pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] epoll_wait(9, [], 1024, 0)  = 0
  [pid 27432] write(32, "\3", 1)          = 1
  [pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>

As a workaround we map buffer <C-c> to <Esc> for the fzf buffer
`vim.keymap.set` to avoid breaking compatibility with older neovim versions

Removed as an experiment since the removal of the `save_query` code
that was running on WinLeave which seems to make the `<C-c>` issue
better or even non-existent? RESTORED AGAIN
```

</details>

**Comment by ibhagwan** [comment] 2023-09-25 04:10
@wookayin, you’re mixing two different issues here, the one you’re describing from my comments relates to a neovim bug with terminating lua procedures, see https://github.com/neovim/neovim/issues/20726 for more info.

I might be mistake but I never had a hang due to wrong fzf args, what I did experience was specifying some complex arg value with **wrong shell escaping causing the shell to hang** - this rarely happens, only with advanced customization so the user usually knows which command causes the hang and where they went wrong.

If my analysis is accurate this would be a low priority issue.

**Comment by wookayin** [comment] 2023-09-25 04:14
Your comment and neovim/neovim#20726 are tangential to this but I think it's relevant, possibly the same reason.

Anyway the reproduction is just an easy way to reproduce the bug and I've seen many cases where the neovim randomly hangs on **a normal use** without advanced customization, just using the built-in providers. I think fzf mat still crash often, actually it happens almost **everyday** for me, and I was just trying to find the root cause which seems to be a deadlock.

**Comment by ibhagwan** [comment] 2023-09-25 04:35
> But NO for "a low priority issue" -- anyway the reproduction here is just an easy way to reproduce the bug and I've seen many cases where the neovim randomly hangs on a normal use without advanced customization, just using the built-in providers. I think fzf may still crash often, even after it's launched, actually it happens almost everyday for me, and I was just trying to find the root cause which seems to be a deadlock.

Everyday hangs aren’t low priority at all but you described in the OP are hangs **only when using wrong args** which are obviously very easy to avoid.

If you’re having everyday hangs that’s a new **very high priority** issue.

Are you closing the interface with ctrl-c when that happens or is it totally random?

**Comment by ibhagwan** [comment] 2023-09-25 04:41
Also, what is your shell/fzf version/environment?

There are at thousands of users for this plugin; this is the first I’m hearing of random hangs (unrelated to ctrl-c), if that were the case it would’ve been reported by now, if such an issue was more prominent it would be a serious UX issue and nobody would have used this plugin.

Is it possible this is related to your customization (nested coroutines for ui.input or other creative ideas)?

**Comment by ibhagwan** [comment] 2023-09-25 10:26
@wookayin, so I did some testing and to my surprise the below hangs 100% of the time:
```lua
require("fzf-lua").fzf_exec({ }, { fzf_raw_args = "--wrong-arg" })
```

I tested this many times in the past and it didn't used to hang like this and would provide a proper error message, I just tested with with [skim](https://github.com/lotabout/skim) and it works as expected:
```lua
:lua require("fzf-lua").fzf_exec({ }, { fzf_raw_args = "--wrong-arg", fzf_bin="sk" })
```
Which fails properly with:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/89132822-2142-415e-b5d6-527304204465)

I suspect this has something to do with fzf's version as this worked perfectly fine in the past, I'll do some more testing.

**Comment by ibhagwan** [comment] 2023-09-25 10:44
Ok, some progress, first this only happens when the `contents` argument  is of type `table` (which isn't used as much in the code, most contents arguments are strings), for example, the below won't fail:
```lua
:lua require("fzf-lua").fzf_exec("ls", { fzf_raw_args = "--wrong-arg" })
```

As I mentioned a few times in the past in our discussions, you would never know how a seemingly small change would potentially come to bite you in the future, here's the commit that broke it https://github.com/ibhagwan/fzf-lua/commit/a294a8330e9b0622acc3de4e0b9ab4e853b53fa2 which was part of #633.

**Closed** 2023-09-25 11:04 UTC

**Comment by ibhagwan** [comment] 2023-09-25 11:06
https://github.com/ibhagwan/fzf-lua/commit/501d7524eae7e881f1406615f1a44cd43b52cf49

@wookayin, the above commit fixes it for everything but `fish` shells, I'm still unclear why this happens or the reasoning behind #633 which required this change, in any event unless you're using `fish` it shouldn't hang any longer when providing wrong args.

**Comment by wookayin** [comment] 2023-09-25 19:52
Awesome @ibhagwan, congratulations and kudos you figured it out. Thanks so much again for your time and help on this.

> Also, what is your shell/fzf version/environment?
> Is it possible this is related to your customization (nested coroutines for ui.input or other creative ideas)?

I am using zsh and fzf 0.39.0 (2023040), on macOS. Glad to hear that you already managed to reproduce, and it's not only me hit by this strange bug.

It's quite hard to reproduce the bug consistently -- and this issue #886 was my best effort to abstract the bug and narrow down the suspected reason as much as possible. But I remember I was just using built-in commands (like GitFiles, Grep) with some reasonable options (see [my config](https://github.com/wookayin/dotfiles/blob/fzf/nvim/lua/config/fzf.lua#L128-L138) just FYI). Probably some of them were related to `<C-c>` but I wasn't 100% sure. If I could manage to reproduce it again, I will take a deeper look next time.

> first this only happens when the contents argument is of type table 

This sounds strange! So I guess it might have something to do with "empty" stdin? (the piped file doesn't write anything) I still don't get why this works and the logic like a294a83 (#633) makes the bug... what a mystery. So it's probably more like a "blocking" file I/O deadlock issue rather than a coroutine..?

I can see that 501d752 fixes the problem, working well in both of my fish and zsh environments.

**Comment by ibhagwan** [comment] 2023-09-25 19:58
Ty for the update @wookayin!

> working well in both of my fish and zsh environments.

The workaround was only applies to non fish shells, I tried to reproduce and fish was still causing the issue, I’m confused how it’s working for you on fish shell as the old code logic remained.

**Comment by ibhagwan** [comment] 2024-03-23 19:04
@wookayin, in regards to https://github.com/neovim/neovim/issues/20726, take a look at #1091, I'm attempting to solve this with a workaround, if you're still interested in using `<C-c>` and experience the occasional hang, can you try the [trace branch](https://github.com/ibhagwan/fzf-lua/tree/trace) , add the below to your setup:
```lua
require("fzf-lua").setup({
  -- 0: silent mode, no messages will be displayed
  -- 1: display the message only if process kill workaround is applied
  -- 2|true, display all `ctrl-c` keypresses (on normal fzf-lua UI close)
  -- I'm using `1` for testing so I can see the message only if proccess was required to be killed
  nvim_freeze_workaround = 1,
})
```

And monitor `:messages` for something like this:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/1e905299-dd3f-44af-8fca-031bc826d465)
