### ISSUE TITLE
help_tags & man_pages don't work.

### ISSUE THREAD

**Issue by ahmedelgabri** [ibhagwan/fzf-lua#175] opened 2021-10-09 14:14 UTC
1. `help_tags` resizes the window in a weird way & when selecting a result nothing happens
2. `man_pages` shows no results at all, which an odd "Echo" man page at the bottom

https://user-images.githubusercontent.com/63876/136661466-41dc4498-834d-4903-b87c-b4e840bf61ed.mp4

```lua
    use {
      'https://github.com/ibhagwan/fzf-lua',
      config = function()
        require('fzf-lua').setup {
          keymap = {
            builtin = {
              ['?'] = 'toggle-preview',
            },
          },
          files = {
            prompt = ' ',
            cmd = vim.env.FZF_DEFAULT_COMMAND,
          },
        }
        local map = require '_.utils.map'
        map.nnoremap(
          '<leader><leader>',
          [[<cmd>lua require 'fzf-lua'.files()<cr>]],
          { silent = true }
        )
        map.nnoremap(
          '<leader>b',
          [[<cmd>lua require 'fzf-lua'.buffers()<cr>]],
          { silent = true }
        )
        map.nnoremap(
          '<leader>h',
          [[<cmd>lua require 'fzf-lua'.help_tags()<cr>]],
          { silent = true }
        )
      end,
      requires = {
        'https://github.com/vijaymarupudi/nvim-fzf',
      },
    }
```

**Comment by ahmedelgabri** [comment] 2021-10-09 19:00
> Did it ever work for you or could this be related to recent changes?

I honestly don't know, I don't use these commands this much. I think this was the first time to use `help_tags` & then I tried `man_pages` & both gave me these results.

> Does this happen consistently? What happens if you try it right when you start neovim?

It's consistent, no matter how I call them they both gave the same results as the video posted above.

**Comment by ibhagwan** [comment] 2021-10-09 19:39
In your video I see the "minimized help window" opens in a split top right for you, probably something related to your neovim split preferences, still shoulnd't cause an issue.

Can you try the below variants? if one of them works we can just add it to the setup permanently:
```lua
-- Try with different split options: 'topleft', 'aboveleft', 'belowright', 'botright'
:lua require'fzf-lua'.help_tags({ previewer = { split = "belowright" } })
:lua require'fzf-lua'.man_pages({ previewer = { split = "topleft" } })

-- If you can find one that's working add it to the setup function:
require'fzf-lua'.setup({
  helptags = { previewer = { split = "topleft" } },
})
```

If none work can you try with this [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua)? This will help identify if this comes from configuration options, if we can find which option causes this behavior I can work around it.

**Comment by wimstefan** [comment] 2021-10-11 12:52
That was an easy one :)
The [culprit is here](https://github.com/wimstefan/dotfiles/blob/0d3d4af4c62941b8a4088aaaf32116d64e0357d1/config/nvim/init.lua#L182-L188) ...
I'd rather like to keep that option though since I prefer to open help- and manpages in a right vertical column.

**Comment by ibhagwan** [comment] 2021-10-11 12:54
> That was an easy one :) The [culprit is here](https://github.com/wimstefan/dotfiles/blob/0d3d4af4c62941b8a4088aaaf32116d64e0357d1/config/nvim/init.lua#L182-L188) ... I'd rather like to keep that option though since I prefer to open help- and manpages in a right vertical column.

Alright, my guess was close enough :-)

Already started writing the solution by adding `noautocmd` where appropriate, will commit soon and update this thread so you can try.

**Comment by ibhagwan** [comment] 2021-10-11 13:26
https://github.com/ibhagwan/fzf-lua/commit/4b9b719491ae70f3d17a54ee062573fefc296002 - this should solve it at least for `help_tags`, works well with the `autocmd` from @wimstefan, let me know if this solves it for you too @wimstefan  @ahmedelgabri ?

Man pages still giving me trouble as it fails to load properly with `noautocmd`, I will work on that tomorrow.

**Comment by wimstefan** [comment] 2021-10-11 13:30
After a very quick check I can confirm that it works so far - even with man pages 😁
Thanks a lot @ibhagwan for that quick and solid solution! 🙏

**Comment by ibhagwan** [comment] 2021-10-11 18:20
https://github.com/ibhagwan/fzf-lua/commit/3d1b8d0c068f0c1b159e73109774450d7905a105

This modified the `man_pages` provider to not require the single line `Man` window but instead get the preview directly from the shell `man` command.

@ahmedelgabri @wimstefan - let me know if this works fine and I can close this issue?

**Comment by ibhagwan** [comment] 2021-10-12 16:03
> `man -c … | col -b` doesn't work
> 
> `man … | col -b` works

I see, I missed that.

> also I tried `man -k .` & that also doesn't work.

That is why your man window is empty.

> I'm curious which version of `man` you have then? mine is `2.9.4` maybe they have some differences

`man —version` or `man -v` returns an error, looking at my distribution packages it seems I have `man-pages_5.12`?

**Comment by ahmedelgabri** [comment] 2021-10-12 19:59
I think this might be an issue I have locally, you can close this issue for now I think. I will check why `man -k .` or `apropos .` are not working because they should work.

**Closed** 2021-10-12 20:00 UTC
Labels: bug

**Comment by gennaro-tedesco** [comment] 2024-12-30 11:48
@ahmedelgabri Have you perhaps found a solution to `man -k .` not showing? I somehow see the same on my system and haven't been able to figure out why.

**Comment by ahmedelgabri** [comment] 2024-12-30 23:06
@gennaro-tedesco no, I didn't find a solution for this.

**Comment by phanen** [comment] 2025-01-09 14:11
@gennaro-tedesco @ahmedelgabri Meet the same problem today due to mistakenly replace my `man-db` with `mandoc` package on my system.

If you use arch-based system, man index is generated by systemd timer (https://wiki.archlinux.org/title/Man_page#Searching_manuals):
* man-db
```systemd
ExecStart=+/usr/bin/install -d -o root -g root -m 0755 /var/cache/man
# Regenerate man database.
ExecStart=/usr/bin/mandb --quiet
```
* mandoc
```systemd
ExecStart=/usr/bin/makewhatis
```

If available maybe you can run `mandb`/`makewhatis` as root user.
