### ISSUE TITLE
feature request: is it available to support windows?

### ISSUE THREAD

**Issue by linrongbin16** [ibhagwan/fzf-lua#709] opened 2023-03-31 23:06 UTC
Hi, is it available to support windows?

**Comment by ibhagwan** [comment] 2023-03-31 23:13
Probably not by me, duplicate of #585, #613

**Closed by ibhagwan** 2023-03-31 23:14 UTC

**Comment by ibhagwan** [comment] 2024-02-13 15:58
Windows is now supported follow #1038 and the [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows) for more info.
