### ISSUE TITLE
jdt file preview buffer doesn't close 

### ISSUE THREAD

**Issue by y1rn** [ibhagwan/fzf-lua#609] opened 2023-01-14 13:19 UTC
### Info

- Operating System: archlinux
- Shell: zsh
- Terminal: windows terminal
- `nvim --version`: NVIM v0.8.2
- `fzf --version`: 0.35

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup {
  fzf_opts = {
    ['--no-separator'] = '',
  },
  winopts = {
    preview = {
      delay = 10,
    },
  },
  keymap = {
    fzf = {
      ["ctrl-z"] = "abort",
      ["ctrl-u"] = "unix-line-discard",
      ["ctrl-a"] = "beginning-of-line",
      ["ctrl-e"] = "end-of-line",
      ["alt-a"]  = "toggle-all",
    },
  },
}

```
</details>

### Description 
jdt file preview buffer doesn't close  after exit fzf search.

**Comment by ibhagwan** [comment] 2023-01-14 16:08
By `jdt` you mean Java LSP server previews?

**Comment by ibhagwan** [comment] 2023-01-14 19:33
Are you using `jdtls` directly with `nvim-lspconfig` or with `nvim-jdtls`?

I just installed [`nvim-jdtls`](https://github.com/mfussenegger/nvim-jdtls) and tested it with a java project, seems to be working fine, can you share more info where this is failing you or better yet a smaple project that I can clone and reproduce the same error?
![image](https://user-images.githubusercontent.com/59988195/212492828-a4766613-537c-40c5-82b7-42b0004a592f.png)

**Comment by y1rn** [comment] 2023-01-14 20:23
I m using nvim-jdtls. detail step is:
1. open lsp_references on method called by some jar file. 
2. selected preview jdt file(not press enter).
3. exit fzf.
then I can see jdt buffer not close. And other java file in reference list can be close normally .

**Comment by y1rn** [comment] 2023-01-14 20:26
![image](https://user-images.githubusercontent.com/70128797/212495221-f72ae73f-481d-4498-a420-18f303e9013f.png)

**Comment by ibhagwan** [comment] 2023-01-15 00:27
Ty for reporting @y1rn, should be fixed now.

**Closed** 2023-01-15 00:27 UTC

**Comment by asmodeus812** [comment] 2023-02-11 08:04
@ibhagwan Hi, i was just trying out fzf lua, straight up without any customization, but i notice the same issue, when i do execute any lsp_references action (all buffers are attaching, even those i have not yet visited / scrolled to / selected) and i do :buffers! i can see a ton of buffers still lingering around, the jdtls server also starts to attach to all of them (when you do :LspInfo i can see that the server is attached to all results from lsp_references) . Here is a sample project i was testing on.
![image](https://user-images.githubusercontent.com/15955811/218247498-60593837-8f40-4c9e-8b70-c5761a7edef6.png)
![image](https://user-images.githubusercontent.com/15955811/218247479-4befa99e-de5e-44c9-8868-ce4ba63cd363.png)

The buffers remain even after you close the picker, the buffers i have not even visited, just opened references, and all got attached immediately. Not sure if this is isolated to only lsp_references or other lsp_{actions} could also be like that !

**Comment by ibhagwan** [comment] 2023-02-11 08:10
I noticed the same behavior when testing `jdtls`, unfortunately that’s how it works, you’d get the same result if you use `vim.lsp.buf.references`, not much I can do about it.

**Comment by ibhagwan** [comment] 2023-02-11 08:21
> Seems to also be reproduciable with a simple rust project too. Where all buffers with references are getting pre loaded even before the picker is shown when you call lsp_refs

That’s how the LSP server works, `rust_analyzer` analyzes your project up to the project root, open files or otherwise you’re going to get all refs/defs/symbols, etc, personally I use [fidget.nvim](https://github.com/j-hui/fidget.nvim) so I can see what the LSP server is analyzing and when the workspace is ready, with `rust_analyzer` you even get refs/defa from imported crates, I actually like it.

In any even this has nothing to do with fzf-lua and everything to do with your LSP configuration.

**Comment by asmodeus812** [comment] 2023-02-11 11:17
@ibhagwan i did just had a look at that, even with the native lsp call to references when you call it, buffers are still being attached. Was not aware of that. 

What about preventing the start_or_attach from jdtls from triggering when inspecting any of the files picker (oldfiles, etc) ? At the moment when the default previewer shows the content of the buffer (if i move up/down in java files) the start or attach (which is an auto cmd that triggers, for java files to start the server also goes off). Strangely enough, this is working fine in telescope when moving and previewing files.

**Comment by ibhagwan** [comment] 2023-02-11 13:45
> What about preventing the start_or_attach from jdtls from triggering when inspecting any of the files picker (oldfiles, etc) ?

Unless it’s something super straight forward I’d like to avoid even more single use case exceptions for `jdtls`, it’s a pain to maintain and have to install all the Java stuff as is just to understand what users are talking about.

> Strangely enough, this is working fine in telescope when moving and previewing files.

Back when I tested it Telescope wasn’t previewing nvim-jdtls files prefixed with `jdt://`, although this might have changed, does Telescope show proper preview of these special files? Previewing them requires following them with `lsp.jump_to_location` which I assume instructs jdtls to create the buffers.

**Comment by ibhagwan** [comment] 2023-02-11 13:49
> Strangely enough, this is working fine in telescope when moving and previewing files.

If you don’t just mean the `jdt://` files perhaps there is a way to prevent the LSP from being attached to the preview buffer that I overlooked, @abenz recently asked something similar in #626, if that’s the case perhaps we can reopen the issue and explore this again.

**Comment by asmodeus812** [comment] 2023-02-11 14:29
@ibhagwan  yes indeed i mean regular non URI based files which are on the file system.

**Comment by ibhagwan** [comment] 2023-02-11 14:31
> @ibhagwan yes indeed i mean regular non URI based files which are on the file system.

Then lets continue this discussion in #626 as it makes more sense there, I’ve reopened the issue.
