### ISSUE TITLE
Builtin previewer stops after pressing ctrl-g in live_grep

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#604] opened 2023-01-09 17:52 UTC
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: `NVIM v0.9.0-dev-624+gf7ad46e69`
- `fzf --version`: `0.35.1 (brew)`

- [x] The issue is reproducible with `mini.sh`

### Description 

When running live_grep, the previewer stops working after pressing `ctrl-g`. To reproduce with `mini.sh`:

1. run `mini.sh` to start nvim
2. invoke `:FzfLua live_grep`
3. search for something
4. press `ctrl-g`
5. preview is gone

Recording:

https://user-images.githubusercontent.com/108725/211374478-2a0338b7-a21d-46cb-a9b3-b79ef05c23f7.mp4

**Comment by ibhagwan** [comment] 2023-01-09 18:10
Ty @fsouza, this seems to be the cause https://github.com/ibhagwan/fzf-lua/commit/2ef7fe0d00234e1744010d9c1afe1c4492a242af, will be fixed shortly.

**Comment by ibhagwan** [comment] 2023-01-09 18:54
https://github.com/ibhagwan/fzf-lua/commit/e337b533c32fbc2533309bb94ee146b98da271fe - should work now.

**Closed** 2023-01-09 18:54 UTC
Labels: bug

**Comment by fsouza** [comment] 2023-01-09 20:44
Thank you for the quick fix!
