### ISSUE TITLE
Issue with live workspace symbols and `typescript-tools.nvim`

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1096] opened 2024-03-22 07:06 UTC
Sorry, it's me again:) It works one or two weeks ago, and it works in another project.

https://github.com/ibhagwan/fzf-lua/assets/53742299/c4410ed1-d87f-4a4f-b303-028a17ccdb21

**Comment by ibhagwan** [comment] 2024-03-22 09:04
Wow @kaiphat, you can bring on some hard stuff :)

Im suspecting this commit https://github.com/ibhagwan/fzf-lua/commit/5104ac1744b92f888ef9f1d4bb6ff14e700c7a37 due to #1089.

- Are you using nightly neovim? If so, can you try and update to the latest nightly and also lmk if this works with 0.9.5?
- What language servers are you using when it works and it doesn’t? In the screen capture, is this plain `tsserver` from Mason or `typescript-tools.nvim`?

**Comment by ibhagwan** [comment] 2024-03-22 09:18
Also what happens if you run:
`:FzfLua lsp_live_workspace_symbols query=init`?

**Comment by kaiphat** [comment] 2024-03-22 09:31
> Also what happens if you run: `:FzfLua lsp_live_workspace_symbols query=init`?

Yes, it works

**Comment by ibhagwan** [comment] 2024-03-22 09:32
I’m starting to suspect this is an issue with `typescript-tools.nvim` unable to accept an empty query for symbols, I’m suspecting the above will work as well as this:
```
:FzfLua lsp_live_workspace_symbols exec_empty_query=false
```

**Comment by kaiphat** [comment] 2024-03-22 09:33
I use `typescript-tools.nvim` and `NVIM v0.9.5`.
I'll try to checkout to another commit later if it needs.

**Comment by ibhagwan** [comment] 2024-03-22 09:34
> I use `typescript-tools.nvim` and `NVIM v0.9.5`. I'll try to checkout to another commit later if it needs.

No need, this looks like a typescript-tools bug, it proxies all LSP requests, you might as well bisect typescript tools to find out when empty symbols queries started returning nil.

**Comment by kaiphat** [comment] 2024-03-22 09:34
> :FzfLua lsp_live_workspace_symbols exec_empty_query=false

Also works good

**Comment by ibhagwan** [comment] 2024-03-22 09:38
> > :FzfLua lsp_live_workspace_symbols exec_empty_query=false
> 
> Also works good

Everything also works as expected with plain `tsserver`, this is a typescript tools issue which should be opened upstream, most likely this is also easily reproducible with a few lines of code by calling `workspace/symbol` with an empty query.

**Comment by kaiphat** [comment] 2024-03-22 10:26
Nvim freezed:)
A lot of (>1000 lines)
<img width="691" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/53742299/5d685cb0-1a79-4767-9116-de0d57d8f4e2">

**Comment by ibhagwan** [comment] 2024-03-22 14:51
> Nvim freezed:)
> A lot of (>1000 lines)

You replied in the wrong thread, this belongs to #1091 :)

Going to close this issue as there’s not much else I can do here, at least you have a workaround by setting `exec_empty_query=false`.

**Closed by ibhagwan** 2024-03-22 14:51 UTC
Labels: upstream
