### ISSUE TITLE
Search buffer by name does not work

### ISSUE THREAD

**Issue by damanis** [ibhagwan/fzf-lua#1086] opened 2024-03-13 06:24 UTC
Reproduce:
- Open several files in neovim (with or without GUI, such as neovim-qt)
- Run `lua require("fzf-lua").buffers()` — `Buffers` window shown properly
- Start enter some buffer name — `Buffers` window is empty

Environment:
- nvim version:
NVIM v0.10.0-dev-2581+gd5488633f
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
Run "nvim -V1 -v" for more info
- fzf-lua version: 9a414ab6c
- Buffers section in config file:
```
    buffers = {
      prompt = 'Buffers❯ ',
      file_icons = true,
      color_icons = true,
      sort_lastused = false,
      winopts = { preview = { vertical = 'up:70%' } },
    },
```

**Comment by ibhagwan** [comment] 2024-03-13 06:43
What is your fzf version?

Does this work `:FzfLua buffers _fzf_nth_devicons=false`?

I’m pretty sure the new `--nth` addition from #1080 is the cause I’m just not sure why it doesn’t work for you.

**Comment by ibhagwan** [comment] 2024-03-13 06:48
Also,  what about  `files`? Does it work as expected? Can you try searching for a file name that starts with some characters with `^…` - does that work?

How about `git_status`/`oldfiles`?

Is there any chance you have a special mapping for buffers that hides the `[bufnr]` using `--nth`?

**Comment by ibhagwan** [comment] 2024-03-13 06:55
Another possible cause is that you modified fzf-lua’s `nbsp` in setup?

**Comment by ibhagwan** [comment] 2024-03-13 07:09
@damanis, use https://github.com/ibhagwan/fzf-lua/commit/ff21680ddfd2ba434ea7061b9042f7e18966597d

It disables the buffer icon exclusion as I’m not sure it makes sense in case someone wants to search by bufnr, should solve your issue.

Let me know if other files pickers work as expected?

**Comment by damanis** [comment] 2024-03-13 07:12
> What is your fzf version?
> 
> Does this work `:FzfLua buffers _fzf_nth_devicons=false`?
> 
> I’m pretty sure the new `--nth` addition from #1080 is the cause I’m just not sure why it doesn’t work for you.

fzf version: 0.46.1 (3c0a630)
Provided command — same behavior.

**Comment by damanis** [comment] 2024-03-13 07:13
> Another possible cause is that you modified fzf-lua’s `nbsp` in setup?

`nbsp` isn't touched in my config.

**Comment by damanis** [comment] 2024-03-13 07:18
> Also, what about `files`? Does it work as expected? Can you try searching for a file name that starts with some characters with `^…` - does that work?
I created file `^qweqwe`. It shown in `Files`, but if try search `^q`, it isn't found.

**Comment by ibhagwan** [comment] 2024-03-13 15:46
> In this version search in Buffers works.
> In Files and LiveGrep I don't see problems.

> I created file ^qweqwe. It shown in Files, but if try search ^q, it isn't found.

Do you wish to debug this further?

**Comment by damanis** [comment] 2024-03-13 15:50
If you want.
I don't use `^` in file names and in `Files` and `Buffer` commands (fuzzy is prefer).

**Comment by ibhagwan** [comment] 2024-03-13 16:00
Let’s see why the field’s don’t match in your setup, can you run the below and try to change the `nth` arg to different numbers (1-5) and let me know / post the results?

```lua
local fzf = require("fzf-lua")
fzf.setup({
  files = {
    fzf_opts = {
      ["--delimiter"] = string.format("[:%s]", fzf.utils.nbsp),
      ["--wirh-nth"] = "-1..",
   }
  },
})
```

What the above does is split the string using fzf-lua’s nbsp, the `with-nth` flag is telling fzf to display only the fields marching the spec, so `-1..` displays only from the last field, `2..` displays the 2nd field onwards, what I’m looking for is which number displays only the file names for you without icons (technically that number set as `nth` would enable searching for `^`).

**Comment by damanis** [comment] 2024-03-13 17:13
Let's clarify what to check: files with `^` in name or regex search in `Files` with `^`?

**Comment by ibhagwan** [comment] 2024-03-13 17:18
> Let's clarify what to check: files with ^ in name or regex search in Files with ^?

You don't need to check anything, with `--with-nth` the non matching fields with disappear (to spec) , for example, in my setup running, so running `:lua require("fzf-lua").files({fzf_opts={["--with-nth"]="-1.."}})` removes all the icons:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/09f06589-0b52-4708-b027-923f48d33f32)


`--nth` tells fzf on what fields to fuzzy match, `--with-nth` tells fzf what fields to display, I asked to test with `--with-nth` so we can find out why your delimiter/nbsp combo fails to split the string by the right fields.

**Comment by ibhagwan** [comment] 2024-03-13 17:19
Btw, you don't even need to run `setup`, copy paste the same command I used above and run in in the cmdline with different args:
```lua
:lua require("fzf-lua").files({fzf_opts={["--with-nth"]="-1.."}})
:lua require("fzf-lua").files({fzf_opts={["--with-nth"]="2.."}})
:lua require("fzf-lua").files({fzf_opts={["--with-nth"]="3.."}})
```

**Comment by damanis** [comment] 2024-03-13 17:38
I put your config instead of mine.
`-1` and `2` looks same as on your screenshot. With `3` files name are not seen.

With my config `Files` command without options looks like `-1` and `2`.
```
    files = {
      cmd = 'fd .',
      fd_opts           = "--color=never --type f --hidden --follow --exclude .git --exclude CVS --strip-cwd-prefix",
      file_icons        = false,         -- show file icons?
      git_icons        = false,         -- show file icons?
    },
```

**Comment by ibhagwan** [comment] 2024-03-13 17:44
> I put your config instead of mine.
> -1 and 2 look same as on your screenshot. With 3 files name are not seen.

That's how it should be, that means it's working as expected, the string is split by the invisible `nbsp` right before the filename and therefore searching for `^file` should work, so now I'm confused even more about this:

> I created file ^qweqwe. It shown in Files, but if try search ^q, it isn't found.

Did you create the file with `^` at the start? If so that would be our "problem". `^foo` in fzf is similar to regex, it means search for a file that start with `foo`, you didn't need to create a new file, just search for a file that starts with something, for example if I want to search for all paths starting with `lua\` I would search for `^lua`:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/162f047d-e2a3-4205-93b5-f4b650faf5bc)


Given our testing I'm assuming this works and we can close this issue, sorry for the confusion :-)

**Comment by damanis** [comment] 2024-03-13 18:15
No problem. Fine plugins, I'm happy to help.
> Did you create the file with ^ at the start?
Yes, I tried.
Just regex with `^` works properly.

**Comment by ibhagwan** [comment] 2024-03-13 18:23
> No problem. Fine plugin, I'm happy to help.
> 
> > Did you create the file with ^ at the start?
> 
> Yes, I tried. Just regex with `^` works properly.

Perfect, we can close this then.

Ty for the help!

**Closed by ibhagwan** 2024-03-13 18:23 UTC
