### ISSUE TITLE
Neovim got frozen after holding `<C-J>` to scroll down the results of `live_grep()`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#211] opened 2021-11-09 13:34 UTC
Say there are 4000+ results after I typed some keywords. The CPU usage will go to 99.7%, which makes nvim frozen. To reproduce this bug holding `<C-J>` till the cursor reach the last result.

Edit: This also happened with 200+ results.

**Comment by ibhagwan** [comment] 2021-11-09 16:12
I’ll test this, it shouldn’t happen there is a 100ms delay between releasing the key to showing the preview exactly to prevent this scenario (same as fzf itself does).

What previewer are you using? `bat` or the neovim win one?
Does this also happen with `live_grep_native`?

**Comment by ibhagwan** [comment] 2021-11-09 17:19
Can you also try this script in the shell? this is almost exactly what `live_grep_native` does, if this gets stuck do we'll have to solve it at the fzf level:

```sh
#!/bin/sh
QUERY="$1"
RG_CMD="rg --hidden --column --line-number --no-heading --color=always --smart-case -g '!{.git,node_modules}/*' -- "
FZF_BINDS="f2:toggle-preview,f3:toggle-preview-wrap,f4:abort,f5:execute($EDITOR {1}),shift-down:preview-page-down,shift-up:preview-page-up,ctrl-u:unix-line-discard,ctrl-f:half-page-down,ctrl-b:half-page-up,ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all"
CMD="false "
if [ "$#" -gt 0 ]; then
    QUERY=$(echo $QUERY | sed 's/[\\~$?*|\\[()]/\\&/g')
    CMD="$RG_CMD '$QUERY'"
fi
eval ${CMD} | fzf --border --ansi --layout=reverse --info=inline --multi --height='80%' --delimiter='[: ]' --phony --query="$QUERY" --bind="$FZF_BINDS,change:reload:$RG_CMD {q} || true" --prompt='Rg❯ ' --preview-window='border:nohidden:nowrap:down:45%:+{2}-/2' --preview='bat --style=numbers,changes --color always --highlight-line={2} -- {1}' 
```

**Comment by nyngwang** [comment] 2021-11-10 00:59
> I’ll test this, it shouldn’t happen there is a 100ms delay between releasing the key to showing the preview exactly to prevent this scenario (same as fzf itself does).
> 
> What previewer are you using? `bat` or the neovim win one? Does this also happen with `live_grep_native`?

I first tested with `bat`, then I downgraded to `cat` and `head`. All cases have this problem. Let me test `live_grep_native` now.

**Comment by nyngwang** [comment] 2021-11-10 01:03
I think this is an appropriate moment to use GIF. Let me upload the situation:

**Comment by ibhagwan** [comment] 2021-11-10 20:23
Since we had many messages in different threads let’s do a summary here so I can focus on the exact issue:

- Is this unique to `live_grep`? Can you preview with no problems with `files()`? What about holding `<C-j>` with `files`?
- Is this issue still there without preview enabled (you can close the preview with `<F4>`, or set `winopts.preview.hidden = 'hidden'`)
- Does this happen `live_grep_native` or `:FzfLua grep search=’'`
- Does the shell script [posted above](https://github.com/ibhagwan/fzf-lua/issues/211#issuecomment-964363962)  work with no issues from the shell (this is almost exactly what `live_grep_native` runs)?
- What is your fzf version?

**Comment by nyngwang** [comment] 2021-11-11 04:28
> Does the shell script posted above ...

Regarding this, since I'm not very good at shell script, so I might need your help on what specific steps I need to do to enable the script/function?

I will answer the other answers maybe last week, I have too many tasks to do recently.

**Comment by ibhagwan** [comment] 2021-11-11 07:08
> Regarding this, since I'm not very good at shell script, so I might need your help on what specific steps I need to do to enable the script/function?

- Save those lines into a file, let’s call it `live_grep.sh`
- Make that file executable `chmod a+x live_grep.sh`
- Execute `./live_grep.sh`

If done correctly you’ll have live grep of text with `bat` preview inside the shell (without neovim).

**Comment by kutsan** [comment] 2021-11-11 15:27
I'm having exactly the same problem. Tried the script above and it doesn't have a problem for me, it works without lag or CPU freeze.

**Comment by ibhagwan** [comment] 2021-11-11 16:21
> I'm having exactly the same problem. Tried the script above and it doesn't have a problem for me, it works without lag or CPU freeze.

Ty @kutsan for letting me know, can you also respond to my questions [in this comment](https://github.com/ibhagwan/fzf-lua/issues/211#issuecomment-965716949) so we can try to hone in the issue?

Btw, if the script worked well for you I assume `live_grep_native` works for you?

**Comment by BenWeber42** [comment] 2021-11-12 17:49
I believe I have the same issue where the nvim gui freezes in a large repository . In my cases the repository is 5.3G with 15k files.

The issue occurs with `:lua require('fzf-lua').grep({ search = '' })<CR>` however (emulates the old fzf.vim grep behavior).

> Since we had many messages in different threads let’s do a summary here so I can focus on the exact issue:
> 
>     * Is this unique to `live_grep`? Can you preview with no problems with `files()`? What about holding `<C-j>` with `files`?

With `files()` when holding `<C-j>` the gui doesn't freeze. While scrolling the preview stays empty and after finishing scrolling, the preview appears with a small delay.

>     * Is this issue still there without preview enabled (you can close the preview with `<F4>`, or set `winopts.preview.hidden = 'hidden'`)

with `winopts.preview.hidden = 'hidden'` the nvim gui still freezes and becomes unresponsive for several seconds.

>     * Does this happen `live_grep_native` or `:FzfLua grep search=’'`

With `:FzfLua grep search=''` the gui is very very smooth, almost no lags (sometimes the `Rg>` very briefly disappears).
Although, the gui stops after 8k lines (there should be significantly more).
 
>     * Does the shell script [posted above](https://github.com/ibhagwan/fzf-lua/issues/211#issuecomment-964363962)  work with no issues from the shell (this is almost exactly what `live_grep_native` runs)?

For comparison:

* fzf-lua (`:lua require('fzf-lua').grep({ search = '' })<CR>`): GUI freezes for multiple seconds, nvim uses 100% CPU, rg uses between 7% and 120% CPU and fzf stays at < 20 CPU (fzf barely uses memory)
* `live_grep.sh ""` (your script): doesn't seem to properly reproduce the above command. GUI stays responsive, rg uses < 20% cpu, fzf uses 80 - 120% CPU (memory steadily goes up to 1G+, then I stopped)
* original fzf.vim: GUI stays responsive, rg uses 80 - 120% CPU, fzf uses up to 400% CPU (memory goes up very quickly to 1G+, then I stopped).

(these numbers are from a very beefy cpu with 100G+ RAM)

I feel like somehow the lines from `rg` aren't forwarded quick enough to `fzf` (which is why the memory consumption grows so slowly). As if something in nvim goes in between. :thinking: 

>     * What is your fzf version?

```
$ fzf --version
0.25.1 (6654239)
```

**Comment by ibhagwan** [comment] 2021-11-12 18:51
Ty @BenWeber42! This is very helpful.

One questions I didn’t see mentioned, did you try `live_grep_native`?

**Comment by ibhagwan** [comment] 2021-11-12 21:14
Another question for @nyngwang, @kutsan and @BenWeber42:

Are you using the default `rg` command or did you modify `grep.cmd` or `grep.rg_opts`? If you changed the command it might be related to #185 where this can happen with some text files with really long lines which I worked around by adding `--max-columns=512` to the default `rg_opts`.

If we can confirm this is the issue:

- `live_grep_native` should work fine as a workaround
- I will work again on a proper solution in the code even if `--max-columns=512` doesn't exist in the command

**Comment by ibhagwan** [comment] 2021-11-13 03:25
I think I found the issue and fixed it, can you try the latest commit and let me know?

**Comment by nyngwang** [comment] 2021-11-13 10:19
@ibhagwan I think it works! The CPU usage < 10% all-time with 30,000+ results. And my computer temperature never passed 6x degrees.

**Comment by ibhagwan** [comment] 2021-11-13 10:25
> @ibhagwan I think it works! The CPU usage < 10% all-time with 30,000+ results. And my computer temperature never passed 6x degrees.

Yes! I had a good feeling :)

Now will you do me a small favor and test it out with:
```lua
  grep = {
    file_icons = true,
    experimental = true
  }
```

This should add icons to the `live_grep` results, something I’ve been weary about in the past but now that I found the source of this issue I feel more confident changing the default to `experimental = true`.

**Comment by nyngwang** [comment] 2021-11-13 12:50
OK, I think another problem occurs: the cursor didn't scroll to the line where it found the keyword.

**Comment by BenWeber42** [comment] 2021-11-13 16:06
The following is with the not updated version:

```
$ git last
commit cb526dbb0c3af7f5e32011e7b7698b3168ce44a6
Author: bhagwan <bhagwan@disroot.org>
Date:   Thu Nov 11 08:11:14 2021 -0800

    remove 'manually loaded' comment (closes #212)
```

> One questions I didn’t see mentioned, did you try `live_grep_native`?

No sorry, I thought it would be equivalent to `:FzfLua grep search=''` and I couldn't  find documentation on `live_grep_native`, so I'm not sure how to use it.

I tried:

* `:lua require("fzf-lua").live_grep_native()`: gui stays responsive, nvim CPU usage <20%, rg CPU usage < 20%, fzf CPU usage ~120% (memory goes up to 1G+, then I stopped)
* `:lua require("fzf-lua").live_grep_native({ search = '' })`: same as above.
* `:FzfLua grep search=""`: gui becomes very unresponsive (multiple seconds lags), nvim CPU usage ~100%, rg CPU usage ~ 70%, fzf CPU usage ~80% (memory usage goes up very very slowly). Actually, I noticed that nvim used 2G of memory after a little while (haven't checked for the other cases nvim memory usage, but thought might be useful info).


> Are you using the default `rg` command or did you modify `grep.cmd` or `grep.rg_opts`?

I haven't modified either of them so I assume it should take the default values.

So then I udpated to:

```
$ git last
commit 5e899dc046146e386a077c6c2b9d1ad6a0c8f4bb (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: bhagwan <bhagwan@disroot.org>
Date:   Sat Nov 13 01:03:26 2021 -0800

    set correct title highlight length (+1)
```

and got:

* `:lua require('fzf-lua').grep({ search = '' })`: gui unresponsive, nvim ~100% CPU (memory goes up quickly to 1G+), rg & fzf ~100% (though CPU usage varies)
* `:FzfLua grep search=""`: gui unresponsive
* `:lua require("fzf-lua").live_grep_native()`: gui stays responsive, nvim ~20% CPU, rg ~20% CPU, fzf ~120% CPU.

**Comment by ibhagwan** [comment] 2021-11-13 16:45
> OK, I think another problem occurs: the cursor didn't scroll to the line where it found the keyword. And the high-temperature and CPU usage problems still exist when using `live_grep`. The `live_grep_native` works with lower CPU usage. I think you might need to check the precision of the results. I was testing by searching keywords from `~`.

@nyngwang can you screenshot when you have the cursor not scrolling to line? Do your results appear as `file:line:col:matched content`?

What do you mean “check precision” - did you not get the results you were expecting? Do the results differ between `live_grep` and `live_grep_native`?



Ty @BenWeber42, FYI, all the below 4 are the same command (lua has different ways of string representation):
```lua
:FzfLua grep search=""
:lua require('fzf-lua').grep({ search = '' })
:lua require('fzf-lua').grep({ search = "" })
:lua require('fzf-lua').grep({ search = [[]] })
```

I didn’t see if you tested if the commit solved the `live_grep` issue?
Does the `grep` issue happen with smaller repos as well or only the big repo you described?

**Comment by BenWeber42** [comment] 2021-11-13 17:37
> Ty @BenWeber42, FYI, all the below 4 are the same command (lua has different ways of string representation):
> 
> ```lua
> :FzfLua grep search=""
> :lua require('fzf-lua').grep({ search = '' })
> :lua require('fzf-lua').grep({ search = "" })
> :lua require('fzf-lua').grep({ search = [[]] })
> ```

Thanks, good to know. I'm still getting used to lua :sweat_smile: 
 
> I didn’t see if you tested if the commit solved the `live_grep` issue? Does the `grep` issue happen with smaller repos as well or only the big repo you described?

Tested (on newest commit, see my comment above):

* `:lua require("fzf-lua").live_grep({ search = '' })`: gui stays responsive, nvim <20% CPU usage, rg & fzf ~100% CPU usage (fzf memory goes up quickly)
* `:lua require('fzf-lua').grep({ search = '' })` tested with small repo (57 files, 1.1MB): basically loads all results within < 1s into the gui, 2.8k lines, gui stays responsive all the time.

To be honest, I don't understand the behavior of `:lua require("fzf-lua").live_grep({ search = '' })`. When I enter the command, first the results stay empty, nothing loads, 0/0 results. When I start typing, it starts to load results. E.g., I type one letter 't' and it keeps loading results. But then, when I start typing more (e.g., "gennbhtable"), it stops loading results (gui doesn't change at all) and eventually shows 0/0 results. Then when I delete all input, it starts loading all lines again, this is different than when I start it. When I start and give no input, it loads nothing. When I enter input, then delete all input again, it loads everything.

I'm not sure if this is the expected behavior or if this is buggy. If this is an issue, I'm not sure if it's orthogonal to this issue and should have its own github issue or if it makes sense to discuss this behavior in this github issue. This is the reason why I use `grep({ search = '' })`, because it does what I want which is basically to reproduce what the old ripgrep fzf vim plugin did.

**Comment by ibhagwan** [comment] 2021-11-13 18:05
> To be honest, I don't understand the behavior of `:lua require("fzf-lua").live_grep({ search = '' })`. When I enter the command, first the results stay empty, nothing loads, 0/0 results. When I start typing, it starts to load results. E.g., I type one letter 't' and it keeps loading results. But then, when I start typing more (e.g., "gennbhtable"), it stops loading results (gui doesn't change at all) and eventually shows 0/0 results. Then when I delete all input, it starts loading all lines again, this is different than when I start it. When I start and give no input, it loads nothing. When I enter input, then delete all input again, it loads everything.
> 
> I'm not sure if this is the expected behavior or if this is buggy. If this is an issue, I'm not sure if it's orthogonal to this issue and should have its own github issue or if it makes sense to discuss this behavior in this github issue. This is the reason why I use `grep({ search = '' })`, because it does what I want which is basically to reproduce what the old ripgrep fzf vim plugin did.

First you're correct `grep({ search = '' })` is the equivalent of `fzf.vim`'s `:Rg`.

The behavior you're describing is actually by design, first we need to understand the difference between `grep` and `live_grep`:

- `grep`: uses `rg` (or `grep`) to perform a search query, feeds all the results into fzf which then enables fuzzy searching on the results
- `grep({ search = '' })` is a shortcut to an empty query search, it is the equivalent of running `rg --column --line-number --no-heading --color=always --smart-case ''` in the shell, if you tried it you'll see it simply outputs **all lines in all files** with their textual context and as you can imagine feeding the entire lines of a project into the fuzzy finder isn't very efficient (memory, speed, all are impacted)

This is where `live_grep` comes in (`live_grep_native` is the same thing):
- `live_grep` doesn't use fzf's fuzzy search capability at all, it uses only the UI part of `fzf` (therefore you get only exact matches with it)
- Every time your search term changes `fzf` will run a new `rg` command in the background with a new search term, so when you type `fo` it will display the results of `rg <options> 'fo'` and when you add another `o`, a new `rg` command will be run and the results will change to the output of `rg <options> 'foo'`

Regarding `live_grep({ search = '' })` , the empty search has been disabled on purpose as it doesn't make much sense to just display all lines of the project before you know what you want to search for, if you still wish to display results without any search term you need to send the `exec_empty_query` flag:
```lua
-- both are the same exact thing
:FzfLua live_grep exec_empty_query=true
:lua require'fzf-lua'.live_grep({exec_empty_query=true})
```

Obviously, to each their own, some prefer to start with fuzzy finding, some prefer exact matches, the workflow I found works best for me is:
- I first run `live_grep` and play around with the search term until I find roughly what I need
- If I need to narrow it down further I will now open `grep_last()` instead (which is a shortcut to `grep({ continue_last_search = true })` - now the result set is smaller and I can fuzzy search on it
- If I still need to do some refinements I will run `live_grep_resume` (again a shortcut to `live_grep({ continue_last_search = true })` to continue where I left off.

**Comment by ibhagwan** [comment] 2021-11-13 18:39
FYI, since I've seen this come up more than a few times, I added the `grep_project` command which is a shortcut to `:lua require'fzf-lua'.grep({ search = "" })` as the equivalent of running `fzf.vim` `:Rg` with no search term.

**Comment by ibhagwan** [comment] 2021-11-21 19:37
Since there are no updates I'm closing this issue for now, I feel the majority of this issue was solved in https://github.com/ibhagwan/fzf-lua/commit/e02451600a5b69669f871cc07d240d3f86978f49.

In addition `live_grep_native` seems to be a good alternative for large code bases.

Feel free to reopen if you're still experiencing freezes.

**Closed by ibhagwan** 2021-11-21 19:37 UTC

**Comment by BenWeber42** [comment] 2021-11-24 14:45
I don't know what's the definition of done here. But `lua require("fzf-lua").grep_project()` is still completely unresponsive in large code bases.

About `live_grep` and `live_grep_native`, do I understand correctly, that neither support fuzzy search unless I use a regex that's _fuzzy_?

I just know that `:Rg` of the old fzf plugin has no problem with the same large code base and supports fuzzy searching out of the box.

**Comment by ibhagwan** [comment] 2021-11-24 18:23
> I don't know what's the definition of done here. But `lua require("fzf-lua").grep_project()` is still completely unresponsive in large code bases.

`grep_project` is merly a shortcut to to `grep({ search = '' })` it's not meant to solve antyhing.

I'd like to solve it as well, the issue in the OP was solved and the title isn't related, if you wish to work on it please open a new issue, while you're at it can you try running without icons at all and seeing if it helps?

```lua
require'fzf-lua'.grep({ search='', file_icons=false, git_icons=false })
```

Also any additional information you can provide would help, if you can pin point what file types causes the freezes, what folder size, etc, anything that would help me narrow it down.


> About `live_grep` and `live_grep_native`, do I understand correctly, that neither support fuzzy search unless I use a regex that's _fuzzy_?

Yes, that's correct. If you want to try something interesting you can install [`skim`](https://github.com/lotabout/skim) which is a rust version of fzf and set `fzf_bin = 'sk'` in the setup function. It has a different implemenation of `live_grep` by way of its ["interactive mode"](https://github.com/lotabout/skim#interactive-mode), if you do that you can switch between fuzzy and exact matches with `ctrl-q` (eseentially switching between `grep` and `live_grep`).

> I just know that `:Rg` of the old fzf plugin has no problem with the same large code base and supports fuzzy searching out of the box.

See my comment above, I'm willing to invest the time and effort into this and it would really help to have more frequent communication, having more than a week in between comments on the same issue makes it harder to tackle something like this as it requires lots of debugging code of the underlying libuv layer.

**Comment by BenWeber42** [comment] 2021-11-25 08:51
I apologize, sorry I hope I didn't come off as rude or demanding. I wasn't sure what the status of the issue was. I agree it's best to close this and track the the performance issue separately.

I will try without icons. Unfortunately, it's not always easy for me to find time for this, but I understand that infrequent communication isn't helpful either...

I think I will try to invest some time into this myself. With a bit of luck I might be able to pin-point the issue.

And I also just want to make sure you know this: I think fzf-lua is a marvelous plugin and you've done a fantastic job with it. I've been looking to upgrade the fzf plugin in my setup for many years and I think fzf-lua is the way forward for this.

**Comment by ibhagwan** [comment] 2021-11-25 17:23
No problem at all @BenWeber42, feel free to open the issue when you find time and we’ll work on it :)

**Comment by ibhagwan** [comment] 2021-12-12 07:15
FYI, I just commited a fundemental change to how fzf-lua works (optional, enabled by default).

Relevant commit: https://github.com/ibhagwan/fzf-lua/commit/2d8a4e9afc7b32cdd7552f1ccd641c8bd6c2e85c

This below is what it does, you can freely `grep{ search = '' }` and expect the UI to be super responsive at all times:

```help
major performance improvement: process entries externally, READ BELOW:
Since LUA is single threaded I reached a limit to performance
optimization, both 'git_icons' and 'file_icons' require string
matching and manipulations which eventually hurt performance
when running on large amount of files.
In order to solve that this commit introduces the option to spawn
commands and process the entries in a separate neovim process which
prints to stdio as if it was a regular shell command. This speeds up
things significantly and also makes the UI super responsive as if fzf
was run in the shell. This required a few lua hacks to be able to load
nvim-web-devicons in a '--headless --clean' instance and sharing the
user configuration through the RPC interface from the running instance.
This is enabled by default for 'files' and 'grep' providers and can also
be enabled for 'git.files' if required, control using the 'multiprocess'
option.
```
