### ISSUE TITLE
Bug: When I search some strings with grep and save the search result to a history file, but it also generates a temporary file in current search directory

### ISSUE THREAD

**Issue by fchyang** [ibhagwan/fzf-lua#1648] opened 2024-12-27 03:04 UTC
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

Bash

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.55.0 (fc69308)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--inline-info

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

1. When I searched for a string like ‘winopts’ with grep, grep_cword or live_grep in ~/.config/nvim/lua and saved the search result to a file in ~/.local/share/nvim/fzf-history, but it also generated a temporary file named winopts in ~/.config/nvim/lua.
![image](https://github.com/user-attachments/assets/68dab5f0-3ace-4223-8e48-44f025c75ba3)
```
vim.keymap.set("n", "<A-b>",
  function() require('fzf-lua').grep({
  --function() require('fzf-lua').live_grep({
  --function() require('fzf-lua').grep_cword({
     cmd = "rg -g '*.cpp' -g '*.cc' -g '*.h' -g '*.c' -g '*.java' -g '*.rs' -g '*.bp' "
              .. "-g '*.mk' -g '*.py' -g '*.xml' -g '*.lua' "
              .. "--glob '!.git/*' --glob '!.repo/*' --glob '!tags' --glob '!.go' "
              .. "--column --line-number --no-heading --color=always --smart-case "
              .. "--no-ignore --no-ignore-dot -- "
              .. vim.fn.shellescape(vim.fn.expand('<cword>'))
              .. " | tee ~/.local/share/nvim/fzf-history  ",
      winopts = { fullscreen=true,},
      search = vim.fn.expand('<cword>'),
      actions = require'fzf-lua'.defaults.actions.files,
      file_icons = false,
      color_icons = false,
    })
 end, { desc = "Fzf Grep Search" })
```
2. But when I searched the string ‘winopts’ with fzf_exec by rg in ~/.config/nvim/lua, there was no temporary file named winopts in ~/.config/nvim/lua
```
vim.keymap.set("n", "<C-x>",
  function() require('fzf-lua').fzf_exec(
      "rg -g '*.cpp' -g '*.cc' -g '*.h' -g '*.c' -g '*.java' -g '*.rs' -g '*.bp' "
              .. "-g '*.mk' -g '*.py' -g '*.xml' -g '*.lua' "
              .. "--glob '!.git/*' --glob '!.repo/*' --glob '!tags' --glob '!.go' "
              .. "--column --line-number --no-heading --color=always --smart-case "
              .. "--no-ignore --no-ignore-dot -- "
              .. vim.fn.shellescape(vim.fn.expand('<cword>'))
              .. " | tee ~/.local/share/nvim/fzf-history  ",
      {
        prompt = 'Rg> ',
        hls = {
          cursor = "IncSearch",
          search= "IncSearch",
        },
        previewer = "builtin",
        winopts = { fullscreen=true, },
        search = vim.fn.expand('<cword>'),
        actions = require'fzf-lua'.defaults.actions.files,
      }
    )
 end, { desc = "Fzf Grep Search" })
```
3. So I don't know why？Can you help me？Thanks！

**Comment by ibhagwan** [comment] 2024-12-27 03:16
You’re `cmd` is wrong, you don’t need to expand cword in both the cmd and the `search`, the search will be added by fzf-lua, if you wanna do it this way use `raw_cmd` instead.

> `tee ~/.local/share/nvim/fzf-history`

What’s in this file and what’s the purpose of it? If you want search history why not use fzf_opts `--history`?
https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-setup-input-history-keybinds

**Comment by fchyang** [comment] 2024-12-27 06:31
> You’re `cmd` is wrong, you don’t need to expand cword in both the cmd and the `search`, the search will be added by fzf-lua, if you wanna do it this way use `raw_cmd` instead.
>=> using the raw_cmd is  ok ！
> > `tee ~/.local/share/nvim/fzf-history`
> 
> What’s in this file and what’s the purpose of it? If you want search history why not use fzf_opts `--history`? https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-setup-input-history-keybinds
>=> Yes, I had tried it, it seemed to only have the history of input? but I want to setup output history, so I used 'tee cmd' to save the searched results to fzf-history file, then I binded alt-r to open the output history, if I want to check the results. it would be quick. Because I work with a large code base(Android Source Code) , if I re-search the string again, it would consume some time.
```
vim.keymap.set("n", "<A-r>",
  function() require('fzf-lua').fzf_exec(
    "bat ~/.local/share/nvim/fzf-history",
    {
      previewer = "builtin",
      winopts = { fullscreen=true,},
      actions = require'fzf-lua'.defaults.actions.files
    }
  )
  end, { desc = "Fzf Grep Search" })
```

**Comment by ibhagwan** [comment] 2024-12-27 15:00
> using the raw_cmd is ok !

I’m sure the command is ok  and also there is no issue using it with `fzf_exec` but not with `grep_xxx`, the reason is that the grep pickers **add the search regex after the command** so in this case will be added after the `tee` (**and that’s why searching for `winopts` also generates a file in that name**), maybe you can add it as `filter = ` instead?
https://github.com/ibhagwan/fzf-lua/blob/76e25abc4bbaab243b52fad7f7d4262e76254fd3/lua/fzf-lua/providers/grep.lua#L106-L112

Like this:
```lua
require('fzf-lua').grep({
     cmd = "rg -g '*.cpp' -g '*.cc' -g '*.h' -g '*.c' -g '*.java' -g '*.rs' -g '*.bp' "
              .. "-g '*.mk' -g '*.py' -g '*.xml' -g '*.lua' "
              .. "--glob '!.git/*' --glob '!.repo/*' --glob '!tags' --glob '!.go' "
              .. "--column --line-number --no-heading --color=always --smart-case "
              .. "--no-ignore --no-ignore-dot -- ", -- remove cword from here it’s wrong 
      winopts = { fullscreen=true,},
      filter = 'tee ~/.local/share/nvim/fzf-history',
      search = vim.fn.expand('<cword>'),  -- cword can only be in `search`
      -- actions = require'fzf-lua'.defaults.actions.files,  -- this is the default, don’t need this
      file_icons = false,
      color_icons = false,
    })
```

> but I want to setup output history, so I used 'tee cmd' to save the searched results to fzf-history file

You can do this perhaps differently, why not have a custom action that writes the results into the file using lua code and then call the original edit, for example:
```lua
actions = {
  ["enter"] = function(sel, opts)
    -- add lua code that saves `sel` table to file
    actions.file_edit(sel,opts)
  end
}
```

Also what about sending to quick fix and then using `quickfix_stack`? It saves results based on the query and you can go back and forth between the different result sets:
![IMG_2846](https://github.com/user-attachments/assets/b8d0a39a-65b2-4827-aa0a-0131c399b375)

**Comment by ibhagwan** [comment] 2024-12-29 02:57
Closing as not a bug, if my answer isn't sufficient feel free to continue the discussion.

**Closed by ibhagwan** 2024-12-29 02:57 UTC
Labels: invalid
