### ISSUE TITLE
fzf-lua adds highlighted file to quickfix list when closing fzf popup by <C-q> (whitout having selecting a file there).

### ISSUE THREAD

**Issue by dcordb** [ibhagwan/fzf-lua#56] opened 2021-08-28 12:45 UTC
If we, for example, execute `:FzfLua files` and not select anything, just press `<C-q>` (binding of FZF to close), then the highlighted file will be added to the quickfix list. And the quickfix list will be opened too.

The behaviour I would want is that it won't add that file to the quickfix list.

**Comment by dcordb** [comment] 2021-08-28 12:55
I peeked at the code and I see that the opening of quickfix happens here:

https://github.com/ibhagwan/fzf-lua/blob/233062d7e684c9cabeb6f175b6958382c76e71ca/lua/fzf-lua/actions.lua#L79-L93

But I see the if you got there:

https://github.com/ibhagwan/fzf-lua/blob/233062d7e684c9cabeb6f175b6958382c76e71ca/lua/fzf-lua/actions.lua#L80

So maybe we need to check the value of `selected` there :thinking:.

I can reproduce this consistently with the following minimal config:

```
call plug#begin('~/.config/nvim/plugged') " change here for your plugin's directory
    Plug 'ibhagwan/fzf-lua'
    Plug 'vijaymarupudi/nvim-fzf'
call plug#end()
```

**Comment by jpe90** [comment] 2021-08-28 15:06
Actually <C-q> appears to be a specific binding for sending selected to quickfix:

https://github.com/ibhagwan/fzf-lua/blob/233062d7e684c9cabeb6f175b6958382c76e71ca/lua/fzf-lua/config.lua#L44

**Comment by ibhagwan** [comment] 2021-08-28 15:28
Seems like the issue here is trying to use an already set to bind to close fzf, if you already have the muscle memory for `C-q` to close `fzf` why don’t you change the “send to quickfix list” binding to something else which will solve your issue (it will be removed from the `—expect` fzf flag).

As for the issue itself (selected using the highlighted file), I’m not sure if this is fixable, this behavior is controlled by the `fzf` utility, pressing `C-q` without selection is exactly as opening fzf and pressing enter without any selection, it uses the highlighted file instead and that’s why the code can pass the `if not selected or #selected < 2 then return end` condition.

**Comment by ibhagwan** [comment] 2021-08-28 15:34
> Actually <C-q> appears to be a specific binding for sending selected to a quickfix list:
> 
> https://github.com/ibhagwan/fzf-lua/blob/233062d7e684c9cabeb6f175b6958382c76e71ca/lua/fzf-lua/config.lua#L44
> 
> https://github.com/ibhagwan/fzf-lua/blob/233062d7e684c9cabeb6f175b6958382c76e71ca/lua/fzf-lua/config.lua#L124
> 
> Unfortunately binding that customization to "nil" inside my neovim config doesn't seem to disable it, I have to remove the binding from the repo itself.

That’s because of the way lua treats `nil` inside a table, when you set it to `nil` it gets removed from your custom config thus it goes not get merged into the global config, you can set it to `false` (in your `setup` function) to get what you want:

```lua
["ctrl-q"]        = false
```

**Comment by dcordb** [comment] 2021-08-28 23:29
> pressing C-q without selection is exactly as opening fzf and pressing enter without any selection

@ibhagwan why this? for example if you use fzf from the shell, do not select anything and then press `<C-q>` then fzf will close, no result will be given and the exit status of fzf will be 1 (as documented in fzf's manual).

Is it possible for you to watch the exit status of the spawned fzf, and if it's 1 then set `selected` to an empty table ?

**Comment by dcordb** [comment] 2021-08-28 23:49
Well, I just did as you said, disabled the `<C-q>` remap, and then added `<C-s>` to send files to quickfix. Although the ideal thing would be to do both with a single remap, but for now this is not such of an issue I think.

**Comment by ibhagwan** [comment] 2021-08-29 02:15
> > pressing C-q without selection is exactly as opening fzf and pressing enter without any selection
> 
> @ibhagwan why this? for example if you use fzf from the shell, do not select anything and then press `<C-q>` then fzf will close, no result will be given and the exit status of fzf will be 1 (as documented in fzf's manual).
> 
> Is it possible for you to watch the exit status of the spawned fzf, and if it's 1 then set `selected` to an empty table ?
> 
> **UPD**: Also this is the way that `fzf.vim` works: you press `<C-q>` and it closes fzf window, and no file is opened.

Perhaps you’re right, I didn’t really test it as I’m still working on a big feature but I suspect it was because when you set an action bind it adds `—expect=ctrl-q` to the fzf flags.

**Comment by ibhagwan** [comment] 2021-08-29 02:17
> Well, I just did as you said, disabled the `<C-q>` remap, and then added `<C-s>` to send files to quickfix. Although the ideal thing would be to do both with a single remap, but for now this is not such of an issue I think.

I’ll get to this in a couple of days and see if I can make it work the way you want, perhaps through a combination of the fzf shell exit code.

**Comment by ibhagwan** [comment] 2021-08-30 07:35
I just tested the usage of the `--expect` flag along with your suggestion of testing the shell error, I'm afraid we hit a roadblock, in order to receive the `ctrl-q` in neovim (in order to send to quickfix list) I must add the `--expect` flag, the issue is that when the flag is added fzf will not raise a shell error when nothing is selected, it will simply treat the highlighted item as selected.

You can test it yourself in the shell with these two commands:
```sh
❯ echo "1\n2\n3" | fzf
❯ echo "1\n2\n3" | fzf --expect=ctrl-q
```
The second command never sets a shell error while the first command always sets a shell error (with items selected or not).

Were you able to make this work the way you want with `fzf.vim`, if so I can probably make it work, otherwise, quite honestly I don't see how this is really worth an effort on my end.

**Closed** 2021-08-30 16:12 UTC
Labels: question

**Comment by dcordb** [comment] 2021-08-30 16:55
> The second command never sets a shell error while the first command always sets a shell error (with items selected or not).

I see. It seems that it's not possible. Thanks for your explanation!
