### ISSUE TITLE
No symbol highlights when looking at fzf results

### ISSUE THREAD

**Issue by jackfranklin** [ibhagwan/fzf-lua#719] opened 2023-04-06 06:44 UTC
### Info

- Operating System: Ubuntu, via WSL.
- Shell: Fish
- Terminal: Alacritty for Windows
- `nvim --version`: `NVIM v0.9.0-dev-1230+gd1e0f7454`
- `fzf --version`: `0.38.0 (352ea07)`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
  keymap = {
    fzf = {
      ["ctrl-q"] = "select-all+accept",
    },
  },
  winopts = {
    height = 0.2,
    preview = {
      hidden = "hidden",
    },
  },
  oldfiles = {
    cwd_only = true,
  },
})
```
</details>

### Description 

I have this odd issue where colours do not get applied when looking at fzf results.

However, if I run FzfLua highlights, it all looks fine:

![colors-working](https://user-images.githubusercontent.com/193238/230292844-506a2efe-8df7-41e3-9ed9-ed35dee26c8d.png)

But if I look at document symbols I do not get any highlighting:

![not-working](https://user-images.githubusercontent.com/193238/230292993-a028f988-da42-45b8-a294-e2280ca9fbc3.png)

I am wondering if you have seen this before or have anything I could try to rectify the issue? Thanks!

**Comment by jackfranklin** [comment] 2023-04-06 06:54
Going to attempt to track down a possible commit - I pinned my fzf-lua version to https://github.com/ibhagwan/fzf-lua/commit/5147c4d8b99a0a5821b8bd5f918a17e83cb113e9 and the colours now work fine. Will report back if I can get more specific!

**Comment by jackfranklin** [comment] 2023-04-06 06:56
As of https://github.com/ibhagwan/fzf-lua/commit/27550b6d44b57e069705901169e5d021e264ef2f  (March 9th) the colours worked.

**Comment by ibhagwan** [comment] 2023-04-06 14:39
That’s “by design”, since PR #682 the highlights changed and now match the treesitter highlights, if you wish to have `Variable` highlighted you’d need to modify or link your current colorscheme `@variable` highlight group.

**Comment by jackfranklin** [comment] 2023-04-07 07:42
@ibhagwan sorry for the silly question, do you have an example of how I would customise the color of `@variable`, for example? I am struggling to understand it.

**Comment by jackfranklin** [comment] 2023-04-07 12:11
Turns out that this was not an issue with my theme, but I needed to explicitly turn symbols off: https://github.com/jackfranklin/dotfiles/commit/1bc564acc86a95339f32cc46caaa72a971f019d0

Once I did that, I got the colours back:

![Screenshot 2023-04-07 140829](https://user-images.githubusercontent.com/193238/230606591-a16fab21-7094-483f-b98c-2f8d65bc92be.png)

**Comment by ibhagwan** [comment] 2023-04-07 14:26
> Turns out that this was not an issue with my theme, but I needed to explicitly turn symbols off:
> Once I did that, I got the colours back:

I’m not sure why this happens, what font are you using?

**Comment by ibhagwan** [comment] 2023-04-16 19:30
Closing, feel free to reopen if you need more help.

**Closed by ibhagwan** 2023-04-16 19:30 UTC
Labels: question
