### ISSUE TITLE
Bug: Improper version check causes issues with winfixbuf

### ISSUE THREAD

**Issue by Grazfather** [ibhagwan/fzf-lua#1340] opened 2024-07-17 13:16 UTC
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev

### Fzf version (`fzf --version`)

0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

0

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

Related to #1303. In fact the same issue.

The version check should know to exclude `-dev` versions.

With nvim 0.10.0-dev we do not have `winfixdev`. The version checks should (probably) assume an older version if we are on the -dev version.

**Comment by ibhagwan** [comment] 2024-07-17 14:17
> With nvim 0.10.0-dev we do not have winfixdev. The version checks should (probably) assume an older version if we are on the -dev version.

Duplicate of #1303, this isn’t a bug, `winfixbuf` is part of 0.10, please update your old nightly to 0.10 release.

**Closed by ibhagwan** 2024-07-17 14:17 UTC
Labels: duplicate, invalid

**Comment by Grazfather** [comment] 2024-07-17 17:08
Right. I am saying that it's a bug. Some people (myself included) can't get off of that particular version on a managed system.

You could probably fix this issue for everyone by going into [_utils.lua_](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/utils.lua#L13) and changing:

```lua
M.__HAS_NVIM_06 = vim.fn.has("nvim-0.6") == 1
M.__HAS_NVIM_07 = vim.fn.has("nvim-0.7") == 1
M.__HAS_NVIM_08 = vim.fn.has("nvim-0.8") == 1
M.__HAS_NVIM_09 = vim.fn.has("nvim-0.9") == 1
M.__HAS_NVIM_010 = vim.fn.has("nvim-0.10") == 1
M.__HAS_NVIM_011 = vim.fn.has("nvim-0.11") == 1
```

to
```lua
M.__HAS_NVIM_06 = (vim.fn.has("nvim-0.6") == 1) and (vim.fn.has("nvim-0.6-dev") != 1)
M.__HAS_NVIM_07 = (vim.fn.has("nvim-0.7") == 1) and (vim.fn.has("nvim-0.7-dev") != 1)
M.__HAS_NVIM_08 = (vim.fn.has("nvim-0.8") == 1) and (vim.fn.has("nvim-0.8-dev") != 1)
M.__HAS_NVIM_09 = (vim.fn.has("nvim-0.9") == 1) and (vim.fn.has("nvim-0.9-dev") != 1)
M.__HAS_NVIM_010 = (vim.fn.has("nvim-0.10") == 1) and (vim.fn.has("nvim-0.10-dev") != 1)
M.__HAS_NVIM_011 = (vim.fn.has("nvim-0.11") == 1) and (vim.fn.has("nvim-0.11-dev") != 1)
```

**Comment by Grazfather** [comment] 2024-07-17 17:14
Looks like you'd probably want to check if `-dev` is in `vim.version()`, which might be tough since e.g. `nvim-0.10-dev` is not full nvim-0.10 but is full nvim-0.9

**Comment by ibhagwan** [comment] 2024-07-17 17:15
> Right. I am saying that it's a bug

This isn’t a bug, I cannot guarantee what development version you have, what if you’re stuck on a dev version post the commit that **does include** `winfixbuf`, in such case the code will fail for all the others running 0.10-dev with a later commit than your current one.

You should use a neovim release, either 0.9.5 or 0.10 or if you insist on a dev version use the latest  0.11 nightly, if you cannot do that pin your fzf-lua commit to before the  `winfixbuf` change.

**Comment by ibhagwan** [comment] 2024-07-17 17:20
> Looks like you'd probably want to check if `-dev` is in `vim.version()`, which might be tough since e.g. `nvim-0.10-dev` is not full nvim-0.10 but is full nvim-0.9

This is a hack not a solution, there are many other changes with each new version immediately, for example, in the latest 0.11 nightly `vim.tbl_xxx` deprecations, this is just one example of many other unintended consequences.

Aside from the latest nightly which I keep up to date and make sure should always work I cannot support older versions dev builds, while possible, the overhead and code complexity doesn’t justify it, if you can’t update your neovim version you should also work with an older fzf-lua version that worked before the changes.

**Comment by Grazfather** [comment] 2024-07-17 17:24
If my dev commit did have winfixbuf, it would still be safe to assume it doesn't, no? On another machine with a full 0.10 release, for example, I made `__HAS_NVIM_010` false and everything still works fine.

Deprecations would be an issue, but they shouldn't be removed (afaict) in the next version, so it would still be safe to basically assume one minor version behind if the version is `-dev`.

I'll rollback to work around this issue, but if you have code that tests for a feature, and it doesn't actually have that feature, then that is most certainly a bug in your code.

Thanks for your response.

**Comment by ibhagwan** [comment] 2024-07-17 22:41
@Grazfather, the test for `-dev` is faulty, but it’s possible to test for existence of an option with `vim.fn.exists`, https://github.com/ibhagwan/fzf-lua/commit/023b95078f9cc28ce67d7a7a6b4ea1bc7cfa488d should solve your issue.

**Comment by Grazfather** [comment] 2024-07-18 12:51
Tested on my two machines, one with 0.10.0-dev, and one with the full release. It works great on both.

Thanks for fixing this!

By the way, I looked into why I was stuck on that version, and it's because the [neovim-unstable](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) PPA for ubuntu is stuck on that version for some reason.

The [stable](https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable) ppa is stuck on 0.7.2, unfortunately.

**Comment by Grazfather** [comment] 2024-07-18 19:34
Seems another check should be added around line 142

**Comment by ibhagwan** [comment] 2024-07-18 21:26
> Seems another check should be added around line 142

https://github.com/ibhagwan/fzf-lua/commit/6b5c48fe40695c0b1df61c1bbf7fdcfca04c7e16
