### ISSUE TITLE
Issue with git_status in Lua files

### ISSUE THREAD

**Issue by idr4n** [ibhagwan/fzf-lua#1089] opened 2024-03-18 20:46 UTC
### Info

- Operating System: macOS
- Shell: fish
- Terminal: wezterm
- `nvim --version`: nightly
- `fzf --version`:  ?

- [X] The issue is reproducible with `mini.sh`: Yes, it is

<img width="1332" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/20104703/245478a5-4b5c-487d-9dfb-779aca5289b7">

### Description 

When there are changes in Lua file, I get the error above. Seems to be something related to treesitter.

**Comment by ibhagwan** [comment] 2024-03-18 21:06
Seems unleaded to fzf lua, you’re using the nightly and the error seems to be coming from the runtime, can you  try with the latest nightly or 0.9.5?

**Comment by idr4n** [comment] 2024-03-18 21:13
Yes, you are right, Just tested it with 0.9.5 and the issue is not there. Thanks a lot. Closing this then.

**One questions though**. I used to be able to filter modified files with `FzfLua files` by typing `M` but not anymore. In that case I didn't have to use `git_status`. Is there any way to get that back?

**Comment by ibhagwan** [comment] 2024-03-18 21:19
> Yes, you are right, Just tested it with 0.9.5 and the issue is not there. Thanks a lot. Closing this then.
> 
> **One questions though**. I used to be able to filter modified files with `FzfLua files` by typing `M` but not anymore. In that case I didn't have to use `git_status`. Is there any way to get that back?

The icon fields have been excluded from search post #1080, so you can now search for `^filename` for entries starting with `filename`,  you can disable the new behavior by setting `fzf_opts = {["--nth"] = false }`.

**Comment by idr4n** [comment] 2024-03-18 21:21
> The icon fields have been excluded from search post #1080, so you can now search for `^filename` for entries starting with `filename`, you can disable the new behavior by setting `fzf_opts = {["--nth"] = false }`.

Awesome! Thanks again.

**Comment by idr4n** [comment] 2024-03-18 21:27
Sorry to bother, but `fzf_opts = { ["--nth"] = false }` doesn't seem to do anything in terms of searching for modified files in `FzfLua files`. Maybe I didn't understand what you meant?

**Comment by ibhagwan** [comment] 2024-03-18 21:40
> Sorry to bother, but `fzf_opts = { ["--nth"] = false }` doesn't seem to do anything in terms of searching for modified files in `FzfLua files`. Maybe I didn't understand what you meant?

My bad, use `:lua require("fzf-lua").files({ _fzf_nth_devicons=false})` (or put it under `({ files = …})`

**Comment by idr4n** [comment] 2024-03-18 21:47
Great, that worked like a charm! Now I can search for modified files as before. Thanks a lot!

**Comment by ibhagwan** [comment] 2024-03-18 22:39
@idr4n Im trying but can’t reproduce the original issue, can you check if this still happens with the latest nightly or was it happening only with an older development build?

If there’s a compatibility issue wirh the nightly I’d like to solve it but this doesn’t happen on my end.

**Comment by idr4n** [comment] 2024-03-19 01:56
@ibhagwan Yes, I just checked and it is still happening in the latest nightly:

NVIM v0.10.0-dev-2626+g9d315fb8b
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188

**Comment by ibhagwan** [comment] 2024-03-19 02:32
> @ibhagwan Yes, I just checked and it is still happening in the latest nightly:
> 
> NVIM v0.10.0-dev-2626+g9d315fb8b Build type: RelWithDebInfo LuaJIT 2.1.1710088188

Still can’t reproduce it, same version, lua file in git-status, maybe it’s a Mac thing? I’m on Linux.

Can you press f3 to toggle the preview wrap and post the complete stack trace so I can explore the runtime code and see why this happens?

**Comment by ibhagwan** [comment] 2024-03-19 02:42
It seems to be failing at the line below, only I’m not sure why, this is the headless command wrapper it shouldn’t be starting treesitter for the lua file in the fzf native previewer in the output of git diff, I’m confused what’s happening here

https://github.com/neovim/neovim/blob/79af4e7e734ed460eddbd57b7bf70d3e1624d772/runtime/lua/vim/treesitter/language.lua#L104

**Comment by idr4n** [comment] 2024-03-19 03:10
> Can you press f3 to toggle the preview wrap and post the complete stack trace so I can explore the runtime code and see why this happens?

Sure, here it is:

<img width="792" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/20104703/ffd04381-635b-40d6-a3a2-13fc6428e8a4">

**Comment by ibhagwan** [comment] 2024-03-19 03:34
> Sure, here it is:

That confirms the line in the runtime I linked earlier, I also tested on Mac (with a lua file) and can’t reproduce it and since you also tested with `mini.sh` I’m a bit stumped what could be causing this.

**Comment by ibhagwan** [comment] 2024-03-19 03:37
Can you pinpoint what happened that made you first notice this issue? Did you update fzf-lua or upgraded to the nightly (or both?)? Was there any fzf-lua commit where this worked fine prior?

**Comment by ibhagwan** [comment] 2024-03-19 03:39
One more question, have you tried with the prebuilt binaries from neovim releases or are you building it yourself from source?

**Comment by idr4n** [comment] 2024-03-19 03:49
> Can you pinpoint what happened that made you first notice this issue? Did you update fzf-lua or upgraded to the nightly (or both?)? Was there any fzf-lua commit where this worked fine prior?

Actually I was using Telescope's git_status until now but wanted to use only fzflua so I tried it out and I noticed it just yesterday. In Telescope does not happen.

> One more question, have you tried with the prebuilt binaries from neovim releases or are you building it yourself from source?

I download the prebuilt binary from neovim release. I pretty much use this approach:

```
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
tar xzf nvim-macos.tar.gz
./nvim-macos/bin/nvim
```

Finally, I just tested it in a fresh install of LazyVim with only Fzf-lua install (on top of the LazyVim default plugins), and it is happening there as well.

**Comment by idr4n** [comment] 2024-03-19 04:04
Also, I noticed that LazyVim (and in my own config as well), `version = false` is used for installing treesitter. I think in your nvim-lua config you don't have that. Could it be that `version = false` install the latest version of treesitter?

**Comment by ibhagwan** [comment] 2024-03-19 04:42
> Actually I was using Telescope's git_status until now but wanted to use only fzflua so I tried it out and I noticed it just yesterday. In Telescope does not happen.

That’s because this is coming from the external neovim, fzf-lua uses neovim as a command wrapped by running the preview as a `neovim --headless --clean -- cmd … {}`, the curly braces are then replaced by fzf with the elected entry and fzf-lua will run the preview command inside (git diff, bat, etc), the error we’re seeing comes from that external instance not the main instance (which Telsscope runs in).

> Also, I noticed that LazyVim (and in my own config as well), version = false is used for installing treesitter. I think in your nvim-lua config you don't have that. Could it be that version = false install the latest version of treesitter?

I’m not sure what this means, where should I specify `version = false`? I’ll do some digging :)

**Comment by ibhagwan** [comment] 2024-03-19 04:46
I just looked, I’m not using any version variable in my lazy.nvim for treesitter, doesn’t that mean I’m using the latest HEAD directly from git?

**Comment by ibhagwan** [comment] 2024-03-19 05:08
@idr4n, I had an idea to disable the ftplugins on the headless wrapper using `g:did_load_filetypes`, I believe this should solve the issue as we never want to edit the files in the headless wrapper they’re just used as args for our command, can you try [branch 1089](https://github.com/ibhagwan/fzf-lua/tree/1089) and let me know if that solves the issue?

**Comment by idr4n** [comment] 2024-03-19 09:56
Thanks @ibhagwan, I just tested branch 1089 and indeed that solves the issue in the latest nightly nvim version (in the stable version also remains OK as before).

**Comment by ibhagwan** [comment] 2024-03-19 15:45
Ty @idr4n, merged to main, closing.

**Closed by ibhagwan** 2024-03-19 15:45 UTC
Labels: bug
