### ISSUE TITLE
preview window border placement wrong when using alpha-nvim

### ISSUE THREAD

**Issue by jdrouhard** [ibhagwan/fzf-lua#711] opened 2023-04-01 16:23 UTC
### Info

- Operating System: macOS
- Shell: zsh 5.8
- Terminal: kitty
- `nvim --version`: NVIM v0.9.0-dev-1311+g643c0ed57
- `fzf --version`: 0.38.0 (352ea07)

- [X] The issue is reproducible with `mini.sh` (sorta)...

Need the following diff to master:

```diff
diff --git a/scripts/init.lua b/scripts/init.lua
index 5a685c6..c994664 100644
--- a/scripts/init.lua
+++ b/scripts/init.lua
@@ -14,5 +14,7 @@ vim.api.nvim_set_keymap("n", "<C-l>", [[<Cmd>lua require"fzf-lua".live_grep_glob
 vim.api.nvim_set_keymap("n", "<C-g>", [[<Cmd>lua require"fzf-lua".grep_project()<CR>]], {})
 vim.api.nvim_set_keymap("n", "<F1>", [[<Cmd>lua require"fzf-lua".help_tags()<CR>]], {})
 
+require("alpha").setup(require("alpha.themes.dashboard").config)
+
 require("fzf-lua").utils.info(
   "|<C-\\> buffers|<C-p> files|<C-g> grep|<C-l> live grep|<C-k> builtin|<F1> help|")
diff --git a/scripts/mini.sh b/scripts/mini.sh
index 69d86fb..85de86e 100755
--- a/scripts/mini.sh
+++ b/scripts/mini.sh
@@ -36,6 +36,7 @@ if [ "${1:-}" = "reset" ]; then
 fi
 
 download_plugin "nvim-tree" "nvim-web-devicons"
+download_plugin "goolord" "alpha-nvim"
 
 # if exists, link to local folder so we can test local changes
 if [ -d "${plug_dir}" ]; then
```

### Description 
Hi again @ibhagwan !

So I'm honestly not sure if this is an alpha-nvim bug or a bug with fzf-lua, but I thought I'd start here :)

When using alpha-nvim and the `dashboard` theme, opening fzf-lua causes the preview window border to be shifted to the left by a few columns, and the z-index for the fzf window is higher. This causes the preview window border to be truncated on the left side by the fzf window, and by the preview buffer itself on the right side.

Using the diff above and using the mini.sh script, just type `<c-p>` to see what I'm talking about:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/394891/229302533-3ed08d40-a8de-4f9f-bfae-99a79fd7b8a3.png">

The title in the preview window border is truncated, and the preview window itself extends past the right-side of the border, so it seems like the border is calculated too far to the left.

**Comment by ibhagwan** [comment] 2023-04-01 16:35
Hi @jdrouhard, it’s been a while :)

Let me do some digging later today and get back to you.

**Comment by ibhagwan** [comment] 2023-04-01 16:42
Strange, it doesn't seem to replicate on my end, tried both horizontal and veritcal splits (you can see the alpha.nvim dashboard faintley at the top:
![image](https://user-images.githubusercontent.com/59988195/229303540-3885bd84-ca4e-4654-90d8-3fd2077ec20e.png)

![image](https://user-images.githubusercontent.com/59988195/229303547-88dcdbd2-f955-4367-b70c-8a627c3ca8ae.png)

**Comment by jdrouhard** [comment] 2023-04-01 16:52
Weird, it is reproducible for me every time with just the minimal config (with the diff in the issue description). I tried it inside and outside tmux, and with both kitty and iTerm2.

What else could cause the difference between our systems? Try making your terminal window smaller or something?

**Comment by ibhagwan** [comment] 2023-04-01 16:54
> Weird, it is reproducible for me every time with just the minimal config (with the diff in the issue description). I tried it inside and outside tmux, and with both kitty and iTerm2.

I was able to reproduce it only with the nightly and only with my screen at full width, strange thing is the row/col/height/width numbes as well as anchor paramaters are **all the same**, even stranger when I press F5/F6 to change preview layout I can rotate it back to horizontal position and it displays normally with the exact same numbers - could this be a neovim nightly bug?

**Comment by ibhagwan** [comment] 2023-04-01 16:57
Full screen width with neovim nightly:
![image](https://user-images.githubusercontent.com/59988195/229304221-ebc256be-6713-470a-98bd-b2b0e1986374.png)

After pressing `F6` followed by `F5`:
![image](https://user-images.githubusercontent.com/59988195/229304230-ee84e4f3-b8cf-4ca1-8f51-5cf14c312e1f.png)

Not sure where this is coming from, what's even stranger is that it won't happen with my default config and neovim nightly and only with `mini.sh` + `alpha.nvim`.

Given these circumstances I'm leaning more towards a neovim float window bug that is somehow triggered by `alpha.nvim` initiated settings/calls?

**Comment by jdrouhard** [comment] 2023-04-01 17:08
Ah, it only happens on nightly. That was going to be my next thought if you couldn't repro, still.

I guess it's time to bisect.

**Comment by jdrouhard** [comment] 2023-04-01 17:56
It's https://github.com/neovim/neovim/commit/fedf002cb34d0d7a50c54f84a2f161984db2a4c2

**Comment by ibhagwan** [comment] 2023-04-01 18:08
Ty @jdrouhard, this is very helpful!

> Maybe there's something to do to somehow figure out where the cursorcolumn should be before figuring out where to put the preview window border? Again, haven't looked through fzf-lua code too closely yet. Let me know if you'd like me to dig further (or if this is actually a neovim bug).

I’ll take a deeper look in the code and see if this new “feature” or a bug and if it can be resolved from the fzf-lua side.

**Comment by ibhagwan** [comment] 2023-04-01 18:21
At first glance, this does seem to indicate a neovim bug, I added debugging for the `nvim_open_win` parameters, I tried closing and reopning the preview with `F4` and the layour fixes itself after redraw, moreover, the parametes are exactly the same and seem accurate (border at col `91` and preview at col `92`) yet the border window opens in the wrong position which, to me, indicates a neovim bug:
![image](https://user-images.githubusercontent.com/59988195/229307882-64fd4f38-5f93-4a89-a815-f1e4dc8b6bb6.png)


The only thing I'm not sure about is what call in `alpha.nvim` triggers this issue.

**Comment by jdrouhard** [comment] 2023-04-01 18:24
I'm not really sure how to make a minimal repro that shows what the problem is exactly? Like, what exactly is the issue? Is the cursorcolumn in one column but reporting another?

If it's a neovim bug, I'd like to report it so someone could have a chance to fix it before the 0.9 release (if it's a small bug).

**Comment by ibhagwan** [comment] 2023-04-01 18:26
> I'm not really sure how to make a minimal repro that shows what the problem is exactly? Like, what exactly is the issue? Is the cursorcolumn in one column but reporting another?
> 
> If it's a neovim bug, I'd like to report it so someone could have a chance to fix it before the 0.9 release (if it's a small bug).

I'm not sure how to create a minimal repro either but the issue seems to be `nvim_open_win` that opens in the wrong cooridates.

Given your bisect I'm pretty sure it's related to the cursor column fixes but unsure about the combination of events that cause `nvim_open_win` to open in the wrong column.

**Comment by ibhagwan** [comment] 2023-04-01 18:34
More info below.

This is where I got my debugging info:
https://github.com/ibhagwan/fzf-lua/blob/30fb626355d4b65cb6922d7de8bdb2a276b7d97e/lua/fzf-lua/win.lua#L508

If you `vim.pretty_print` the `nvim_open_win` variables in the lines below you'll see the parmeters  I posted above, they're always the same, the border window is one column before the preview window (preview contents) and 2 columns wider (to be able to draw the border).

On the first call `nvim_open_win` is called with  **correct parmaters**  but is being drawn in the wrong location (few columns before the preview contents window), when we close and reopen the preview `nvim_win_set_config` is called **with the same paramters** which draws the window in the correct position.

While I'm not sure how to minimally reproduce this, it's pretty clear to me this is a neovim bug which causes `nvim_open_win` to draw the window in the wrong position.

**Comment by ibhagwan** [comment] 2023-04-20 01:16
@jdrouhard, I see this was fixed with your PR in https://github.com/goolord/alpha-nvim/pull/201 - is this safe to close this issue or is there another potential upstream or fzf-lua related issue?

**Comment by jdrouhard** [comment] 2023-04-20 01:27
There's probably a neovim bug but I don't have the energy or time to chase it down right now 😂

You can close this!

**Closed** 2023-04-20 01:28 UTC
Labels: upstream

**Comment by ibhagwan** [comment] 2023-04-20 01:29
> There's probably a neovim bug but I don't have the energy or time to chase it down right now 😂
> 
> You can close this!

Fair enough given this is a real edge case.
