### ISSUE TITLE
[bug] Gutter background

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1075] opened 2024-03-07 08:40 UTC

**Comment by ibhagwan** [comment] 2024-03-07 15:26
What do you expect me to do with this issue?

I’m hoping this is an oversight on your end (an empty issue with just a title), aside from the fact I can’t actually help you without knowing what is bugged or how to reproduce the bug this is very disrespectful, I take a lot of my time to answer issues very respectfully and very detailed and go out of my way to help users yet you can’t even decline the issue properly (not to even mention the issue template)?

**Comment by ibhagwan** [comment] 2024-03-07 15:30
Duplicate of #1075

**Closed by ibhagwan** 2024-03-07 15:30 UTC
