### ISSUE TITLE
Need to patch nvim-web-devicons setup bug

### ISSUE THREAD

**Issue by njhoffman** [ibhagwan/fzf-lua#119] opened 2021-09-08 12:45 UTC
Hello, thank you for your work on getting fzf implemented with lua.

I noticed quite a few bugs the past day or so, centered around this:

`
Error executing luv callback:
...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:201: attempt to call a nil value
"after/syntax/lua.vim" 18L, 1428C
`

It's stemming from a bug with nvim-web-icons when multiple setup calls can clobber the icon map names, I'm pretty sure the offending lines in your project are core.lua:43:
```lua
  if config._has_devicons and config._devicons then
    icon, hl  = config._devicons.get_icon(file, ext:lower(), {default = true})
  else
    icon, hl = '', 'dark_grey'
  end

  -- allow user override of the color
  local override = config.globals.file_icon_colors[ext]
```

Instead of i.e. DevIconPy I was getting transformed to DevIconpy and not matched causing breaking errors.   
I made a pull request with a fix to their repo: https://github.com/kyazdani42/nvim-web-devicons/pull/77 but prob not a bad idea to put in a fallback handler in case icon matching doesn't go as planned.
But

**Comment by ibhagwan** [comment] 2021-09-08 15:23
This is indeed new code from PR #108 by @jdrouhard.

I'm just confirming the bug with you so I can apply the correct fix, so the bug in `devicons` will still return the highlight name only that the extensions will now be lowercase (i.e. DevIcon**py** instead of DevIcon**Py**) - is that the only way the icons names get clobbered?

**Comment by jdrouhard** [comment] 2021-09-08 15:32
I'm not clear how the icon highlight names are getting clobbered or set to lower case. I don't think this is a bug either here or in nvim-web-devicons. 

The code in question above only lowercases the extension when doing the lookup but calls setup() if it wasn't loaded yet. Setup() uses the highlight names straight from the plug-in.

@njhoffman Are you sure you aren't manually calling setup somewhere else?

**Comment by ibhagwan** [comment] 2021-09-08 15:50
Added a couple of workarounds to accommodate the lowercase extensions and make sure the code won't crash if it can't find a highlight.

https://github.com/ibhagwan/fzf-lua/commit/dfce17f266b7e35f9532377af366671f46b57232

**Comment by jdrouhard** [comment] 2021-09-08 15:58
Hmm @ibhagwan I don't think we need this, I don't think there's a bug here and that workaround looks kinda messy :(

Can we revert that until we dig further? I'd like to get more information about @njhoffman actual problem.

**Comment by ibhagwan** [comment] 2021-09-08 16:04
> Hmm @ibhagwan I don't think we need this, I don't think there's a bug here and that workaround looks kinda messy :(

I agree, it's messy and I'm not liking this but I prefer this to a bug.

> Can we revert that until we dig further? I'd like to get more information about @njhoffman actual problem.

I agree here as well, I'd like to revert this but **after we find what causes the bug** :-)

I'd like to get rid of the `char_is_lower()` part, this change is pretty harmless don't you think (and would also avoid this bug)?

https://github.com/ibhagwan/fzf-lua/blob/dfce17f266b7e35f9532377af366671f46b57232/lua/fzf-lua/core.lua#L217-L218

**Comment by ibhagwan** [comment] 2021-09-08 16:05
@jdrouhard  we can leave this issue open until we find the cause and remove the ugly workaround.

**Comment by jdrouhard** [comment] 2021-09-08 16:06
I don't think it's a bug, though. I think @njoffman has code elsewhere that is clobbering his devicons icon table. We should be able to rely on the devicons repo giving us the correct highlight codes.

**Comment by ibhagwan** [comment] 2021-09-08 16:07
> I don't think it's a bug, though. I think @njoffman has code elsewhere that is clobbering his devicons icon table. We should be able to rely on the devicons repo giving us the correct highlight codes.

Let's wait for more input from @njhoffman then.

**Comment by ibhagwan** [comment] 2021-09-08 16:11
@jdrouhard  I forced pushed the repo and commented out the ugly part, leaving just the  below until we get to the bottom of this issue and understand what causes his devicons extensions to return lowercase.

https://github.com/ibhagwan/fzf-lua/blob/2016be182addfa048d558dc12f0773a36fa53e60/lua/fzf-lua/core.lua#L217-L218

**Comment by ibhagwan** [comment] 2021-09-08 16:50
@njhoffman, I just read the (rather simple) code of `nvim-web-devicons` and I can’t find any reason why the extensions would return lowercase after running setup a few times.

Do you have any info why is this happening and how your devicons PR solves the issue?

It’s also very likely that @jdrouhard is right and something in your code causes this, are you using any icon overrides? Can you post your devicons setup function or link to your dot files?

**Comment by njhoffman** [comment] 2021-09-08 18:30
It very could very well be a setup problem on my end, but from my initial thoughts it does seem like a bug.  I took another quick look, and what is happening is the setup function is getting called repeatedly very fast because of (what I think) is a scope issue with this line in the nvim-webicons repo:
```
local loaded = false

local function setup(opts)
  -- if loaded then return end

  loaded = true

  local user_icons = opts or {}

  if user_icons.default then
    global_opts.default = true
  end

  if user_icons.override and user_icons.override.default_icon then
    default_icon = user_icons.override.default_icon
  end

  icons = vim.tbl_extend("force", icons, user_icons.override or {});

  table.insert(icons, default_icon)

  set_up_highlights()

  vim.cmd [[augroup NvimWebDevicons]]
  vim.cmd [[autocmd!]]
  vim.cmd [[autocmd ColorScheme * lua require('nvim-web-devicons').set_up_highlights()]]
  vim.cmd [[augroup END]]
end

local function get_icon(name, ext, opts)
  if not loaded then
    setup()
  end

```
The loaded flag is being set in the local function so for me everytime get_devicons is called it tries to setup again. and things just kind of fall apart from there.  Here is an output of how the icons get mangled after this occurs, I know it's kind of hard to read but basically the '+ " are for when it is correct, the "!! " is for when it's wrong, and I also mark each time setup i called.  I blasted away my shada file as well tomake sure nothing in there was causing issues.  I can look more tonight, but I'm turning my fix back on for now so I can get some other work done ;-).  Thanks again.
[fzf-lua.bug.txt](https://github.com/ibhagwan/fzf-lua/files/7131079/fzf-lua.bug.txt)

**Comment by jdrouhard** [comment] 2021-09-08 18:53
I think we'll need to see your dotfiles and full config. The `loaded` variable is local to the `nvim-web-devicons` module, and both `get_devicon()` and `setup()` access the same "local static" variable (the icon table works the same way).

It sounds like something is unloading your modules repeatedly, since it's not actually possible for the loaded variable to go back to false once changed to true. I added a print statement to `setup()` locally and it only gets called once, even though I have a custom setup option table and multiple plugins that use it.

**Comment by ibhagwan** [comment] 2021-09-08 19:45
@njhoffman instead of the fix you know you can also set `file_icons = false` yes?

**Comment by ibhagwan** [comment] 2021-09-08 20:21
> fzf-lua.bug.txt

Based on the contents of this file seems like you have some kind of circular require of `nvim-web-devicons`, lua should raise an exception so maybe it's dynamically generated somehow.

Like @jdrouhard said, we'll need to see the complete `~/.config/nvim` folder to solve this.

**Comment by ibhagwan** [comment] 2021-09-09 08:21
@njhoffman I was going to try and help you out and figure out the source of the issue in your dotfiles, I must say seeing the [amount of plugins you install](https://github.com/njhoffman/dotfiles/blob/master/.config/nvim-profiles/default/lua/plugins/load.lua) made me freak out lol

I think a safe first step here would be to try and see if this issue is reproduced with a minimal config with only fzf-lua and devicons installed (I believe it won’t).

Since the issue isn’t coming from fzf-lua and the below fix from earlier makes sure fzf-lua won’t break (worst case it will just return all grey colors) I’m going to close this issue. If you discover new information that points towards fzf-lua feel free to reopen the issue.

https://github.com/ibhagwan/fzf-lua/blob/2016be182addfa048d558dc12f0773a36fa53e60/lua/fzf-lua/core.lua#L217-L218

**Closed by ibhagwan** 2021-09-09 08:21 UTC
Labels: bug, invalid
