### ISSUE TITLE
Issues after new previewer got merged

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#67] opened 2021-08-30 16:52 UTC
Hey, it's been long time!

After upgrading to latest version of your plugin today I encountered two issues:

1) With custom `winopts_raw` I get following error

```
E5108: Error executing lua ...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:248: .../nvim/site/pack/packer/s
tart/fzf-lua/lua/fzf-lua/win.lua:304: attempt to call method 'rep' (a nil value)
```

My `winopts_raw` is set to function which returns something like 

```lua
{
  border = { { "▎", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "Nor
malFloat" }, { " ", "NormalFloat" }, { "▎", "NormalFloat" }, { "▎", "NormalFloat" } },
  col = 24,
  height = 38,
  relative = "editor",
  row = 58,
  style = "minimal",
  width = 72
}
```

2) Now obsolete (removed?) `window_on_create` is not called. How can I set up my my mapping to quit with `q` again?
```lua
 vim.api.nvim_buf_set_keymap(0, 't', '<Esc>', '<C-c>', { nowait = true, silent = true })
```

3) `preview_opts = 'hidden'` seems to be ignored, preview is always displayed.
Thanks!

**Comment by ibhagwan** [comment] 2021-08-30 17:12
> Hey, it's been long time!

Hey indeed :-)

> After upgrading to latest version of your plugin today I encountered two issues:
> 
>     1. With custom `winopts_raw` I get following error
> 
> 
> ```
> E5108: Error executing lua ...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:248: .../nvim/site/pack/packer/s
> tart/fzf-lua/lua/fzf-lua/win.lua:304: attempt to call method 'rep' (a nil value)
> ```
This should be fixed now, the reason this was happening is because the new preview window draws the border manually and uses the characters supplied to `borderchars`, I didn't even know you can specify a highlight like this, see my next note on how to fix you highlight.

> My `winopts_raw` is set to function which returns something like
> 
> ```lua
> {
>   border = { { "▎", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "Nor
> malFloat" }, { " ", "NormalFloat" }, { "▎", "NormalFloat" }, { "▎", "NormalFloat" } },
>   col = 24,
>   height = 38,
>   relative = "editor",
>   row = 58,
>   style = "minimal",
>   width = 72
> }
> ```
Note that this will now only highlight the fzf window border and not the preview border, but fear not as you don't even need this anymore, just set `winopts.hl_boder = "NormalFloat"` and you'll get the look you're after.

>     1. Now obsolete (removed?) `window_on_create` is not called. How can I set up my my mapping to quit with `q` again?
> 
> 
> ```lua
>  vim.api.nvim_buf_set_keymap(0, 't', '<Esc>', '<C-c>', { nowait = true, silent = true })
> ```
I deprecated it mostly to let users know about the new highlight settings (since I now draw the windows myself rather than rely on `nvim-fzf`), I won't remove it anytime soon, in fact I was planning on adding `fzf_on_create` and `preview_on_create` for finer grained control. If the deprecated message is bothering you I can expedite these additions.

>     1. `preview_opts = 'hidden'` seems to be ignored, preview is always displayed.
>        Thanks!

That's correct, I was going to parse the flags and look for the words `hidden|nohidden` and set the builtin previewer accordingly (as I do with the `right|left|up|down`) but I got lazy and put the option directly under `previewers.builtin.hidden`.

**Comment by ibhagwan** [comment] 2021-08-30 17:15
Btw, I can already imagine your next request which will be to set the fzf window dynamically based on the value of `hidden`, it's on my list to fix sometime lol

**Comment by gegoune** [comment] 2021-08-30 20:37
> Note that this will now only highlight the fzf window border and not the preview border, but fear not as you don't even need this anymore, just set winopts.hl_boder = "NormalFloat" and you'll get the look you're after.

I don't think I have ever used preview actually, had it hidden and togglable but never did that, I am sure I didn't.

Problem is that sizing is all wrong now, I have not changed my function and now window drawn by fzf has good position but only half of its horizontal size (vertically its OK).

> I deprecated it mostly to let users know about the new highlight settings (since I now draw the windows myself rather than rely on `nvim-fzf`), I won't remove it anytime soon, in fact I was planning on adding `fzf_on_create` and `preview_on_create` for finer grained control. If the deprecated message is bothering you I can expedite these additions.

I am not getting deprecation warning and function does not seem to be called at all. Have added `print()` call in there that does not get printed once fzf is opened.

> That's correct, I was going to parse the flags and look for the words hidden|nohidden and set the builtin previewer accordingly (as I do with the right|left|up|down) but I got lazy and put the option directly under previewers.builtin.hidden.

Does it mean `preview_opts` will get deprecated?

**Comment by ibhagwan** [comment] 2021-08-30 20:44
> > Note that this will now only highlight the fzf window border and not the preview border, but fear not as you don't even need this anymore, just set winopts.hl_boder = "NormalFloat" and you'll get the look you're after.
> 
> I don't think I have ever used preview actually, had it hidden and togglable but never did that, I am sure I didn't.
> 
> Problem is that sizing is all wrong now, I have not changed my function and now window drawn by fzf has good position but only half of its horizontal size (vertically its OK).
>

It’s wrong because you’re still technically using the built in previewer, set `default_previewer = 'bat'` and you’ll be back to what you had before.


> > I deprecated it mostly to let users know about the new highlight settings (since I now draw the windows myself rather than rely on `nvim-fzf`), I won't remove it anytime soon, in fact I was planning on adding `fzf_on_create` and `preview_on_create` for finer grained control. If the deprecated message is bothering you I can expedite these additions.
> 
> I am not getting deprecation warning and function does not seem to be called at all. Have added `print()` call in there that does not get printed once fzf is opened.

Maybe there is an issue with `window_on_create` inside winopts raw, let me check and get back to you on that.
 
> > That's correct, I was going to parse the flags and look for the words hidden|nohidden and set the builtin previewer accordingly (as I do with the right|left|up|down) but I got lazy and put the option directly under previewers.builtin.hidden.
> 
> Does it mean `preview_opts` will get deprecated?

Nope because the new option is only part of the new previewer, if anything the config is a bit messy now and the previewer part will have to to be refactored, I usually don’t make breaking changes or at least make sure it’s all backward compatible so don’t worry.

**Comment by gegoune** [comment] 2021-08-30 20:50
> It’s wrong because you’re still technically using the built in previewer, set default_previewer = 'bat' and you’ll be back to what you had before.

Ah, true, missed that, although I saw it in the commit, I forgot to set it! Sorry. :)

With that option set I am getting correct window size and dimensions again, lovely. Remaining issue is the one with keymap, will wait for you, no rush though! :)

> I usually don’t make breaking changes or at least make sure it’s all backward compatible so don’t worry.

Don't mind breaking changes, can just update config, was just asking if I should remove that option to keep my config clean.

And indeed, options are bit convoluted, that's why I suggested organising them bit more way back in https://github.com/ibhagwan/fzf-lua/issues/7#issuecomment-881012428. :)

**Comment by ibhagwan** [comment] 2021-08-30 20:53
> And indeed, options are bit convoluted, that's why I suggested organising them bit more way back in [#7 (comment)](https://github.com/ibhagwan/fzf-lua/issues/7#issuecomment-881012428). :)

That’s why I refused it back then, I wanted to complete the project with my entire TODO list so that I see how all the options interact in order to organize them better.

It’s not absolutely terrible now but the fact that the builtin previewer is fundamentally different than the one inside fzf threw me off a bit.

**Comment by ibhagwan** [comment] 2021-08-30 20:58
Btw, if you’re using buffers and want the old behavior you’d have to also add `previewer = false` under buffers, that will restore the old behavior, I specifically changed the buffers previewer default because I wasn’t happy with its barebones no syntax preview.

**Comment by ibhagwan** [comment] 2021-08-30 23:06
>I am not getting deprecation warning and function does not seem to be called at all. Have added print() call in there that does not get printed once fzf is opened.

I just tested it and my `window_on_create` is called, doesn't matter if it's defined in `winopts` or `winopts_raw`, the only difference is it doesn't raise the deprecated message when defined in `winopts_raw`,  I look at the code and fail to see how it's being skipped.

Can you post your setup function so I can try to reproduce?
The below is what I used as my `winopts_raw`:

```lua
    winopts_raw = function()
      local width = math.floor(vim.o.columns * 0.60)
      local height = math.floor(vim.o.lines * 0.65)
      if vim.o.columns < 120 then
        width = math.floor(vim.o.columns * 0.40)
      end
      local row = math.floor((vim.o.lines - height) * 0.50)
      local col = math.floor((vim.o.columns - width) * 0.50)
      return {
        height = height,
        width = width,
        row = row,
        col = col,
        -- border = 'none',
        window_on_create = function()
          print("window_on_create")
          vim.cmd("set winhl=Normal:NormalFloat,FloatBorder:VertSplit")
        end
      }
    end
```

Btw, you can also try and move the `window_on_create` under `winopts` directly and lmk if you see the deprecated message and does it get called from there?

**Comment by gegoune** [comment] 2021-08-30 23:13
Ah, I think we did come to conclusion a while ago that `window_on_create` can be separate option and it worked as below up until latest changes:

```lua
    require('fzf-lua').setup {
      window_on_create = function()
        -- vim.cmd 'set winhl=Normal:NormalFloat'
        print 'called'
        vim.api.nvim_buf_set_keymap(0, 't', '<Esc>', '<C-c>', { nowait = true, silent = true })
      end,
      winopts_raw = require('my.utils').floatArgs,
}
```

`floatArgs` is

```lua
    M.floatArgs = function()
      local columns = vim.o.columns
      local lines = vim.o.lines

      local width = math.floor(columns - (columns * 2 / 5))
      local height = math.floor(lines - (lines * 1 / 3))

      if columns < 120 then
        width = math.floor(columns - (columns * 1 / 5))
      end

      return {
        relative = 'editor',
        row = lines,
        col = math.floor((columns - width) / 2),
        width = width,
        height = height,
        border = require('my.utils').left_border,
        style = 'minimal',
      }
    end
```

**Comment by ibhagwan** [comment] 2021-08-30 23:28
> Ah, I think we did come to conclusion a while ago that `window_on_create` can be separate option and it worked as below up until latest changes:
> 
> ```lua
>     require('fzf-lua').setup {
>       window_on_create = function()
>         -- vim.cmd 'set winhl=Normal:NormalFloat'
>         print 'called'
>         vim.api.nvim_buf_set_keymap(0, 't', '<Esc>', '<C-c>', { nowait = true, silent = true })
>       end,
>       winopts_raw = require('my.utils').floatArgs,
> }
> ```
> 
> `floatArgs` is
> 
> ```lua
>     M.floatArgs = function()
>       local columns = vim.o.columns
>       local lines = vim.o.lines
> 
>       local width = math.floor(columns - (columns * 2 / 5))
>       local height = math.floor(lines - (lines * 1 / 3))
> 
>       if columns < 120 then
>         width = math.floor(columns - (columns * 1 / 5))
>       end
> 
>       return {
>         relative = 'editor',
>         row = lines,
>         col = math.floor((columns - width) / 2),
>         width = width,
>         height = height,
>         border = require('my.utils').left_border,
>         style = 'minimal',
>       }
>     end
> ```



Now I understand why it’s not working, I had a backward compatible option to copy all `winopts` params from the globals  into the `winopts` table, since I removed `window_on_create` from my default config the backward comparability doesn’t work anymore.

In your case it should look like the below:

```lua
require('fzf-lua').setup {
  winopts = {
    window_on_create = function() end()
  }
}
```

If it’s really critical for you I’ll restore it to how it was, lmk?

**Comment by gegoune** [comment] 2021-08-30 23:36
Aha, got it, it works set up as above. Also worked when I moved that function to table returned by `floatArgs`. Have updated my config to look like what you got above. Works fine, except for deprecation warning which I do see now. Not sure if deprecating it without providing alternative is a way to go. Or is there a new way of setting up such mapping for fzf window that I missed in incremental readme updates?

Thanks for all your help with this one, mainly being patient with me! And for such great plugin! Daily driver definitely!

**Comment by ibhagwan** [comment] 2021-08-31 00:00
> Aha, got it, it works set up as above. Also worked when I moved that function to table returned by `floatArgs`. Have updated my config to look like what you got above. Works fine, except for deprecation warning which I do see now. Not sure if deprecating it without providing alternative is a way to go. Or is there a new way of setting up such mapping for fzf window that I missed in incremental readme updates?
> 
> Thanks for all your help with this one, mainly being patient with me! And for such great plugin! Daily driver definitely!

You can move it inside `winopts_raw` to avoid the deprecated notice.

As I wrote somewhere above I was planning to separate it to two different functions `fzf_on_create` and `preview_on_create` separate for each window.

**Comment by ibhagwan** [comment] 2021-08-31 00:37
FYI, just committed a fix for issue #73, now when using the builtin previewer the main fzf window will adjust to the size when the preview is `hidden` and will expand/shrink when preview is toggled on/off (by default `F4`).

I'm mentioning this here because your layout was messed up with the builtin previewer, now you can have treesitter syntax previews even when using `hidden`.

**Comment by ibhagwan** [comment] 2021-08-31 00:37
And with that said I think we can close this issue :-)

**Closed by ibhagwan** 2021-08-31 00:37 UTC
Labels: bug

**Comment by gegoune** [comment] 2021-08-31 09:58
Awesome it does work. Thanks! There is an issue with opening and closing preview with builtin previewer. Will open another issue for it though as it does not bother me at all at the moment.

Thanks once again!

**Comment by ibhagwan** [comment] 2021-08-31 14:17
> Awesome it does work. Thanks! There is an issue with opening and closing preview with builtin previewer. Will open another issue for it though as it does not bother me at all at the moment.
> 
> Thanks once again!

Please do open an issue so I know what to fix.
