### ISSUE TITLE
lsp_code_actions does not work in Golang in sync mode (async = true)

### ISSUE THREAD

**Issue by dinhhuy258** [ibhagwan/fzf-lua#93] opened 2021-09-03 16:51 UTC
As the title.

Video:

https://user-images.githubusercontent.com/17776979/132040915-fba97f34-cf64-4305-9666-5114199a818b.mov

My config:

```lua
M.setup = function()
  local fzf_status_ok, fzf = pcall(require, "fzf-lua")
  if not fzf_status_ok then
    return
  end

  local fzf_actions_status_ok, actions = pcall(require, "fzf-lua.actions")
  if not fzf_actions_status_ok then
    return
  end

  fzf.setup {
    winopts = {
      win_height = 0.85, -- window height
      win_width = 0.80, -- window width
      win_row = 0.30, -- window row position (0=top, 1=bottom)
      win_col = 0.50, -- window col position (0=left, 1=right)
      -- win_border    = false,           -- window border? or borderchars?
      win_border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
      hl_normal = "Normal",
      hl_border = "FloatBorder",
    },
    fzf_layout = "reverse", -- fzf '--layout='
    fzf_args = "", -- adv: fzf extra args, empty unless adv
    fzf_binds = { -- fzf '--bind=' options
      "ctrl-d:half-page-down",
      "ctrl-u:half-page-up",
      "ctrl-f:page-down",
      "ctrl-b:page-up",
      "ctrl-a:toggle-all",
      "ctrl-l:clear-query",
    },
    preview_cmd = "", -- 'head -n $FZF_PREVIEW_LINES',
    preview_border = "border", -- border|noborder
    preview_wrap = "nowrap", -- wrap|nowrap
    preview_opts = "nohidden", -- hidden|nohidden
    preview_vertical = "down:60%", -- up|down:size
    -- preview_horizontal  = 'right:60%',  -- right|left:size
    preview_layout = "vertical", -- horizontal|vertical|flex
    -- flip_columns        = 120,            -- #cols to switch to horizontal on flex
    bat_theme = "Visual Studio Dark+", -- bat preview theme (bat --list-themes)
    -- provider setup
    files = {
      prompt = "Files❯ ",
      cmd = "", -- "find . -type f -printf '%P\n'",
      git_icons = true, -- show git icons?
      file_icons = true, -- show file icons?
      color_icons = true, -- colorize file|git icons
      actions = {
        ["default"] = actions.file_edit,
        ["ctrl-h"] = actions.file_split,
        ["ctrl-v"] = actions.file_vsplit,
        ["ctrl-t"] = actions.file_tabedit,
        ["ctrl-q"] = actions.file_sel_to_qf,
        ["ctrl-y"] = function(selected)
          print(selected[2])
        end,
      },
    },
    git = {
      files = {
        prompt = "GitFiles❯ ",
        cmd = "git ls-files --modified --others --exclude-standard",
        previewer = "git_diff",
        git_icons = true, -- show git icons?
        file_icons = true, -- show file icons?
        color_icons = true, -- colorize file|git icons
      },
      branches = {
        prompt = "Branches❯ ",
        cmd = "git branch --all --color",
        preview = "git log --graph --pretty=oneline --abbrev-commit --color {1}",
        actions = {
          ["default"] = actions.git_switch,
        },
      },
      icons = {
        ["M"] = { icon = "M", color = "yellow" },
        ["D"] = { icon = "D", color = "red" },
        ["A"] = { icon = "A", color = "green" },
        ["?"] = { icon = "?", color = "magenta" },
      },
    },
    oldfiles = {
      prompt = "History❯ ",
      cwd_only = false,
    },
    buffers = {
      prompt = "Buffers❯ ",
      file_icons = true, -- show file icons?
      color_icons = true, -- colorize file|git icons
      sort_lastused = true, -- sort buffers() by last used
      actions = {
        ["default"] = actions.buf_edit,
        ["ctrl-h"] = actions.buf_split,
        ["ctrl-v"] = actions.buf_vsplit,
        ["ctrl-t"] = actions.buf_tabedit,
        ["ctrl-x"] = actions.buf_del,
      },
    },
    quickfix = {
      -- cwd               = vim.loop.cwd(),
      file_icons = true,
      git_icons = true,
    },
    lsp = {
      prompt = "❯ ",
      -- cwd               = vim.loop.cwd(),
      file_icons = true,
      git_icons = false,
      lsp_icons = true,
      async_or_timeout = false,
      jump_to_single_result = true,
      severity = "hint",
      icons = {
        ["Error"] = { icon = "", color = "red" }, -- error
        ["Warning"] = { icon = "", color = "yellow" }, -- warning
        ["Information"] = { icon = "", color = "blue" }, -- info
        ["Hint"] = { icon = "", color = "magenta" }, -- hint
      },
    },
    -- placeholders for additional user customizations
    loclist = {},
    helptags = {},
    manpages = {},
  }

  local utils = require "utils"

  utils.set_keymap("n", "<Leader>fr", ":lua require('fzf-lua').live_grep({ cmd = \"vimrg\" })<CR>", { noremap = true })
  utils.set_keymap("n", "<Leader>fg", ":lua require('fzf-lua').git_files()<CR>", { noremap = true })
  utils.set_keymap("n", "<Leader>fc", ":lua require('fzf-lua').git_branches()<CR>", { noremap = true })
  utils.set_keymap("n", "<Leader>fb", ":lua require('fzf-lua').buffers()<CR>", { noremap = true })
  utils.set_keymap("n", "<Leader>fe", ":lua require('fzf-lua').oldfiles()<CR>", { noremap = true })
  utils.set_keymap("n", "<Leader>ff", ":lua require('fzf-lua').files()<CR>", { noremap = true })
end
```

Thank you

**Comment by ibhagwan** [comment] 2021-09-03 17:05
Ty for the detailed report! that is strange indeed, the LSP functions aren’t language aware, perhaps it has something to do with the LSP server running multiple client IDs, nevertheless this should have worked as multiple client were addressed at issue #39.

Can you tell me what is your LSP setup and which go language server you’re using? I’ll install the same version and see if I can reproduce.

**Comment by dinhhuy258** [comment] 2021-09-03 17:16
Thank you for quick response. For the golang lsp i am using gopls. This is my config https://github.com/dinhhuy258/dotfiles/blob/master/nvim/lua/lsp/init.lua.

You dont need to copy my lsp config, just setup as u want. The problem is not from lsp i think. You can see if i use the lsp action which provides by neovim and it works.  If i use fzf actions which provides by your plugin then it show nothing, i guest there are problems when showing fzf popup.

If u need anything from me, feel free let me know. I may respond your question quite slow since its too late at my place now. >.<

**Comment by ibhagwan** [comment] 2021-09-03 17:30
> Thank you for quick response. For the golang lsp i am using gopls. This is my config https://github.com/dinhhuy258/dotfiles/blob/master/nvim/lua/lsp/init.lua.
> 
> You dont need to copy my lsp config, just setup as u want. The problem is not from lsp i think. You can see if i use the lsp action which provides by neovim and it works. If i use fzf actions which provides by your plugin then it show nothing, i guest there are problems when showing fzf popup.

Yes, I saw that the first time, I know the issue is with `fzf-lua` I’m just need sure it’s coming from the LSP setup or parsing of the actions (more likely since you aren’t getting the “no actions found” message).

> If u need anything from me, feel free let me know. I may respond your question quite slow since its too late at my place now. >.<

Ty! Will keep you posted.

**Comment by ibhagwan** [comment] 2021-09-03 18:50
Strangely enough this works for me with `gopls`:

![screenshot-1630694777](https://user-images.githubusercontent.com/59988195/132052885-5cd49bbc-002b-41ac-923f-a21e98deb06d.png)

I noticed your actions aren't numbered (at about ~8s), is that just the screen capture cutting or is this how it appears for you? If so there might be something in the code action parsing preventing this from working:

For reference, this is how `lua vim.lsp.buf.code_action()` appears on my end:
```sh
Type  :qa  and press <Enter> to exit Nvim
Code Actions:
1. Add import:  "fmt"
2. Organize Imports
Type number and <Enter> or click with the mouse (q or empty cancels):
```

**Comment by ibhagwan** [comment] 2021-09-03 20:07
One more thing to test would be to run the non-async version of code_actions, this might print an error that would be more descriptive what's going on here:

```lua
:lua require('fzf-lua').lsp_code_actions({ async = false })
```

**Comment by dinhhuy258** [comment] 2021-09-04 03:42
You're right. Change the setting to async=true then the problem goes away. However, the flickering effect will occur when no code action is available. I think there is a problem with the sync call in `lsp_code_actions`.
The workaround for me now is to use async call in lsp_code_actions.
P/s: I updated the title of the bug to make it more meaningful

**Comment by dinhhuy258** [comment] 2021-09-04 03:47
The problem is from setting `jump_to_single_result=true`. If I disable this setting, it works fine. Maybe in your code, you should ignore the `jump_to_single_result` setting in lsp_code_actions.

**Comment by ibhagwan** [comment] 2021-09-04 04:13
I added this option (`jump_to_single_result`) with the intention of it being used in a single call not globally.

Nevertheless I’ll make sure to disable it for `code_actions` regardless.

**Comment by dinhhuy258** [comment] 2021-09-04 04:23
Thanks you for your support...  Btw can i close the issue?

**Comment by ibhagwan** [comment] 2021-09-04 04:24
Btw, until I get to the code again and fix it, you don’t need to disable it globally, just run this:

```lua

:lua require('fzf-lua').lsp_code_actions({ jump_to_single_reault = false })
```

**Comment by ibhagwan** [comment] 2021-09-04 04:26
> Thank you for your support... Btw can i close the issue?

You can close it if you wish or I’ll close it in a few hours when I get to my computer and add the code to disable it for code actions.

**Comment by dinhhuy258** [comment] 2021-09-04 04:26
Sure i will ><

**Comment by ibhagwan** [comment] 2021-09-04 07:44
https://github.com/ibhagwan/fzf-lua/commit/6c349939b85163bab21d3042cf2cc7f8a251fe87 should fix it.

**Comment by dinhhuy258** [comment] 2021-09-04 07:45
thank you

**Closed by ibhagwan** 2021-09-04 07:44 UTC
Labels: bug
