### ISSUE TITLE
Error executing vim.schedule lua callback: `.../lua/fzf-lua/previewer/builtin.lua:297: Expected Lua number stack traceback:  [C]: in function 'nvim_buf_is_valid'`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#327] opened 2022-01-24 15:17 UTC
I got this error when using the default `<C-x>` to close the hovered-buffer too quickly.

<img src="https://user-images.githubusercontent.com/24765272/150810018-fa7b3774-894f-4541-b2d3-176911ae05fd.png" width="700">

How to reproduce:

1. Open many buffers
2. Execute: `FzfLua buffers`
3. Pressing `<C-x>` as fast as you can

nvim info:

```
NVIM v0.7.0-dev+921-g1907a9481
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by ibhagwan** [comment] 2022-01-25 02:29
I can't reproduce it, I don't think I'm fast enogh :-)

In any event this is a pretty rare race condition, pressing `ctrl-x` attempts to refresh the fzf main window by closing and re-opening, if this happens while the buffer is still being fed into the preview window this can happen.

Unless the fix is very simple, I don't think it's worth it creating all kinds of workarounds for an edge case like this.

**Comment by ibhagwan** [comment] 2022-02-01 02:48
https://github.com/ibhagwan/fzf-lua/commit/3696489667eec357021eba0346c71608aff4f8a0 added extra safety check before populating the preview, should prevent this error.

**Closed** 2022-02-01 02:47 UTC
Labels: wontfix
