### ISSUE TITLE
How to remove hash from `:FzfLua tabs` when `--with-nth` is set to `false`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#1064] opened 2024-02-28 07:49 UTC
Forgiving me for not using a template. I'm clear that my problem is cause by this call:

```lua
vim.keymap.set('n', '<C-b>', function () require('fzf-lua').tabs {
  fzf_opts = { ['--with-nth'] = false }, -- add prefix `{tabnr})` to each item in the list.
  -- .. many omitted.
} end)
```

So when this option is passed into fzf-lua tabs, it shows me this:

<img src="https://github.com/ibhagwan/fzf-lua/assets/24765272/97853cc2-6031-42b6-b66f-a793d985965e" width="600">

I want to keep those `n)` for tab numbers but not the hash following it.

---

I also found another bug during testing:

There is an extra space at the end of what I have typed. For example when I typed `test` (without a space at the end):

<img src="https://github.com/ibhagwan/fzf-lua/assets/24765272/9dc56d3c-b459-4050-953c-53ef12ee2e02" width="600">

**Comment by ibhagwan** [comment] 2024-02-28 16:15
That’s the encoded tab cwd that was added in #1003 by @lbrayner,  it currently cannot be removed but perhaps we can move it to be the first item in the line so you can hide it with `--with-nth`.

> There is an extra space at the end of what I have typed. For example when I typed test (without a space at the end)

This is strange, I cannot reproduce it perhaps something related to your prompt character and fzf not being able to handle it, can you change the prompt and see if it gets solved? If so, that would be an upstream issue with fzf.

**Comment by nyngwang** [comment] 2024-02-28 16:24
> [...] can you change the prompt and see if it gets solved?

This solves it. Thank you for this part. It's good timing to remove some fancy bug-attracting features in my dotfiles.

> it currently cannot be removed but perhaps [...]

I have an idea. Is it possible to change the coloring for this encoded string specifically? If so I can turn it into a very dim color.

**Comment by ibhagwan** [comment] 2024-02-28 16:27
> This solves it. Thank you for this part. It's good timing to remove some fancy bug-attracting features in my dotfiles.

You can open an upstream issue with fzf if you want it fixed.

> I have an idea(as a workaround for now only). Is it possible to change the coloring for this encoded string specifically? If so I can turn it into a very dim color.

No need, I’ll move it to be first item in the line and then you can use `--with-nth=2..` and you’ll get the tabs with x) and no hash.

**Comment by ibhagwan** [comment] 2024-02-28 17:11
@nyngwang, update to the latest commit and use:
```lua
:= require("fzf-lua").tabs({fzf_opts={["--with-nth"]="2.."}})
```

@lbrayner, you might need to change your code a bit as the encoded cwd is now the first argument in the line, I also used `fzf-lua.lib.base64` to encode instead of `vim.base64` since we now have our own base64 lib (since Windows support).

**Comment by nyngwang** [comment] 2024-02-28 17:30
Just tested. It works. Feel free to close this issue when it's appropriate, and again thanks for you kindness :)

**Comment by lbrayner** [comment] 2024-02-28 17:38
@ibhagwan thanks !

**Comment by ibhagwan** [comment] 2024-02-28 18:04
> @ibhagwan thanks !

Great! closing.

**Closed by ibhagwan** 2024-02-28 18:04 UTC
Labels: question
