### ISSUE TITLE
Error detected while processing pre-vimrc command line when enable bat as default previewer

### ISSUE THREAD

**Issue by lodisy** [ibhagwan/fzf-lua#615] opened 2023-01-26 13:11 UTC
### Info

- Operating System: macOS
- Shell: fishshell
- Terminal: alacritty
- `nvim --version`: 
NVIM v0.9.0-dev-726+gddd69a6c8-dirty
Build type: Release
LuaJIT 2.1.0-beta3
- `fzf --version`: 0.36.0 (brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
-- all default settings except
-- ...
    preview = {
        default = "bat"
        -- ...
    }
})
```
</details>

### Description 

Bat command is available when directly use in terminal.

Here I just move the config into another file and require it from the init.lua file for lazy.nvim.

```lua
-- init.lua
return {
    "ibhagwan/fzf-lua"
    config = function()
        require("plugins.fzf.config").setup()
    end
}

-- config.lua
local M = {}
M.setup = function
    -- ...
    require('fzf-lua').setup({
        -- all default settings except
        -- ...
        preview = {
            default = "bat" -- everything works fine if use the builtin previewer
            -- ...
        }
    })
    --...
end

return M

```

<img width="1203" alt="Screenshot 2023-01-26 at 9 05 03 PM" src="https://user-images.githubusercontent.com/8101584/214842755-69b16cc9-8851-4e73-a6d2-8d790c887231.png">

**Comment by ibhagwan** [comment] 2023-01-26 15:39
Few questions:
- Does the default builtin preview work?
- Does this happen on all files or just neovim files?
- Does `config.lua` contain a neovim modeline?
- What happens if you try to run `bat ~/.config/nvim/config.lua` in the shell?

**Comment by lodisy** [comment] 2023-01-27 02:09
1. Yes, with the default builtin previewer
<img width="935" alt="Screenshot 2023-01-27 at 9 57 17 AM" src="https://user-images.githubusercontent.com/8101584/214993990-4299ecbe-d4c7-48ca-93db-a0d132559125.png">
2. All files
<img width="1186" alt="Screenshot 2023-01-27 at 9 58 56 AM" src="https://user-images.githubusercontent.com/8101584/214994177-a39f8a2e-65db-4ea4-9977-6ff4a1e99e9d.png">

3. Not truly understand the question, but this is the config file. Barely nothing just call the setup function.

<img width="518" alt="Screenshot 2023-01-27 at 10 08 21 AM" src="https://user-images.githubusercontent.com/8101584/214995220-ef6fd242-f7ca-41ad-94f9-97114f6c71cd.png">


5. It works as expected with `bat path/to/config.lua`

<img width="580" alt="Screenshot 2023-01-27 at 10 01 21 AM" src="https://user-images.githubusercontent.com/8101584/214994430-1d5c48c3-01fd-4ce2-b1b1-e590ba9c0d2b.png">

**Comment by lodisy** [comment] 2023-01-27 02:15
There was an error message in the preview section: `E5107: Error loading lua [string ":lua"]:1  ')' expected near '='` when navigating between files with arrow keys, but quickly disappeared.

**Comment by ibhagwan** [comment] 2023-01-27 20:31
I can’t seem to reproduce this with fish shell, more questions:
- What’s the output of `fish --version`
- Can you try setting the previewer to `bat_async` instead?
- Can you try running `export SHELL=/bin/bash` before running neovim?
- Can you try with the latest stable neovim 0.8.2 (can download an app image quickly from [here](https://github.com/neovim/neovim/releases/tag/v0.8.2)?

**Comment by lodisy** [comment] 2023-01-28 04:48
> 
1. fish, version 3.6.0
2. setting `bat_async` works
<img width="654" alt="Screenshot 2023-01-28 at 12 47 03 PM" src="https://user-images.githubusercontent.com/8101584/215242540-c5e47982-2537-4112-9184-8446d6dd2ce6.png">

Would try the other two later if necessary.

**Comment by ibhagwan** [comment] 2023-01-28 05:42
If you’re satisfied with the `bat_async` workaround that’s ok, I’d still like to the get to why this happens as opposed to applying a workaround.

**Comment by lodisy** [comment] 2023-01-28 05:59
> If you’re satisfied with the `bat_async` workaround that’s ok, I’d still like to the get to why this happens as opposed to applying a workaround.

3. issue persists
4. issue persists
<img width="616" alt="Screenshot 2023-01-28 at 1 58 22 PM" src="https://user-images.githubusercontent.com/8101584/215248935-bda61fd2-d76a-4d66-8241-4af0644e3ad0.png">

<img width="398" alt="Screenshot 2023-01-28 at 1 59 27 PM" src="https://user-images.githubusercontent.com/8101584/215248967-752de4b0-606c-4f8e-9bd4-ecd4ecbd9db8.png">

**Comment by ibhagwan** [comment] 2023-01-29 01:25
I guess this isn’t `fish` related, can you run `:FzfLua files previewer=bat debug=true` and then press `F3` to enable the preview line wrap (so I can inspect the full command) and post a screenshot of the preview debug info?

Should look like this:
![6B52C2D6-0250-4828-8D01-A6A84DD3A90E](https://user-images.githubusercontent.com/59988195/215298912-e116c4c2-b075-4ef8-900d-754d7740f351.jpeg)

**Comment by lodisy** [comment] 2023-01-29 03:07
> I guess this isn’t `fish` related, can you run `:FzfLua files previewer=bat debug=true` and then press `F3` to enable the preview line wrap (so I can inspect the full command) and post a screenshot of the preview debug info?
> 
> Should look like this: ![6B52C2D6-0250-4828-8D01-A6A84DD3A90E](https://user-images.githubusercontent.com/59988195/215298912-e116c4c2-b075-4ef8-900d-754d7740f351.jpeg)

<img width="646" alt="Screenshot 2023-01-29 at 11 03 15 AM" src="https://user-images.githubusercontent.com/8101584/215302189-fb05d9b9-34ef-4455-b692-d338d317ea7f.png">
Hi, I was unable to wrap it. I saw F3 is only for builtin previewer? Function keys are bounded on macOS. I changed it to S-down, but didn't work, I guess this is all the commands?
<img width="469" alt="Screenshot 2023-01-29 at 11 06 08 AM" src="https://user-images.githubusercontent.com/8101584/215302270-e31a5f17-18bc-47c5-a59f-c1003174af71.png">

**Comment by ibhagwan** [comment] 2023-01-29 03:39
> Hi, I was unable to wrap it. I saw F3 is only for builtin previewer? Function keys are bounded on macOS. I changed it to S-down, but didn't work, I guess this is all the commands?

Given we’re using the `bat` previewer which is using the fzf preview capability only the preview binds under `keymap.fzf` would work, Fzf does have a `toggle-preview-wrap` bind and would have worked under `keymap.fzf` but it wouldn’t matter much here since I don’t see the debug output at all in the preview window.

The way the bat previewer works is by running `bat <args> $(neovim --headless … <selected line>)`, the latter part used to extract the filename from the entry (strip icons, lines, columns, etc) and the command fails with the error you’re being displayed, I’m trying to think of new ways  else to debug this without a special branch with extra debug outputs.

**Comment by ibhagwan** [comment] 2023-01-29 03:44
Another way to enable preview line wrap with Fzf  is to set `winopts.preview.wrap = 'wrap'` (default is `nowrap`) , maybe there is a more insightful error message after the  `…pre-vimrc command line:` error?

**Comment by lodisy** [comment] 2023-01-29 04:59
> Another way to enable preview line wrap with Fzf is to set `winopts.preview.wrap = 'wrap'` (default is `nowrap`) , maybe there is a more insightful error message after the `…pre-vimrc command line:` error?

Still the same, the error message is like mentioned here, couldn't capture it cause it only showed when navigating between files.

You can see the opts in the background. Tried both setting `wrap` and also remapping the keys.

> There was an error message in the preview section: `E5107: Error loading lua [string ":lua"]:1 ')' expected near '='` when navigating between files with arrow keys, but quickly disappeared.
<img width="702" alt="Screenshot 2023-01-29 at 12 55 18 PM" src="https://user-images.githubusercontent.com/8101584/215305729-7bb83eba-4ae9-42e8-8c72-daf26a9810c7.png">

<img width="650" alt="Screenshot 2023-01-29 at 12 57 19 PM" src="https://user-images.githubusercontent.com/8101584/215305805-9f635ba5-54b8-4186-8dda-232dd0517130.png">

**Comment by lodisy** [comment] 2023-01-29 05:07
I tried re-installing the plugin, but it still persists. I previously used Linux and worked fine. I would try switching back to Linux using the same config later.

**Comment by ibhagwan** [comment] 2023-01-29 05:54
> I tried re-installing the plugin, but it still persists. I previously used Linux and worked fine. I would try switching back to Linux using the same config later.

I doubt this is an installation issue and also pretty sure this will work fine on your Linux box, when I get access to my computer I’ll send you a few commands to test from the command line that would hopefully help us isolate the issue.

**Comment by ibhagwan** [comment] 2023-02-01 19:07
Can you test all of the below and tell me which one (if any) fails on your setup from a `fish` shell?
> The preview window should display the filename, complexity of preview command increases as you go down in the list, the last command is similar to what is being run with the `bat` previewer
```sh
rg --files | fzf --preview-window=nohidden:right:50% --preview="echo {}"
rg --files | fzf --preview-window=nohidden:right:50% --preview='sh -c "echo {}"'
rg --files | fzf --preview-window=nohidden:right:50% --preview='sh -c "echo $(echo inner {})"'
rg --files | fzf --preview-window=nohidden:right:50% --preview='sh -c "nvim --headless --clean --cmd \"lua io.stdout:write({});os.exit(0)\""'
```

Another thing that will help is if you can run the `bat` preview and have it fail and while the fzf-lua is open run `ps -ef | grep fzf` and paste here **the entire fzf command**, that way we can see what exactly fails on your system.

**Comment by lodisy** [comment] 2023-02-02 02:27
Hello,

all 5 commands were working fine run in fish.

the output from last command

![PXL_20230202_022241722.jpg](https://user-images.githubusercontent.com/8101584/216215547-ec815545-5e80-4a1d-860c-be921727014c.jpg)

I didn't understand the exact steps in the 2nd part, so not sure if this is the expected output.


![PXL_20230202_022435126.jpg](https://user-images.githubusercontent.com/8101584/216215993-e902b83f-32d4-41fd-a6a3-a1aeaf2e3e0d.jpg)

**Comment by ibhagwan** [comment] 2023-02-02 02:48
> all 5 commands were working fine run in fish.

Tysm for testing!

> I didn't understand the exact steps in the 2nd part, so not sure if this is the expected output.

Sorry for not being more clear, I want to see what is the exact background command that's running while the bug is present, hopefully these are clearer instructions:
- Restore fzf-lua config to use `bat` (so that the preview fails)
- Have 2 terminal windows open (Side by side or different desktops, doesn't matter)
- In one terminal run neovim and open fzf-lua, navigate to a file where it the preview fails
- **While fzf-lua is open on one terminal** run `ps -ef | grep fzf` on the other terminal and post the output

**Comment by ibhagwan** [comment] 2023-02-02 03:12
Actually don't worry about it any longer, I was able to reprpduce this, the soluition will be fast tracked from here on :-)

Ty for your help! I'll keep you posted when this is solved.

**Comment by ibhagwan** [comment] 2023-02-02 03:56
Can you update to the latest commit (https://github.com/ibhagwan/fzf-lua/commit/c25c3f210670b5539ccff527e9702127d27cc322) and let me know if this solves the issue for you?

**Comment by linsijia628** [comment] 2023-02-02 05:08
> Can you update to the latest commit ([c25c3f2](https://github.com/ibhagwan/fzf-lua/commit/c25c3f210670b5539ccff527e9702127d27cc322)) and let me know if this solves the issue for you?

Great, it's fixed with this commit. Thanks!

**Comment by lodisy** [comment] 2023-02-02 05:09
> Can you update to the latest commit (https://github.com/ibhagwan/fzf-lua/commit/c25c3f210670b5539ccff527e9702127d27cc322) and let me know if this solves the issue for you?

👍 Thanks, this fixed for me.

**Comment by ibhagwan** [comment] 2023-02-02 05:11
> > Can you update to the latest commit ([c25c3f2](https://github.com/ibhagwan/fzf-lua/commit/c25c3f210670b5539ccff527e9702127d27cc322)) and let me know if this solves the issue for you?
> 
> 👍 Thanks, this fixed for me.

Ty for the update, we can finally close this :)

**Closed by ibhagwan** 2023-02-02 05:11 UTC
Labels: bug
