### ISSUE TITLE
Pasting text freezes FzfLua when using builtin previewer

### ISSUE THREAD

**Issue by tobiwild** [ibhagwan/fzf-lua#909] opened 2023-10-18 16:40 UTC
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Kitty / also tested in macOS Terminal
- `nvim --version`:
NVIM v0.10.0-dev-5383+g0818d6552-Homebrew
Build type: Release
LuaJIT 2.1.1696795921
Run "nvim -V1 -v" for more info
- `fzf --version`:
0.43.0 (brew)

- [x] The issue is reproducible with `mini.sh`

### Description 

Reproduce:

- run `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
- press `C-p` to open files prompt
- paste from clipboard via `<cmd>v`
- the first couple of characters are inserted, but then the UI hangs and no input is being processed 
- the only thing that helps is leaving terminal mode by using `<c-\\><c-n>`

I checked with `git bisect` and found that 32821ea80674c053d3c407034625925cb20dd101 introduced this behaviour, and indeed when I change the previewer for files to `bat` the issue is gone.

**Comment by ibhagwan** [comment] 2023-10-20 03:09
Ty for the report @tobiwild, I’ll look into it.

**Comment by ibhagwan** [comment] 2023-10-20 16:22
@tobiwild, I can't seem to reproduce this, can you share some more pointers when this happens exactly?

- How long is the string you're pasting?
- Does the string have any matches or it should show an empty preview?
- If this string has a match what filetype / what filesize is in the preview?
- Does this also happen with the builtin previewer in `hidden` state (press `F4`)?
- What happens if you enter the same string slowly without pasting?
- What happens if you enter the same string as fast as you can?
- Is this happening cosistently or randomly?
- What happens if you paste using neovim binds  `<C-\><C-n>p` (or from clipboard using  `<C-\><C-n>"+p"`

**Comment by ibhagwan** [comment] 2023-10-20 16:28
Can you also try to download [fzf v0.39 binary](https://github.com/junegunn/fzf/releases/tag/0.39.0)  and try the same with:
```lua
:lua require("fzf-lua").files({ fzf_bin = "/path/to/fzf-v0.39" })
```

**Comment by tobiwild** [comment] 2023-11-01 12:22
I checked again and found that the FZF zero event and the shell execution seems to be the issue, disabling this zero event helps. I tested also with disabling the `clear_preview_buf` call:

```diff
diff --git a/lua/fzf-lua/previewer/builtin.lua b/lua/fzf-lua/previewer/builtin.lua
index 9a4f558..f901db9 100644
--- a/lua/fzf-lua/previewer/builtin.lua
+++ b/lua/fzf-lua/previewer/builtin.lua
@@ -292,11 +292,14 @@ function Previewer.base:cmdline(_)
   return act
 end
 
+local calls = 0
 function Previewer.base:zero(_)
   local act = string.format("execute-silent(%s)",
     shell.raw_action(function(_, _, _)
-      self:clear_preview_buf(true)
-      self.last_entry = nil
+      calls = calls + 1
+      vim.notify("Previewer Zero Call " .. calls)
+      -- self:clear_preview_buf(true)
+      -- self.last_entry = nil
     end, "", self.opts.debug))
   return act
 end
```

The issue remains:

https://github.com/ibhagwan/fzf-lua/assets/891533/bcbda840-4663-4812-97e7-73abeb0956cf

Typing the string fast works fine, pasting via `<C-\><C-n>p` has the same issue.

But I now switched to `bat` which I'm also fine with.

**Comment by ibhagwan** [comment] 2023-11-02 02:48
> I checked again and found that the FZF zero event

The zero even is used to clear the previewer when fuzzy matching yields no results, it was only introduced since fzf 0.40 that’s why I asked to try with 0.39 as I suspected this might be it based on the commit you linked.


> I tested also with disabling the `clear_preview_buf` call:

from the video it seems your notification is being called and you can exit fzf-lua, what do you exactly mean by fzf-lua freezes”?


After analyzing your screencast this seems to be working as expected, typing `Previewer` simply yields no results (note the `0/63` in the info line I.e. no matches), can you try slowly deleting characters with backspace and see when you start getting results again?

**Comment by ibhagwan** [comment] 2023-11-24 16:29
Losing due to inactivity, feel free to reopen if this is still an issue @tobiwild.

**Comment by somnam** [comment] 2023-11-25 07:48
I'm having the same issue when pasting in `files` search:
* the length of the string doesn't matter that much, it just gets cut at some point and fzf window freezes
* there are no file matches for the string
* also happens when previewer is hidden
* this happens most of the time when pasting but occasionally there's no freeze

Here's an example:
https://github.com/ibhagwan/fzf-lua/assets/4627919/a5398205-5911-416a-92a5-7b307e43758e

Would it be possible to look into this issue? I'll try switching to a different previewer than the bulitin and see if this helps.

**Comment by ibhagwan** [comment] 2023-11-25 07:56
> Can you also try to download [fzf v0.39 binary](https://github.com/junegunn/fzf/releases/tag/0.39.0) and try the same with:
> 
> ```lua
> :lua require("fzf-lua").files({ fzf_bin = "/path/to/fzf-v0.39" })
> ```

@somnam, what is your fzf version? are you also on MacOS? Can you try with fzf version 0.39 as mentioned above and let me know if the issues exists with 0.39?

**Comment by somnam** [comment] 2023-11-25 15:10
> @somnam, what is your fzf version? are you also on MacOS? Can you try with fzf version 0.39 as mentioned above and let me know if the issues exists with 0.39?

Yep, I'm on MacOS too, but using bash & wezterm. I was using the latest fzf version 0.44.1 installed from git repo with `--bin` option. After switching back to 0.39 it looks like the issue has gone away. The problem seems to be linked with the zero event. Is there some additional info / debug I could provide?

**Comment by ibhagwan** [comment] 2023-11-27 09:22
> > @somnam, what is your fzf version? are you also on MacOS? Can you try with fzf version 0.39 as mentioned above and let me know if the issues exists with 0.39?
> 
> Yep, I'm on MacOS too, but using bash & wezterm. I was using the latest fzf version 0.44.1 installed from git repo with `--bin` option. After switching back to 0.39 it looks like the issue has gone away. The problem seems to be linked with the zero event (0.40.0 has the same problem for me). Is there some additional info / debug I could provide?

No need to provide any additional info, I was able to reproduce this, not sure what causes the freeze yet but it seams to stem from consecutive calls to the zero event, I have an idea to solve this with a singleton shell command, I’ll test it tomorrow and hopefully solve this issue.

**Comment by ibhagwan** [comment] 2023-11-27 16:54
@tobiwild, @somnam, turns out this is an issue with fzf, opened an issue upstream: https://github.com/junegunn/fzf/issues/3516

**Comment by ibhagwan** [comment] 2023-12-26 01:09
FYI, this is solved at the upstrem's HEAD, waiting for a [new release](https://github.com/junegunn/fzf/releases)  to close this issue.

**Comment by ibhagwan** [comment] 2024-01-01 06:47
Closing this with the release of fzf [v0.45](https://github.com/junegunn/fzf/releases/tag/0.45.0)

**Closed by ibhagwan** 2024-01-01 06:47 UTC
Labels: upstream
