### ISSUE TITLE
Didn't switch to the buffer by `Fzflua files` with `actions.file_edit`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#390] opened 2022-04-19 03:35 UTC
### Info

- Operating System: macOS 12.3.1
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: 
```
NVIM v0.8.0-dev+12-g147cc60d2
Build type: Release
LuaJIT 2.1.0-beta3
``` 
- `fzf --version`: 0.30.0 (brew)

- [ ] The issue is reproducible with `minimal_init.lua`

I got another error when calling `Fzflua files`:

<img src="https://user-images.githubusercontent.com/24765272/163914683-b0e78163-4ade-47fb-9455-0c7b31db0325.png" width="600">

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  fzf_cli_args = "-i", -- Case-Insensitive for: `Fzf files`, `buffers`.
  winopts = {
    border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
    height = 0.8,
    width = 0.5,
    row = 0.1,
    col = 0.9,
    preview = {
      title = false,
      wrap = 'wrap',
      vertical = 'down:80%',
      layout = 'vertical',
      delay = 100
    }
  },
  actions = {
    files = { default = actions.file_edit },
    buffers = { default = actions.buf_switch_or_edit },
  },
  lsp = {
    force_uri = false,
    actions = { default = actions.file_tabedit }
  },
  files = {
    prompt = ' File $ ',
    show_cwd_header = true,
    fd_opts =
      "--hidden "..
      "--no-ignore "..
      "--ignore-case "..
      "--type f "..
      -- "--max-depth 15 "..
      " "..
      "--exclude .local "..
      "--exclude .npm "..
      "--exclude .nvm "..
      "--exclude .tmux "..
      "--exclude .cache "..
      "--exclude .vscode "..
      " "..
      "--exclude .git "..
      "--exclude __pypackages__ "..
      "--exclude node_modules "..
      "--exclude package-lock.json "..
      "--exclude yarn.lock "..
      "--exclude tags "..
      "--exclude .DS_Store "..
      " "
  },
})
```
</details>

### Description 

The demo is not recorded with minimal config setup (as provided above) since it has another error. I expect that after my selection the file should be opened in the current window, not the `[No Name]` buffer.

https://user-images.githubusercontent.com/24765272/163915014-abd9293f-1623-4e5e-9c57-8086b91edbaa.mov

**Comment by nyngwang** [comment] 2022-04-19 03:41
**update**: I have tried the `actions.file_switch_or_edit`, still got the same result.

**Comment by ibhagwan** [comment] 2022-04-19 03:42
Is the error only with this specific file or does it happen with all files?
Did this also happen with 0.7 or only started since you are using the 0.8 nightly?

**Comment by nyngwang** [comment] 2022-04-19 03:47
> Is the error only with this specific file or does it happen with all files?

I just noticed that: If there are only `[No Name]` buffer(s) there before I run `Fzflua files`, the behaviour will appear.

> Did this also happen with 0.7 or only started since you are using the 0.8 nightly?

This also happened on 0.7.

**Comment by ibhagwan** [comment] 2022-04-19 03:50
>I just noticed that: If there is(are) only [No Name] buffer(s) there before I run Fzflua files, the behaviour will appear.

Let's focus first on the issue with `minimal_init.lua` because I can't reproduce this with or without the `[No Name]` buffer, it also seems that your default action is opening the file in a new tab? how can that be `file_edit`?

**Comment by nyngwang** [comment] 2022-04-19 03:52
> [...] it also seems that your default action is opening the file in a new tab? how can that be file_edit?

My bad. I forgot to mention that in the demo I used a plugin called bufferlines.nvim, which makes buffers look like tabs. It's indeed only one tab in the demo.

**Comment by ibhagwan** [comment] 2022-04-19 03:53
> > [...] it also seems that your default action is opening the file in a new tab? how can that be file_edit?
> 
> My bad. I forgot to mention that in the demo I used a plugin called bufferlines.nvim, which makes buffers look like tabs. It's indeed only one tab in the demo.

Can you try and reproduce it with `minimal_init.lua`? There are instructions inside the file how to test it easily without messing your setup, it would really help me if you can find the exact reproduction steps so I can identify the issue.

**Comment by nyngwang** [comment] 2022-04-19 04:01
> Can you try and reproduce it with `minimal_init.lua`?

My answer would be: I think this bug is probably caused by using together with another plugin(I'm using [`neo-tree.nvim`](https://github.com/nvim-neo-tree/neo-tree.nvim)), which will create an empty buffer from the start (right after I run `nvim .`). If this is not appropriate here I think this can be closed. Sorry for causing any inconvenience.

**Comment by ibhagwan** [comment] 2022-04-19 04:44
>My answer would be: I think this bug is probably caused by using together with another plugin(I'm using [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim)), which will create an empty buffer from the start (right after I run nvim .). If this is not appropriate here I think this can be closed. I did try to use minimal config to reproduce it, but that will be not possible by my intuition, since no plugin will create the cause: only [No Name] buffer(s) from the start.

Don’t need to close this bug until we understand where it’s coming from, if it’s possible to solve through fzf-lua I will do my best even if the cause is an interaction with another plugin, if we can understand exactly what part of `neo-tree` causes this I may be able to come up with a workaround.

> But somehow if there is(are) only [No Name] buffer(s), one of the existing [No Name] buffers will occupy the final window. This is what I can provide... Sorry for causing any inconvenience.

First thing I would look for are auto commands generated by neo-tree, is there any purpose for the `[No Name]` buffer? Why is it generated? Isn’t it just the default buffer when opening neovim?

**Comment by ibhagwan** [comment] 2022-04-19 04:47
> My bad. I forgot to mention that in the demo I used a plugin called bufferlines.nvim, which makes buffers look like tabs. It's indeed only one tab in the demo. The command I use will only call this:

If I understand correctly then it seems a new buffer names `neo-tree.lua` was generated but it’s empty so perhaps it’s path was somehow malformed, so  the `file_edit` command worked but opened a non-existing file?

**Comment by nyngwang** [comment] 2022-04-19 04:50
> [...] so the file_edit command worked but opened a non-existing file?

The `file_edit` is correct. But the result is that the current window still shows the `[No Name]` buffer, and the selected one is opened at another (hidden) buffer. (it's visible like a tab because the `bufferline.nvim`)

**Comment by ibhagwan** [comment] 2022-04-19 04:54
> The file_edit is correct. But the result is that the current window still shows the [No Name] buffer, and the selected one is opened at another (hidden) buffer. (it's visible like a tab because the bufferline.nvim)

In this case the issue is probably not in fzf-lua, something in your config (may or may not be `neo-tree`) is either preventing the window switch to the new buffer or forcing it to open hidden, it’s unlikely I can solve this in fzf-lua.

**Comment by nyngwang** [comment] 2022-04-19 04:55
> > [...] create a custom file_edit action function and see where it fails.
> I'm trying this one.

I'm trying to get the buffer id of the file selected by `Fzflua files`. Is there any existing API that can do this?

**Comment by ibhagwan** [comment] 2022-04-19 04:59
> I'm trying to get the buffer id of the buffer for the file selected by Fzflua files. Is there any existing API that can do this? Now I can only get the file path(including the filetype icon, which is annoying).

`FzfLua buffers` shows buffer numbers, if you mean programmatically you can use `vim.api.nvim_list_bufs()`.

**Comment by nyngwang** [comment] 2022-04-19 05:02
> [...] if you mean programmatically you can use `vim.api.nvim_list_bufs()`.

This will list all of the buffers. Is it possible to get just the one I selected by `Fzflua files`?

**Comment by ibhagwan** [comment] 2022-04-19 05:06
> Is there an existing way to get buffer id from selected?

Not inside `selected`, but after running `file_edit` you are technically inside the newly generated buffer, at this point you can run `vim.api.nvim_get_current_buffer()`, that should tell you if you’re in the new buffer or still stuck inside `[No Name]`.

**Comment by nyngwang** [comment] 2022-04-19 05:28
@ibhagwan Is it possible to manually assign a buffer (by its id) for that file to be opened?

**Comment by ibhagwan** [comment] 2022-04-19 05:29
> @ibhagwan Is it possible to manually assign a buffer (by its id) for that file to be opened?

Nope, neovim assigns that based on next available number.

**Comment by nyngwang** [comment] 2022-04-19 05:31
Then, Is it possible to manually assign an existing buffer (by its id) for that file to be opened?

**Comment by ibhagwan** [comment] 2022-04-19 05:33
> Then, Is it possible to manually assign an existing buffer (by its id) for that file to be opened? If this is possible I think I can use the existing `[No Name]` buffer to load the file.

Not possible, even if you switch into an existing window the edit command will generate a new buffer (or reuse an existing buffer if the file was already opened).

**Comment by nyngwang** [comment] 2022-04-19 05:56
@ibhagwan: Final one: How to check that the current buffer is unlisted (i.e. not shown in the `:ls`) and what's the recommended way to make it listed?

**Comment by nyngwang** [comment] 2022-04-19 06:07
I just got it fixed. I have to add one line after the two calls to make the selected file stay in the buffer of the current window:

```lua
files = { default = function (...)
  actions.file_switch(...)
  actions.file_edit(...)
  vim.cmd('edit #')
end },
```

and then I do some other works after neo-tree got closed.

**Closed** 2022-04-19 06:11 UTC
Labels: invalid

**Comment by ibhagwan** [comment] 2022-04-19 15:12
> I just got it fixed. It seems that all problems can be solved without any change from `fzf-lua` side.
> 
> I do some work (making this unlisted buffer get listed) after neo-tree got closed.

Nice job @nyngwang, but the question is why is it needed? What is causing buffers to open in the background instead of switching into the buffer? Was it neo-tree or bufferline?

**Comment by nyngwang** [comment] 2022-04-19 15:50
@ibhagwan I don't know... When I closed neo-tree using toggle it showed me an error message saying something like some content in the buffer will be discarded(I forgot the precise description, and am too lazy to reproduce it now...) So I tried to find some command that can "stage" those content into a buffer.

I can share it further after the author of neo-tree will fix the double-`[No Name]` problem, which occurred when the tree is opened with `float` option.

**Comment by nyngwang** [comment] 2022-05-02 09:14
I just got more clues on this bug. If I use the following command to trigger `Fzflua files`, the bug disappears:

```
vim.keymap.set('n', '<C-G>', function ()
  -- Close neo-tree before running fzf-lua
  if vim.bo.filetype == 'neo-tree' then vim.cmd('wincmd h') end
  require('fzf-lua').files()
end, NOREF_NOERR_TRUNC)
```

That is: If I run `Fzflua files` when my current window is of `filetype` `neo-tree` then this bug will happen.

ref: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/321

**Comment by kohane27** [comment] 2022-08-10 13:53
I was having this exact issue as well.


https://user-images.githubusercontent.com/57322459/183918076-25eb4e53-4a6e-4458-8ff8-e75c2098b1a5.mp4

To reproduce:

1. open nvim with `nvim .` in target dir
2. upon opening nvim the buffer target is on the tree
3. trigger `<cmd>lua require('fzf-lua').files()<cr>`
4. select target file
5. force quit of nvim

With the following remap:

```lua
vim.keymap.set("n", "<C-G>", function()
  -- create an empty buffer before running fzf-lua
  if vim.bo.filetype == "NvimTree" then
    vim.cmd("enew")
  end
  require("fzf-lua").files()
end, { noremap = true, silent = true, nowait = true })
```

https://user-images.githubusercontent.com/57322459/183918103-a246fa40-10b1-4fef-a3ec-2d240fa6792a.mp4

This issue is gone.

My tabline plugin of choice is [barbar.nvim](https://github.com/romgrk/barbar.nvim), but I tried [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) and the same issue persists. I guess if `filetype` is not valid, `fzf-lua` will force quit.

Hope this helps!

**Comment by ibhagwan** [comment] 2022-08-10 14:18
Ty for the info @kohane27!

**Comment by kohane27** [comment] 2022-08-15 10:59
@ibhagwan 

Update on the my previous comment.

Apologies again; my bad. The error has nothing to do with fzf-lua itself. It was the following code from my [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua):

```lua
vim.cmd([[
" automatically close the tab when nvim-tree is the last window in the tab
autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif
]])
```

Once I commented out the above lines the issue is gone. 

Thanks again! I'm absolutely loving `fzf-lua` it makes navigating files and dir a joy!
