### ISSUE TITLE
Error when typing a lot characters and then delete them

### ISSUE THREAD

**Issue by TroySigX** [ibhagwan/fzf-lua#652] opened 2023-02-17 02:38 UTC
### Info

- Operating System: Endeavour OS 6.1.12-arch1
- Shell: bash 5.1.16
- Terminal: Yakuake
- `nvim --version`: 0.8.3
- `fzf --version`: latest

- [x] The issue is reproducible with `mini.sh`

### Description 
When find files (using `require('fzf-lua').files()`), if I type a lot of characters (more than 70) and then delete all of them, fzf-lua stops suggesting files in the directory

**Comment by ibhagwan** [comment] 2023-02-17 02:50
This sounds like an `fzf` issue, once fzf-lua interface is open and all files have been processed it’s no longer in the hands of fzf-lua (unless it’s `live_grep`), at this point it’s just fzf fuzzy matching a list of files in the neovim terminal.

What version of fzf are you using? Does “latest” mean 0.38?
Can you try it in the shell directly with `rg --files | fzf`?

If you’re still experiencing the same behavior in the shell this issue will need to be opened upstream instead.

**Comment by TroySigX** [comment] 2023-02-17 03:01
Yes, I'm using fzf version 0.38

**Comment by ibhagwan** [comment] 2023-02-17 03:01
I was just able to reproduce this in the shell outside of neovim, it's an fzf bug most likely.

Would you like to open an issue [upstream](https://github.com/junegunn/fzf/issues)?

**Comment by TroySigX** [comment] 2023-02-17 04:59
Yes, it'll be great if you do that

**Comment by ibhagwan** [comment] 2023-02-17 18:17
Here's the reproduction outside of neovim / fzf-lua:
![Peek 2023-02-17 10-09](https://user-images.githubusercontent.com/59988195/219746210-5a3d55bb-891a-468d-b791-b870880c4501.gif)

Closing since I can't do anything about it other than the opened issue upstream: https://github.com/junegunn/fzf/issues/3176

**Closed by ibhagwan** 2023-02-17 18:17 UTC
Labels: bug, wontfix

**Comment by ibhagwan** [comment] 2023-02-19 15:11
FYI, this was fixed upstream at https://github.com/junegunn/fzf/commit/b1459c79cfc004dd7944f4db3ffb5a4ae20569ca, should be solved with the next fzf release.

**Comment by TroySigX** [comment] 2023-02-19 15:45
That's great!
