### ISSUE TITLE
[help] How to send all results—selected or not—to quickfix?

### ISSUE THREAD

**Issue by bravoecho** [ibhagwan/fzf-lua#546] opened 2022-10-17 10:08 UTC
Hi, I was looking in the docs and in `actions.lua`, to see if I could change the default action for the non-interactive `:FzfLua grep`. I would like to reproduce `vim-grepper`'s behaviour, that is, directly send all the results to the quickfix. Is it possible? Thanks!

**Comment by ibhagwan** [comment] 2022-10-17 10:50
Duplicate of #324, take a look and see if that solves your issue.

**Comment by ibhagwan** [comment] 2022-10-18 08:04
Not sure if I understand what you mean, can you elaborate or better yet post a screenshot so I can understand what you mean by:
>but when I press enter in the Grep For> prompt, I still get the results in a terminal.

**Comment by bravoecho** [comment] 2022-10-19 13:04
Sure, thanks!

I enter my search:

![image](https://user-images.githubusercontent.com/698828/196697775-e733572d-19aa-4cc5-acfb-b483ac7ad427.png)

and when I press enter a window named `:term//...` opens

![image](https://user-images.githubusercontent.com/698828/196697800-3cdaf312-70d2-4efc-bcb5-dd8b8079522c.png)

instead, I need the quickfix to open, as if I had used `:vimgrep foo **/*` followed by `:copen`.

**Comment by bravoecho** [comment] 2022-10-20 08:04
I see now, you are right! I'm just primed into thinking in terms "command > output > quickfix", and then operate on it, by jumping or by `:cfdo` 🤦‍♂️ Sorry about the confusion.

You are right, in this case I could just use the right combination of `:grep`, `grepprg`, a custom command and `:copen | wincmd J`. In both cases populating the `quickfix` would be synchronous.

Synchronous used to be OK, but when I started working on embarrassingly large repositories, that no longer cut it. So I found that <https://github.com/mhinz/vim-grepper> solved the issue, because it populates the `quickfix` asynchronously.

I guess I'll stick to it for a little longer—even it's not in Lua 😉—and use `fzf-lua` as a replacement for `fzf.vim`.

Regarding the wonky preview in the screenshot, it's only because for some reason I resized the term window with the mouse, but they were initially the same height 🙂

**Comment by bravoecho** [comment] 2022-10-20 08:05
PS: thank you so much for your friendly feedback, hugely appreciated!

**Comment by ibhagwan** [comment] 2022-10-20 08:57
> use fzf-lua as a replacement for fzf.vim.

Yes.

> Regarding the wonky preview in the screenshot, the one I posted above is my full setup, it's only wonky because for some reason I resized the term window with the mouse, but they were initially the same height, so no problem there 🙂

Happy to know it’s not a bug :)

**Closed** 2022-10-21 09:52 UTC
Labels: duplicate

**Comment by jsbmg** [comment] 2023-09-26 17:44
Hello, it seems this isn't working in the latest version - the syntax has changed.

I'm attempting to accomplish the above with this:
```
        grep = {
          actions = {
            ["enter"] = { prefix = "select-all+", fn = actions.file_edit_or_qf } 
          }
        },
```

But it seems that "select-all+" isn't actually working. Am I doing this incorrectly? I don't see an action for select_all.

**Comment by ibhagwan** [comment] 2023-09-26 18:15
> But it seems that "select-all+" isn't actually working. Am I doing this incorrectly? I don't see an action for select_all.

There isn’t an fzf-lua action to select all, this is an fzf (the binary) action, this prefix’s the fzf-lua action with a “select all”.

**Comment by ibhagwan** [comment] 2023-09-26 18:35
@jsbmg, you're mixing up a few things, if you wish to send all results to quickfix, take a look at #324,  use :
```lua
  grep = {
    keymap = { fzf = { ["enter"] = "select-all+accept" } },
    actions = { ["default"] = { actions.file_edit_or_qf },
  },
```

The reason this works is because the keys are first interpreted by fzf which in turns selects all items and "accepts" (i.e. fzf exits and sends all selected items as output), fzf-lua will then interpret the action with "enter" being the default action, `edit_or_qf` will then see more than one file was selected and send it all to the quickfix.

**Comment by jsbmg** [comment] 2023-09-26 19:00
@ibhagwan makes perfect sense now. Thank you!
