### ISSUE TITLE
[dashboard compatibility] New buffer left when opening a new buffer with dashboard open

### ISSUE THREAD

**Issue by sQVe** [ibhagwan/fzf-lua#21] opened 2021-07-25 17:56 UTC
👋🏼 

If I open `nvim` it start `dashboard` and then I open a file into a buffer. There's now two buffers open, one with the file and one that is new. This is not how `fzf.vim` work - it should only have the buffer with the file open.

Using the following setup:

```lua
    use {
        'ibhagwan/fzf-lua',
        event = 'VimEnter',
        requires = {'ibhagwan/nvim-fzf', 'kyazdani42/nvim-web-devicons'}
    }
```

https://user-images.githubusercontent.com/2284724/126908581-e99c787e-0c61-4bef-8937-e1d4f48a401c.mp4

**Comment by ibhagwan** [comment] 2021-07-25 18:24
I found the crux of the issue, seems that `dashboard-nvim` has hard coded compatibility with both Telescope and vim-clap, take a look at [dashboard.vim#L41](https://github.com/glepnir/dashboard-nvim/blob/master/plugin/dashboard.vim#L41), `autocmd User TelescopeFindPre,ClapOnEnter call dashboard#close_preview()` which closes the dashboard preview when telescope or vim-clap user events are signaled.

Obviously this doesn't happen with `fzf-lua`, I'm trying to figure out if I can solve it without having to PR dashboard with a custom event, just as a test I tried hijacking the event and send `TelescopeFindPre` but it doesn't seem to solve the issue.

The issue is probably in `dashboard`, even without opening a file the simple action of opening `fzf-lua` leaves an empty buffer in `dashboard`, I'll do some more digging see if I can work around it.

**Comment by ibhagwan** [comment] 2021-07-25 19:26
Ok, so unfortunately the isn't what I describe in the previous comment, that issue relates to dashboard's preview window (not sure what that is but I can guess).

I'm not sure why but after existing `fzf-lua` and reentering dashboard again, dashboard generates another `[No Name]` buffer, you can see that if you run `fzf-lua.buffers()` you'll see the newly created buffer is number `#3` (which is a new buffer, `fzf-luz` will open at buffer `#2` on a new instance).

This issue is better suited for dashboard, I would have tried to solve it and PR dashboard but it has too much vimscript to my liking :-)

**Comment by sQVe** [comment] 2021-07-25 19:41
@ibhagwan I just find it strange that it works properly for `fzf.vim`.

**Comment by ibhagwan** [comment] 2021-07-25 19:49
> @ibhagwan I just find it strange that it works properly for `fzf.vim`.

I’m with you on that, I really have no clue why it does that, only that it creates a new buffer that isn’t generated by `fzf-lua`, I thought perhaps specific buffer options used for the created floating window in `fzf-lua` but I am running pretty much the same buffer and window options as Telescope so I’m as puzzled as you. All I know with high certainty is the new buffer isn’t created by `fzf-lua`.

I have a strong feeling this is also related to the previous issue we had of the floating window that isn’t closed properly when dashboard is used, I fixed it by force closing the window but I’m still unsure why it happened.

Sorry I can’t be of more help.

**Comment by ibhagwan** [comment] 2021-07-25 20:00
I commented on your [dashboard issue #92](https://github.com/glepnir/dashboard-nvim/issues/92), will leave this issue open until we get to the bottom of it, either here or in dashboard, I might give it another go when I have time later.

**Comment by ibhagwan** [comment] 2021-07-25 20:15
I just applied another fix for `nvim-fzf`, I'm still convinced this is an issue with some `autocmd` in dashboard but somehow changing the order of first closing the window and then deleting the buffer (rather than wiping the buffer and the checking if the window is still open), solved the issue.

If you're still using my fork of `nvim-fzf` just update and it should be solved, lmk if otherwise?

**Closed by ibhagwan** 2021-07-25 20:15 UTC

**Comment by ibhagwan** [comment] 2021-07-26 15:06
Just FYI, turns out this bug also exists or existed with Telescope too, [dashboard issue #88](https://github.com/glepnir/dashboard-nvim/issues/88).
