### ISSUE TITLE
Latest commit breaks LSP / TypeScript symbols

### ISSUE THREAD

**Issue by jackfranklin** [ibhagwan/fzf-lua#934] opened 2023-11-22 18:13 UTC
Hey,

I just updated to the latest fzf-lua and I am finding that with https://github.com/ibhagwan/fzf-lua/commit/c9ed5be563e07ef8d4ca1e650f3c091e19f4c5b2 running I am seeing far fewer results in a TypeScript project when looking up document symbols.

I have yet to debug more, and can try do when I get time, but this is the before (ignore the contents - this is a little side project game I am building):

![Screenshot 2023-11-22 181141](https://github.com/ibhagwan/fzf-lua/assets/193238/efb60999-b6c2-4b92-ba2c-a17b792f4745)

And this is what it looks like with the latest commit, on the same source file, same TS version, same Neovim, etc.

![Screenshot 2023-11-22 181222](https://github.com/ibhagwan/fzf-lua/assets/193238/81957449-4309-4256-9dda-2fb01d6834b7)

I am on Neovim NVIM v0.10.0-dev-1114+g35e50d79c

**Comment by ibhagwan** [comment] 2023-11-22 18:34
That’s definitely a bug, checking.

**Comment by ibhagwan** [comment] 2023-11-22 19:24
https://github.com/ibhagwan/fzf-lua/commit/413c4192cca3ac9296ff4d4c2ca2a404bb07d33b

@jackfranklin, the above commit most likely fixes this bug, can you check and let me know?

**Comment by ibhagwan** [comment] 2023-11-22 20:29
Better yet, try the latest https://github.com/ibhagwan/fzf-lua/commit/ea6829bdcbd08e9387b6af6bda7d31964124c085, should also fix formatting alignment of files in `lsp_workspace_symbols`.

**Comment by miklhh** [comment] 2023-11-24 11:21
I can confirm that this issue manifests for `lsp_document_symbols` when used with clangd.
On commit 1e33086

**Comment by ibhagwan** [comment] 2023-11-24 15:47
@miklhh, doesn’t seem to be an issue in the screenshot your provided, the first screenshot (by @jackfranklin) shows the fzf interface still loading (the < arrow in the info line is still green), in the new, in the new screenshot you sent there is no loading indicator which tells me these are all the symbols in this document.

What makes you think the issue is still there, can you compare the result set with an earlier commit?

**Comment by miklhh** [comment] 2023-11-25 08:56
Sorry for being unclear. To me, a git bisection reveals: `c9ed5be563e07ef8d4ca1e650f3c091e19f4c5b2 is the first bad commit`

`c9ed5be`:
![bad](https://github.com/ibhagwan/fzf-lua/assets/24571764/7c20b99d-379a-4dca-9742-b8c0a625344a)

`99684a6` (my expected result):
![good](https://github.com/ibhagwan/fzf-lua/assets/24571764/48d64681-11b0-4ac5-815d-f8fe24852e72)

**Comment by ibhagwan** [comment] 2023-11-25 16:23
Ty @miklhh, that’s a slightly different  issue, all results are there, they symbol names are wrong (cut) - I’ll fix it.

**Comment by ibhagwan** [comment] 2023-11-25 17:44
https://github.com/ibhagwan/fzf-lua/commit/08a63827636b3169d60d14e458c98e758a77e937 - @miklhh, this should fix it, lmk?

**Comment by miklhh** [comment] 2023-11-25 18:48
08a6382 seems to have fixed the problem for me with clangd. Thank you! :)

**Comment by ibhagwan** [comment] 2023-11-25 18:50
Ty for the update @miklhh, closing.

**Closed by ibhagwan** 2023-11-25 18:50 UTC
Labels: bug

**Comment by jackfranklin** [comment] 2023-11-25 19:01
Sorry for my slow reply, this is working perfectly now. Thank you so much for a speedy reply and for such a great plugin!

**Comment by ibhagwan** [comment] 2023-11-25 19:02
Ty for the update @jackfranklin!
